import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {createHash} from 'node:crypto';
import {createReportThroughputObserver} from '../../scenarios/lz-ppm/report-throughput-observer.mjs';
const extensionId='ari:cloud:ecosystem::extension/app/env/static/ppm-dashboard';
const sha=s=>createHash('sha256').update(s).digest('hex');
const envelope=body=>JSON.stringify({data:{invokeExtension:{success:true,contextToken:{jwt:'renewed-corpus-secret',expiresAt:'later'},errors:null,response:{body}}}});
function setup(options={}){const page=new EventEmitter(),saved=[],events=[];const observer=createReportThroughputObserver({page,extensionId,emit:e=>events.push(e),saveResponse:(id,e)=>saved.push({id,e}),...options});return {page,saved,events,observer};}
function external(f,kind,raw,privacy={}){const id=f.observer.beginExternal(kind,kind==='hook'?'plan':'getSponsorReportPage',{planId:'plan-test-corpus'});let reads=0;const response=kind==='hook'?new Response(raw):{status:()=>200,text:async()=>{reads++;return raw;}};f.observer.externalResponse(id,response,privacy);f.observer.endExternal(id);return {id,response,reads:()=>reads};}
test('full hook source and RPC pages survive exact dual-digest receipt',async()=>{const f=setup();const source={meta:{id:'plan-test-corpus',version:9},issues:[{key:'X-1',children:['X-2'],fieldAvail:{duration:true},_original:{duration:null}}]};const raw=JSON.stringify(source,null,2),a=external(f,'hook',raw);const page={success:true,page:{page:0,rows:[{key:'X-1',duration:null,critical:false}],hash:'hash'}},rpcRaw=envelope(page),b=external(f,'rpc',rpcRaw);assert.deepEqual(await a.response.json(),source);const result=await f.observer.finish();assert.equal(result.complete,true);assert.equal(f.saved.length,2);for(const [n,original]of [raw,rpcRaw].entries()){const e=f.saved.find(v=>v.id===[a.id,b.id][n]).e;assert.equal(e.responseSha256,sha(original));assert.equal(e.responseBytes,Buffer.byteLength(original));assert.equal(e.retainedResponseSha256,sha(e.raw));assert.equal(e.retainedResponseBytes,Buffer.byteLength(e.raw));assert.equal(e.rawEncoding,'forge-response-context-token-redacted-v1');assert.equal(Object.hasOwn(e,'data'),false);}assert.deepEqual(JSON.parse(f.saved.find(v=>v.id===a.id).e.raw),source);assert.deepEqual(JSON.parse(f.saved.find(v=>v.id===b.id).e.raw).data.invokeExtension.response.body,page);assert.equal(b.reads(),1);assert.doesNotMatch(JSON.stringify(f.saved),/renewed-corpus-secret/);});
test('actual UI begin call is retained as a separately validated call receipt without transport',async()=>{const f=setup(),call={functionKey:'captureSponsorReport',payload:{planId:'plan-test-corpus',name:'Exact request',requestId:'uuid',expectedVersion:9,changes:[]}};const req={url:()=> 'https://example.invalid/gateway/api/graphql',postDataBuffer:()=>Buffer.from(JSON.stringify({variables:{input:{extensionId,payload:{contextToken:'request-corpus-secret',call}}}})),allHeaders:async()=>({cookie:'session=opaque-corpus-secret'}),timing:()=>({})};f.page.emit('request',req);f.page.emit('response',{request:()=>req,status:()=>200,text:async()=>envelope({success:true,job:{id:'job'}})});f.page.emit('requestfinished',req);assert.equal((await f.observer.finish()).complete,true);assert.equal(f.saved.length,1);assert.deepEqual(JSON.parse(f.saved[0].e.requestCall.raw),call);assert.equal(f.saved[0].e.requestCall.retainedResponseSha256,sha(f.saved[0].e.requestCall.raw));assert.doesNotMatch(JSON.stringify(f.saved),/request-corpus-secret|opaque-corpus-secret|renewed-corpus-secret|cookie/);});
test('known opaque secret echo, unsafe credential key and unknown JWT refuse evidence without changing business outcome',async()=>{for(const [body,privacy]of [[{issues:[],echo:'opaque-corpus-secret'},{requestHeaders:{Authorization:'Bearer opaque-corpus-secret'}}],[{issues:[],accessToken:'unrecognized'},{}],[{issues:[],echo:'eyJhbGciOiJIUzI1NiJ9.abcdef.signature'},{}]]){const f=setup();external(f,'hook',JSON.stringify(body),privacy);const r=await f.observer.finish();assert.equal(r.complete,false);assert.equal(r.records[0].outcome,'success');assert.equal(f.saved.length,0);assert.ok(r.errors.some(e=>e.kind==='response-evidence'));assert.doesNotMatch(JSON.stringify([r,f.events]),/opaque-corpus-secret|unrecognized|eyJhbGci/);}});
test('held evidence sink never holds later request dispatch or body timestamps',async()=>{let release;const held=new Promise(r=>release=r),f=setup({saveResponse:()=>held});external(f,'rpc',envelope({success:true}));await new Promise(r=>setImmediate(r));external(f,'hook','{"issues":[]}');assert.equal(f.observer.snapshot().records.length,2);assert.ok(f.observer.snapshot().records[0].bodyTerminal);release();assert.equal((await f.observer.finish()).complete,true);});
test('throwing and rejected response sinks fail evidence grade with safe fixed diagnostics',async()=>{for(const sink of [()=>{throw Error('opaque sink secret');},()=>Promise.reject(Error('opaque sink secret'))]){const f=setup({saveResponse:sink});external(f,'rpc',envelope({success:true}));const result=await f.observer.finish();assert.equal(result.complete,false);assert.doesNotMatch(JSON.stringify([result,f.events]),/opaque sink secret/);assert.equal(result.records[0].outcome,'success');}});
test('absent optional sink preserves prior response behavior and does not inspect private request headers',async()=>{const f=setup({saveResponse:undefined});external(f,'hook','{"accessToken":"legacy-opaque-value"}');assert.equal((await f.observer.finish()).complete,true);assert.equal(f.saved.length,0);});
test('an opaque credential echoed by a failed response is withheld from both evidence sinks',async()=>{const failures=[],f=setup({saveFailure:(id,raw)=>failures.push({id,raw})});external(f,'rpc',envelope({success:false,error:'opaque-corpus-secret'}),{requestToken:'opaque-corpus-secret'});const result=await f.observer.finish();assert.equal(result.complete,false);assert.equal(f.saved.length,0);assert.equal(failures.length,1);assert.equal(JSON.parse(failures[0].raw).contentOmitted,true);assert.doesNotMatch(JSON.stringify([failures,f.events,result]),/opaque-corpus-secret|renewed-corpus-secret/);});
test('unsafe job strings and all optional error projections withhold arbitrary details',async()=>{
 const secret='opaque-diagnostic-secret',f=setup();external(f,'rpc',envelope({success:true,job:{id:'job',stageLabel:secret}}),{requestToken:secret});let r=await f.observer.finish();assert.equal(r.complete,false);assert.doesNotMatch(JSON.stringify([r,f.events,f.saved]),/opaque-diagnostic-secret/);
 for(const mode of ['body','external','observer','network']){
  const f=setup(),failure=Error(secret);
  if(mode==='observer')f.observer.recordObserverFailure(failure);
  else if(mode==='network'){const req={url:()=> 'https://example.invalid/gateway/api/graphql',postDataBuffer:()=>Buffer.from(JSON.stringify({variables:{input:{extensionId,payload:{call:{functionKey:'presenceBeat',payload:{planId:'owned'}}}}}})),timing:()=>({}),failure:()=>({errorText:secret})};f.page.emit('request',req);f.page.emit('requestfailed',req);}
  else {const id=f.observer.beginExternal('rpc','getPlan',{});if(mode==='body')f.observer.externalResponse(id,{status:()=>200,text:async()=>{throw failure;}});f.observer.endExternal(id,failure,mode==='external');}
  r=await f.observer.finish();assert.equal(r.complete,false);assert.doesNotMatch(JSON.stringify([r,f.events]),/opaque-diagnostic-secret/);assert.ok(r.errors.some(e=>e.detailSha256===sha(secret)));
 }
});
