import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {admitForecastResume,resumedJob,preservedArtifacts,resumeToPublication,sourceReceiptSha} from '../../scenarios/lz-ppm/seventeenth-forecast-resume-contract.mjs';
const dir='evidence/lz-campaign/seventeenth-source-return-readonly-20260906/artifacts/scenarios-lz-ppm-campaign--755d0-eserve-exact-retained-state-chromium',bytes=fs.readFileSync(dir+'/seventeenth-source.json'),journal=JSON.parse(bytes),initial=journal.finalJob,probe=journal.finalProbe,previous={job:initial,probe};
test('actual successful source-return receipt admits exact active78/full134 baseline',()=>{assert.equal(createHash('sha256').update(bytes).digest('hex'),sourceReceiptSha);assert.deepEqual(admitForecastResume(journal,sourceReceiptSha,previous),previous);});
test('wrong receipt, unknown prior call, mutation, failed integrity or changed manifest refuse',()=>{for(const edit of [j=>j.completed=false,j=>j.advanceCalls=1,j=>j.sourceAndPreferencesPreserved=false,j=>j.forensicCalls[0].httpStatus=424,j=>j.probes[1].privateArtifacts.pop(),j=>j.finalJob.checkpoint++,j=>j.events.push({stage:'body-error'})]){const j=structuredClone(journal);edit(j);assert.throws(()=>admitForecastResume(j,sourceReceiptSha,previous));}assert.throws(()=>admitForecastResume(journal,'0'.repeat(64),previous));});
const next=(j,state='active')=>({...j,checkpoint:j.checkpoint+1,completedUnits:j.checkpoint+1,totalUnits:250,state,stageLabel:'Calculating forecast runs',forecastRuns:{completed:j.forecastRuns?j.forecastRuns.completed+1:0,total:40}});
test('acknowledgement rejects changed owner identities, names, checkpoint skips and failed states',()=>{const valid=next(initial);assert.deepEqual(resumedJob(valid,initial),valid);for(const edit of [j=>j.id='foreign',j=>j.requestId='foreign',j=>j.name='other',j=>j.reportId='other',j=>j.createdAt='other',j=>j.expiresAt='other',j=>j.checkpoint+=1,j=>j.checkpoint-=1,j=>j.state='failed',j=>j.state='cancelled',j=>j.cleanupDone=true,j=>j.completedUnits--]){const j=structuredClone(valid);edit(j);assert.throws(()=>resumedJob(j,initial));}});
test('original full physical history must remain exactly present as new immutable artifacts appear',()=>{assert.deepEqual(preservedArtifacts(probe,initial,probe),probe);for(const edit of [p=>p.privateArtifacts[0].actualHash='0'.repeat(64),p=>p.privateArtifacts[0].present=false,p=>p.privateArtifacts.pop()]){const p=structuredClone(probe);edit(p);assert.throws(()=>preservedArtifacts(p,initial,probe));}});
const wire=job=>({httpStatus:200,outerSuccess:true,body:{success:true,job}});
test('serial continuation requires each fresh status and physical probe before next RPC and reaches publication',async()=>{let job=initial,calls=0,inflight=0;const events=[];const final=await resumeToPublication({initial,advance:async payload=>{assert.equal(inflight,0);inflight++;assert.equal(payload.expectedCheckpoint,job.checkpoint);calls++;job=next(job,calls===45?'complete':'active');if(calls>=41){job.forecastRuns={completed:40,total:40};job.stageLabel=({41:'Combining forecast runs',42:'Verifying forecast results',43:'Preparing the retained schedule',44:'Preparing forecast results',45:'Report captured'})[calls];}return wire(job);},status:async()=>job,probe:async j=>{assert.equal(j,job);inflight--;},onObserved:v=>events.push(v)});assert.equal(final.state,'complete');assert.equal(calls,45);assert.equal(events.filter(e=>e.stage==='advance-response').length,45);assert.equal(events.filter(e=>e.stage==='checkpoint-verified').length,45);assert.equal(events.find(e=>e.stage==='forecast-complete').runAcknowledgements,40);});
test('unknown/timeout/refused/malformed/failed response stops after one actual call without retry',async()=>{for(const bad of [()=>{throw new Error('timeout');},()=>({httpStatus:424}),()=>({httpStatus:200,outerSuccess:true,body:{success:false,error:'busy'}}),()=>wire({...next(initial),state:'failed'}),()=>wire(initial)]){let calls=0;const events=[];await assert.rejects(resumeToPublication({initial,advance:async()=>{calls++;return bad();},status:async()=>assert.fail('status cannot follow invalid ack'),probe:async()=>assert.fail('probe cannot follow invalid ack'),onObserved:v=>events.push(v)}));assert.equal(calls,1);assert.ok(events.some(e=>e.stage==='advance-response'||e.stage==='advance-transport-error'));}});
test('fresh saved-state mismatch or physical corruption stops before second advance',async()=>{for(const fail of ['status','probe']){let calls=0;const job=next(initial);await assert.rejects(resumeToPublication({initial,advance:async()=>{calls++;return wire(job);},status:async()=>fail==='status'?{...job,checkpoint:80}:job,probe:async()=>{throw new Error('physical corruption');}}));assert.equal(calls,1);}});
test('finite checkpoint budget stops acknowledged active job without manufactured publication',async()=>{let calls=0,job=initial;await assert.rejects(resumeToPublication({initial,maxSteps:2,advance:async()=>{calls++;job=next(job);return wire(job);},status:async()=>job,probe:async()=>{}}),/budget/);assert.equal(calls,2);});
import {uiRequestClass} from '../../scenarios/lz-ppm/seventeenth-forecast-resume-contract.mjs';import {retained} from '../../scenarios/lz-ppm/seventeenth-report-recovery-contract.mjs';
test('UI route allows only exact-owned presence bookkeeping alongside real reads',()=>{for(const functionKey of ['presenceBeat','presenceLeave']){assert.equal(uiRequestClass({functionKey,payload:{planId:retained.planId}}),'owned-presence');assert.equal(uiRequestClass({functionKey,payload:{planId:'other'}}),'forbidden');assert.equal(uiRequestClass({functionKey,payload:{}}),'forbidden');}assert.equal(uiRequestClass({functionKey:'getSponsorReport',payload:{planId:retained.planId}}),'read');for(const functionKey of ['captureSponsorReport','advanceSponsorReportCapture','cancelSponsorReportCapture','deleteSponsorReport','deletePlan','saveCapacitySettings','updatePlan','applyChanges'])assert.equal(uiRequestClass({functionKey,payload:{planId:retained.planId}}),'forbidden');});
import {UI_READS} from '../../scenarios/lz-ppm/seventeenth-forecast-resume-contract.mjs';import path from 'node:path';
test('every exact UI read is an actual registered resolver; lookalike prefixes never authorize mutation',()=>{const dir='../lz-ppm-forge/src/resolvers',text=fs.readdirSync(dir).filter(f=>f.endsWith('.js')).map(f=>fs.readFileSync(path.join(dir,f),'utf8')).join('\n');assert.equal(new Set(UI_READS).size,UI_READS.length);for(const key of UI_READS){assert.ok(new RegExp(`(?:define|guarded)\\(['"]${key}['"]`).test(text),key);assert.equal(uiRequestClass({functionKey:key}),'read');}for(const functionKey of ['cancelSponsorReportCapture','canDeleteEverything','getAndDelete','listThenWrite','searchAndApply','checkThenClear'])assert.equal(uiRequestClass({functionKey}),'forbidden');});
import {createForecastProgress} from '../../scenarios/lz-ppm/seventeenth-forecast-resume-contract.mjs';
test('forecast progress refuses counter skips, duplicated run acknowledgements, premature fold and altered run budget',()=>{
 for(const bad of [j=>j.forecastRuns.completed=1,j=>j.forecastRuns.total=20,j=>delete j.forecastRuns,j=>j.stageLabel='Combining forecast runs']){const progress=createForecastProgress(),j=next(initial);bad(j);assert.throws(()=>progress.accept(j,initial));}
 for(const bad of [j=>j.forecastRuns.completed=0,j=>j.forecastRuns.completed=2,j=>j.forecastRuns.total=39]){const progress=createForecastProgress(),a=next(initial);progress.accept(a,initial);const b=next(a);bad(b);assert.throws(()=>progress.accept(b,a));}
 const progress=createForecastProgress(),a=next(initial);progress.accept(a,initial);const malformed={...a,stageLabel:'Combining forecast runs'};assert.throws(()=>progress.accept({...next(a),forecastRuns:{completed:0,total:40}},malformed));assert.throws(()=>progress.finish({...a,state:'complete'}));
});
test('physical immutable run headers exactly match acknowledged run count, with no future header',()=>{const job=next(initial),p=structuredClone(probe);job.forecastRuns={completed:1,total:40};p.checkpoint=job.checkpoint;const keyHash=createHash('sha256').update(JSON.stringify(`p:${retained.planId}:report-jobs:data:${retained.jobId}:forecast-run-0`)).digest('hex');p.privateArtifacts.push({keyHash,expectedHash:'a'.repeat(64),present:true,actualHash:'a'.repeat(64)});p.privateManifestHash=createHash('sha256').update(JSON.stringify(p.privateArtifacts.map(a=>a.keyHash))).digest('hex');assert.deepEqual(preservedArtifacts(p,job,probe),p);assert.throws(()=>preservedArtifacts(p,{...job,forecastRuns:{completed:0,total:40}},probe));assert.throws(()=>preservedArtifacts({...p,privateArtifacts:p.privateArtifacts.slice(0,-1),privateManifestHash:probe.privateManifestHash},job,probe));});
