import net from 'node:net';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {chromium} from 'playwright';
const out=path.resolve('scratch/lz-human-chrome152'),owned=fs.mkdtempSync(path.join(os.tmpdir(),'lz-human-chrome152-')),profile=path.join(owned,'profile'),downloads=path.join(owned,'downloads');fs.mkdirSync(path.join(profile,'Default'),{recursive:true});fs.mkdirSync(downloads);fs.writeFileSync(path.join(profile,'Default','Preferences'),JSON.stringify({download:{default_directory:downloads,prompt_for_download:false}}));
const exe='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';const journal={startedAt:new Date().toISOString(),owned,profile,downloads,exe,version:execFileSync(exe,['--version'],{encoding:'utf8'}).trim(),launchMode:'direct-headed-binary-CDP-noDefaults',cycles:[]};assert.match(journal.version,/152\.0\.7977\.76/);const save=()=>fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(journal,null,2)+'\n');save();
const wait=ms=>new Promise(r=>setTimeout(r,ms));const deadline=async(fn,ms=30000)=>{const end=Date.now()+ms;while(Date.now()<end){const v=await fn();if(v)return v;await wait(100);}throw new Error('Bounded condition timed out');};
const fixture=path.join(owned,'fixture.html');fs.writeFileSync(fixture,`<!doctype html><html><head><title>Owned normal Chrome download probe</title></head><body style="font:22px system-ui;padding:50px;background:#fff;color:#172b4d"><h1>Owned local download control</h1><p>No Jira, login, or shared browser profile.</p><button id="download">Download local report</button><div id="status">Ready</div><script>const n=new URL(location.href).searchParams.get('cycle');document.querySelector('button').onclick=()=>{const content='<!doctype html><html><body><h1>Owned report cycle '+n+'</h1><p>Complete Unicode proof: α—✓</p></body></html>';const url=URL.createObjectURL(new Blob([content],{type:'text/html'}));const a=document.createElement('a');a.href=url;a.download='owned-report-'+n+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#status').textContent='Clicked cycle '+n;};</script></body></html>`);
try{for(let i=1;i<=3;i++){
 const cycle={cycle:i,startedAt:new Date().toISOString(),events:[]};journal.cycles.push(cycle);save();const event=(name,detail={})=>{cycle.events.push({name,time:new Date().toISOString(),...detail});save();};
 const listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));const args=[`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,'--no-first-run','--no-default-browser-check',`${pathToFileURL(fixture).href}?cycle=${i}`];cycle.argv=args;const log=fs.openSync(path.join(out,`chrome-${i}.log`),'w');const child=spawn(exe,args,{stdio:['ignore',log,log]});fs.closeSync(log);cycle.pid=child.pid;const exited=once(child,'exit');child.on('exit',(code,signal)=>event('process-exit',{code,signal}));let browser,cdp;
 try{
  const endpoint=`http://127.0.0.1:${port}`;await deadline(async()=>{try{return(await fetch(endpoint+'/json/version')).ok;}catch{return false;}});
  browser=await chromium.connectOverCDP(endpoint,{noDefaults:true});event('attached-noDefaults');assert.equal(browser.contexts().length,1);const context=browser.contexts()[0],page=context.pages().find(p=>p.url().startsWith(pathToFileURL(fixture).href))||context.pages()[0];assert.ok(page);await page.goto(`${pathToFileURL(fixture).href}?cycle=${i}`);cdp=await context.newCDPSession(page);cycle.cdpVersion=await cdp.send('Browser.getVersion');assert.match(cycle.cdpVersion.product,/Chrome\/152\.0\.7977\.76/);assert.equal(await page.evaluate(()=>navigator.webdriver),false);cycle.webdriver=false;
  await page.locator('#download').click();event('actual-button-click');const output=path.join(downloads,`owned-report-${i}.html`),expected=`<!doctype html><html><body><h1>Owned report cycle ${i}</h1><p>Complete Unicode proof: α—✓</p></body></html>`;
  await deadline(()=>fs.existsSync(output)&&!fs.readdirSync(downloads).some(n=>n.endsWith('.crdownload')));const bytes=fs.readFileSync(output);assert.equal(bytes.toString('utf8'),expected);cycle.download={path:output,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};event('named-file-bytes-complete');
  await wait(2500);assert.equal(child.exitCode,null);const rendered=await context.newPage();await rendered.goto(pathToFileURL(output).href);assert.equal(await rendered.locator('h1').innerText(),`Owned report cycle ${i}`);assert.equal(await rendered.locator('p').innerText(),'Complete Unicode proof: α—✓');await rendered.screenshot({path:path.join(out,`rendered-cycle-${i}.png`)});event('subsequent-render-verified');await rendered.close();await cdp.send('Browser.close');event('graceful-browser-close-requested');const [code,signal]=await Promise.race([exited,wait(15000).then(()=>{throw new Error('Own browser did not cleanly exit');})]);assert.equal(code,0);assert.equal(signal,null);await browser.close();browser=null;
  assert.equal(fs.existsSync(path.join(profile,'SingletonLock')),false);cycle.history=JSON.parse(execFileSync('python3',['-c','import sqlite3,json,sys; c=sqlite3.connect("file:"+sys.argv[1]+"?mode=ro",uri=True); print(json.dumps(c.execute("select target_path,state,received_bytes,total_bytes from downloads order by id").fetchall()))',path.join(profile,'Default','History')],{encoding:'utf8'}));assert.equal(cycle.history.length,i);assert.ok(cycle.history.every(row=>row[1]===1));cycle.passed=true;save();
 }catch(error){cycle.error=String(error);save();try{if(cdp&&child.exitCode===null)await cdp.send('Browser.close');}catch{}try{await browser?.close();}catch{}throw error;}
 await wait(1000);
 }journal.passed=true;
}catch(error){journal.error=String(error);process.exitCode=1;}finally{journal.finishedAt=new Date().toISOString();save();}
