import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import {admitPrelude} from '../../scenarios/lz-ppm/seventeenth-prelude-contract.mjs';
const load=path=>{const b=fs.readFileSync(new URL(path,import.meta.url)),full=JSON.parse(b),keys=['retained','phase','advanceCalls','sourceAndPreferencesPreserved','publicationObserved','outcome','completed','lastWriteReturnedMs','finalJob','finalProbe','previousDiagnostic'];return {j:{...Object.fromEntries(keys.map(k=>[k,full[k]])),probes:[full.probes[0]]},sha:createHash('sha256').update(b).digest('hex')};};
const old=load('../../evidence/lz-campaign/seventeenth-retained-analysis-diagnostic-20260906/artifacts/scenarios-lz-ppm-campaign--8294a-pendent-integrity-preserved-chromium/seventeenth-advance.json'),latest=load('../../evidence/lz-campaign/seventeenth-context-first-diagnostic-20260906/artifacts/scenarios-lz-ppm-campaign--bc021-pendent-integrity-preserved-chromium/seventeenth-context-first-advance.json'),now=latest.j.lastWriteReturnedMs+120000;
const run=(a=latest.j,b=old.j,time=now,sha=latest.sha,olderSha=old.sha)=>admitPrelude(a,sha,b,olderSha,time);
test('two exact actual immutable receipts admit only same retained job and full manifest',()=>{assert.deepEqual(run(),{job:latest.j.finalJob,probe:latest.j.finalProbe});});
test('either receipt digest or chained previous digest mismatch refuses',()=>{assert.throws(()=>run(latest.j,old.j,now,'a'.repeat(64)));assert.throws(()=>run(latest.j,old.j,now,latest.sha,'b'.repeat(64)));assert.throws(()=>run({...latest.j,previousDiagnostic:{sha256:'c'.repeat(64)}}));});
test('latest exact return plus finite lease boundary and unknown preserved outcome mandatory',()=>{for(const t of[NaN,Infinity,now-1])assert.throws(()=>run(latest.j,old.j,t));for(const patch of[{lastWriteReturnedMs:old.j.lastWriteReturnedMs},{advanceCalls:2},{sourceAndPreferencesPreserved:false},{publicationObserved:true},{outcome:'advanced'},{completed:true}])assert.throws(()=>run({...latest.j,...patch}));});
test('a manifest internally coherent but changed from older receipt cannot admit',()=>{const j=structuredClone(latest.j);j.finalProbe.privateArtifacts[0].expectedHash='changed';j.finalProbe.privateArtifacts[0].actualHash='changed';j.probes[0]=structuredClone(j.finalProbe);assert.throws(()=>run(j));});
test('missing, extra, unknown job or public artifact refuses without weakening old controls',()=>{for(const mutate of[j=>j.finalProbe.privateArtifacts.pop(),j=>j.finalProbe.privateArtifacts.push(j.finalProbe.privateArtifacts[0]),j=>j.finalJob.id='foreign',j=>j.finalProbe.publicArtifacts.push({present:true}),j=>j.finalProbe.privateArtifacts[0].present=false]){const j=structuredClone(latest.j);mutate(j);assert.throws(()=>run(j));}});
