import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';import {chromium} from 'playwright';
const out=path.resolve('scratch/lz-ephemeral-chrome152'),sourcePath=path.resolve('../lz-ppm-forge/static/ppm-ui/src/components/planning/SponsorReports.jsx'),source=fs.readFileSync(sourcePath,'utf8'),start=source.indexOf('    const url = URL.createObjectURL'),end=source.indexOf('\n    setNotice(`Downloaded all',start);assert.ok(start>0&&end>start);const block=source.slice(start,end);fs.writeFileSync(path.join(out,'actual-production-blob-block.js.txt'),block+'\n');
const journal={startedAt:new Date().toISOString(),sourcePath,sourceSha256:createHash('sha256').update(source).digest('hex'),blobBlockSha256:createHash('sha256').update(block).digest('hex'),mode:'chromium.launch-channel-chrome-new-ephemeral-context-default-managed-downloads',cycles:[]};const save=()=>fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(journal,null,2)+'\n');const wait=ms=>new Promise(r=>setTimeout(r,ms));save();
try{for(let cycle=1;cycle<=3;cycle++){
 const c={cycle,startedAt:new Date().toISOString(),downloads:[],events:[]};journal.cycles.push(c);const event=(name,detail={})=>{c.events.push({name,time:new Date().toISOString(),...detail});save();};let browser,context,error;
 try{
  browser=await chromium.launch({channel:'chrome'});event('ordinary-launch-completed');const session=await browser.newBrowserCDPSession();c.version=await session.send('Browser.getVersion');assert.match(c.version.product,/Chrome\/152\.0\.7977\.76/);const processes=await session.send('SystemInfo.getProcessInfo');c.pid=processes.processInfo.find(p=>p.type==='browser').id;context=await browser.newContext();const page=await context.newPage();page.on('crash',()=>event('page-crash'));context.on('close',()=>event('context-closed'));browser.on('disconnected',()=>event('browser-disconnected'));
  for(let n=1;n<=3;n++){
   const selected={id:`owned-${cycle}-${n}`},html=`<!doctype html><html><head><meta charset="utf-8"><title>Owned managed report ${cycle}/${n}</title></head><body><h1>Owned managed report ${cycle}/${n}</h1><p>Complete Unicode proof: α—✓</p></body></html>`;
   await page.setContent('<!doctype html><html><body><button>Download complete local HTML</button></body></html>');await page.evaluate(({block,selected,html})=>{document.querySelector('button').onclick=new Function('selected','html',block).bind(null,selected,html);},{block,selected,html});
   event('download-wait',{n});const pending=page.waitForEvent('download');await page.locator('button').click();const downloaded=await pending;event('download-event',{n,filename:downloaded.suggestedFilename()});assert.equal(downloaded.suggestedFilename(),`sponsor-report-${selected.id}.html`);const file=path.join(out,`actual-download-${cycle}-${n}.html`);await downloaded.saveAs(file);assert.equal(await downloaded.failure(),null);const bytes=fs.readFileSync(file);assert.equal(bytes.toString('utf8'),html);c.downloads.push({n,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),file});event('full-file-verified',{n});await wait(2500);
   const doc=await context.newPage();await doc.goto(pathToFileURL(file).href);assert.equal(await doc.locator('h1').innerText(),`Owned managed report ${cycle}/${n}`);assert.equal(await doc.locator('p').innerText(),'Complete Unicode proof: α—✓');if(n===3)await doc.screenshot({path:path.join(out,`rendered-cycle-${cycle}.png`)});await doc.close();event('subsequent-render-verified',{n});
  }
 }catch(e){error=e;c.error=String(e);save();throw e;}finally{
  const cleanup=[];try{await context?.close();event('context-clean-close-completed');}catch(e){cleanup.push(e);}try{await browser?.close();event('browser-clean-close-completed');}catch(e){cleanup.push(e);}if(cleanup.length)throw new AggregateError([...(error?[error]:[]),...cleanup],'Original body and browser close errors');
 }
 let alive=true;for(let i=0;i<30;i++){try{process.kill(c.pid,0);}catch{alive=false;break;}await wait(100);}assert.equal(alive,false);c.processAbsentAfterCleanClose=true;c.passed=true;save();
 }journal.passed=true;
}catch(e){journal.error=String(e);process.exitCode=1;}finally{journal.finishedAt=new Date().toISOString();save();}
