import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {admitRetainedBytes,validateRetainedState,verifyRetainedFresh,requireCleanupAuthority,retainedPhase,originalPlans,retainedPins} from '../../scenarios/lz-ppm/private-retained-continuation-contract.mjs';
import {privateAccount} from '../../scenarios/lz-ppm/private-report-witness-contract.mjs';
const dir='evidence/lz-campaign/private-staged-report-owner-20260906',jp=dir+'/private-staged-report-owner-live/attempt-001/tests-artifacts/scenarios-lz-ppm-campaign--bee9c-eanup-unchanged-shared-Jira-chromium/private-report-witness.json',bytes=fs.readFileSync(jp),terminal=fs.readFileSync(dir+'/terminal-receipt.json'),j=admitRetainedBytes(bytes,terminal);
function fresh(){return{principal:privateAccount,registry:[...originalPlans,retainedPins.sourcePlanId,retainedPins.privatePlanId],source:structuredClone(j.source),snapshot:structuredClone(j.snapshot),planRead:{success:true,plan:structuredClone(j.owner.plan)},modelRead:structuredClone(j.owner.modelRead),settings:structuredClone(j.settings),standing:structuredClone(j.events.find(e=>e.stage==='private-hook'&&e.value.query.what==='plan'&&e.value.query.planId===originalPlans[0]).value.result),issueFirst:structuredClone(j.events.find(e=>e.stage==='shared-issue-get-only').value),issueSecond:structuredClone(j.events.find(e=>e.stage==='shared-issue-get-only').value),drafts:Object.fromEntries([...originalPlans,retainedPins.sourcePlanId,retainedPins.privatePlanId].map(id=>[id,{draft:{success:true,draft:null},active:{success:true,drafts:{}}}]))};}
test('exact failed journal/terminal and full fresh guards admit only retained41 owner',()=>{assert.equal(retainedPhase(undefined),false);assert.equal(retainedPhase(''),false);assert.throws(()=>retainedPhase('owner'));assert.equal(retainedPhase('reopen-cleanup'),true);assert.equal(verifyRetainedFresh(j,fresh()).planRead.plan.id,retainedPins.privatePlanId);assert.throws(()=>admitRetainedBytes(Buffer.concat([bytes,Buffer.from(' ')]),terminal));assert.throws(()=>admitRetainedBytes(bytes,Buffer.from('{}')));});
test('changed or foreign source/snapshot/model/generation/owner/job receipt refuses',()=>{for(const mutate of [x=>x.source.issues[0].duration=100,x=>x.snapshot.hash='bad',x=>x.owner.plan.createdBy='foreign',x=>x.owner.plan.simulationGeneration='foreign',x=>x.owner.modelRead.model.issues[0].duration=10,x=>x.finalJob.checkpoint=42,x=>x.finalJob.cleanupDone=false,x=>x.report.id='foreign',x=>x.settings.version=69]){const value=structuredClone(j);mutate(value);assert.throws(()=>validateRetainedState(value));}});
test('every fresh equality guard is required and changed principal/settings/Jira/source/drafts/registry refuses',()=>{for(const key of Object.keys(fresh())){const value=fresh();delete value[key];assert.throws(()=>verifyRetainedFresh(j,value),key);}for(const mutate of [x=>x.principal='foreign',x=>x.registry.pop(),x=>x.registry.push('foreign'),x=>x.source.meta.version++,x=>x.snapshot.issues[0].duration=4,x=>x.planRead.plan.simulationGeneration='other',x=>x.modelRead.model.issues[0].duration=4,x=>x.settings.version++,x=>x.standing.issues[0].duration=100,x=>x.issueSecond.fields.summary='changed',x=>x.drafts[retainedPins.privatePlanId].draft.draft={changes:{}}]){const value=fresh();mutate(value);assert.throws(()=>verifyRetainedFresh(j,value));}});
test('cleanup remains unarmed until both full HTML exports and exact report/pages/job are proved',()=>{const value={fresh:fresh(),owner:j.owner,summary:j.report,job:j.finalJob,pages:j.expected.pages,html:j.expected.html,reopenedHtml:j.expected.html};assert.equal(requireCleanupAuthority(j,value),true);for(const key of ['fresh','owner','summary','job','pages','html','reopenedHtml']){const next=structuredClone(value);delete next[key];assert.throws(()=>requireCleanupAuthority(j,next),key);}const changed=structuredClone(value);changed.pages[0].rows[0].duration=8;assert.throws(()=>requireCleanupAuthority(j,changed));});
