import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const source=fs.readFileSync('scenarios/lz-ppm/campaign-private-retained-continuation.spec.ts','utf8'),ast=ts.createSourceFile('actual.ts',source,ts.ScriptTarget.Latest,true);
function actual(name,args){let found;function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)===name)found='const '+n.getText(ast)+';';ts.forEachChild(n,visit);}visit(ast);assert(found);return new Function(...args,ts.transpileModule(found,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText+';return '+name+';');}
const expect=v=>({toBe:x=>assert.equal(v,x),toEqual:x=>assert.deepEqual(v,x)}),pins={sourcePlanId:'plan-test-exact'};
function session(fault){let poison=fault==='already'?Error('unknown response'):null;return {checked(){if(poison)throw poison;},async drain(){if(fault==='pending')poison=Error('late unknown');if(poison)throw poison;},wait(){return {promise:Promise.resolve({success:true}),dispose(){}};}};}
test('actual cleanup fence requires full output admission and exact owner before any mutation dispatch',async()=>{for(const state of ['unarmed','foreign','already','pending','healthy']){const owner={id:'exact'},candidate=state==='foreign'?{id:'foreign'}:owner;const fence=actual('mutationFence',['expect','cleanupArmed','owner','pinned','session'])(expect,state!=='unarmed',candidate,{owner},session(state));if(state==='healthy')await fence();else await assert.rejects(fence());}});
test('actual fixture hook permits only exact retained source deletion and never creation or foreign writes',async()=>{for(const what of ['createFixture','unknown','clearDrafts','deleteFixture'])for(const foreign of [true,false]){const calls=[],hook=actual('hook',['expect','retainedPins','mutationFence','getTestState','record'])(expect,pins,async()=>{},async(_app,q)=>{calls.push(q);return{};},()=>{});const q={what,planId:foreign?'foreign':pins.sourcePlanId};if(['clearDrafts','deleteFixture'].includes(what)&&!foreign){await hook(q);assert.equal(calls.length,1);}else{await assert.rejects(hook(q));assert.equal(calls.length,0);}}});
test('actual hook and delete UI action cannot cross an uncertain observation fence',async()=>{for(const fault of ['already','pending']){const s=session(fault),fence=async()=>{s.checked();await s.drain();s.checked();};let calls=0;const hook=actual('hook',['expect','retainedPins','mutationFence','getTestState','record'])(expect,pins,fence,async()=>{calls++;},()=>{});await assert.rejects(hook({what:'deleteFixture',planId:pins.sourcePlanId}));const perform=actual('performDelete',['mutationFence','session','retainedPins','expect'])(fence,s,{privatePlanId:'sim-exact'},expect);await assert.rejects(perform(async()=>{calls++;}));assert.equal(calls,0);}});
test('actual continuation never calls fork/capture/advance and every Page screenshot has explicit body subject',()=>{const calls=[];function visit(n){if(ts.isCallExpression(n))calls.push(n);ts.forEachChild(n,visit);}visit(ast);assert(!calls.some(n=>/^session\.(fork|capture)$/.test(n.expression.getText(ast))));assert(!calls.some(n=>n.arguments.some(a=>ts.isStringLiteral(a)&&['forkSimulationPlan','captureSponsorReport','advanceSponsorReportCapture','createFixture'].includes(a.text))));const shots=calls.filter(n=>n.expression.getText(ast)==='settledScreenshot');assert.equal(shots.length,1);assert.match(shots[0].arguments[1].getText(ast),/subject:documentPage\.locator\('body'\)/);});
