import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './session-fixture.mjs';
test('actual retained admission binds fresh private generation and current own document without a source Create transition',async()=>{
 const f=await fixture();f.session.retainedCandidate(f.inputs);await f.session.stop();const owner=await f.session.admitRetained(f.inputs,f.openRetained);assert.equal(owner.planId,f.f.ack.plan.id);assert.equal(f.records.filter(r=>r.stage==='private-retained-owner-promoted').length,1);assert.equal(f.records.filter(r=>r.stage==='owned-departure-leave-observed').length,0);await f.session.stop();assert.equal(f.records.filter(r=>r.stage==='owned-departure-leave-observed').length,1);await f.session.dispose();
});
test('retained mode forbids new fork and capture before any action',async()=>{const f=await fixture();let actions=0;await assert.rejects(f.session.fork(()=>{actions++;},{},async()=>({})),/cannot fork/);assert.throws(()=>f.session.capture(f.f.ack.plan.id,()=>{}),/cannot capture/);assert.equal(actions,0);await f.session.dispose();});
test('retained candidate is readonly and mutation cannot dispatch before private promotion',async()=>{const f=await fixture();f.session.retainedCandidate(f.inputs);await assert.rejects(f.session.invoke('deleteSponsorReport',{planId:f.f.ack.plan.id,reportId:'known'},true),/not admitted/);assert.equal(f.posts.length,0);assert.equal(f.session.owner().kind,'source');await f.session.dispose();});
test('foreign generation, missing candidate and changed fresh model refuse retained owner without mutation',async()=>{
 for(const kind of ['foreign','missing','changed']){const f=await fixture();if(kind!=='missing')f.session.retainedCandidate(f.inputs);const input=structuredClone(f.inputs);if(kind==='foreign')input.ack.plan.simulationGeneration='foreign';if(kind==='changed')input.modelRead.model.issues[0].duration=100;let opens=0;await assert.rejects(f.session.admitRetained(input,async()=>{opens++;}),/uncertain/);assert.equal(opens,0);assert.equal(f.session.owner().kind,'source');assert.equal(f.posts.length,0);await assert.rejects(f.session.dispose());}
});
test('wrong mount, wrong private principal and stale request document poison retained promotion',async()=>{
 for(const fault of ['private-mount','private-foreign-principal','document-replaced']){const f=await fixture({fault});f.session.retainedCandidate(f.inputs);await assert.rejects(f.session.admitRetained(f.inputs,f.openRetained),/uncertain/);assert.equal(f.session.owner().kind,'source');assert.equal(f.posts.length,0);await assert.rejects(f.session.stop());await assert.rejects(f.session.dispose());}
});
test('missing current beat and existing mounted source cannot satisfy retained admission',async()=>{
 for(const kind of ['missing-beat','source-mounted']){const f=await fixture();f.session.retainedCandidate(f.inputs);if(kind==='source-mounted'){f.mount(f.f.source.meta.name,f.f.source.meta.id);await f.turn();await f.session.drain();}await assert.rejects(f.session.admitRetained(f.inputs,async()=>{}),/uncertain/);assert.equal(f.posts.length,0);await assert.rejects(f.session.dispose());}
});
test('unknown UI result drains before retained cleanup dispatch and keeps the acknowledged owner',async()=>{const f=await fixture();f.session.retainedCandidate(f.inputs);await f.session.admitRetained(f.inputs,f.openRetained);f.emit('getPlan',f.f.ack.plan.id,{}, {failed:true});await assert.rejects(f.session.invoke('deleteSponsorReport',{planId:f.f.ack.plan.id,reportId:'known'},true));assert.equal(f.posts.length,0);assert.equal(f.session.owner().planId,f.f.ack.plan.id);await assert.rejects(f.session.dispose());});
