import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import {EventEmitter} from 'node:events';
import {actualPrivateFixture,app} from '../private-report-witness/actual-fixture.mjs';
import {departOwnedPlan,armPresenceLeave} from '../../scenarios/lz-ppm/owned-plan-departure.mjs';
import {createReportDocumentIdentity} from '../../scenarios/lz-ppm/report-document-identity.mjs';
import {createReportCaptureObserver} from '../../scenarios/lz-ppm/report-capture-observer.mjs';
import {serializeForgeResponse} from '../../scenarios/lz-ppm/forge-response-record.mjs';
import {admitPrivateSource,admitPrivateFork,admitPrivateForkIdentity,privateAccount} from '../../scenarios/lz-ppm/private-report-witness-contract.mjs';
const sessionSource=fs.readFileSync('scenarios/lz-ppm/private-report-witness-session.ts','utf8');
const compiled=ts.transpileModule(sessionSource.replace(/^import .*;\n/gm,'').replace('export function','function'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const expect=v=>({toHaveCount:async n=>assert.equal(await v.count(),n),toBeVisible:async()=>assert(await v.isVisible())});
const make=new Function('assert','expect','getTarget','callEnvelope','replayHeaders','serializeForgeResponse','createReportCaptureObserver','createReportDocumentIdentity','departOwnedPlan','armPresenceLeave','admitPrivateSource','admitPrivateFork','admitPrivateForkIdentity','privateAccount',compiled+';return privateWitnessSession;');
const usePresence=fs.readFileSync(app+'/static/ppm-ui/src/hooks/usePresence.js','utf8').replace(/^import .*;\n/gm,'').replace('export function','function');
const eventTarget=()=>({addEventListener(){},removeEventListener(){}});
export async function fixture({fault=null}={}){
 const f=await actualPrivateFixture(),page=new EventEmitter(),records=[],posts=[];let visible=null,document={},cleanup=()=>{},oldLeave=null,clock=Date.now(),url='https://test.atlassian.net/plugins/servlet/ac';
 const locator=(type,value)=>({async count(){return type==='back'?(visible?1:0):type==='banner'?(visible===f.name?1:0):type==='capacity'?0:value==='LZPT Scenarios'?visible?0:1:value===visible?1:0;},async isVisible(){return !!await this.count();},first(){return this;},async click(){assert.equal(type,'back');cleanup();visible=null;await turn();},getByRole(){return locator('none','');}});
 const frame={url:()=> 'https://test.cdn.prod.atlassian-dev.net/app/env/build/ppm-ui/index.html',locator:q=>locator(q.includes('Back to plans')?'back':q.includes('simulation-plan-banner')?'banner':'capacity',''),getByText:v=>locator('text',v),evaluateHandle:async()=>{const identity=document;return {evaluate:async()=>identity===document,dispose:async()=>{}};},frameElement:async()=>({getAttribute:async()=> 'hosted-resources-iframe',dispose:async()=>{}})};
 page.frames=()=>url==='about:blank'?[]:[frame];page.mainFrame=()=>({});page.url=()=>url;page.goto=async next=>{if(visible)throw Error('Unloading an active plan is forbidden');url=next;records.push({stage:'actual-blank'});};page.request={post:async()=>{posts.push('post');throw Error('No site call in local controls');}};
 const token=()=> 'eyJlocal.'+Buffer.from(JSON.stringify({exp:fault==='expired-wire'?1:Math.floor(Date.now()/1000)+900})).toString('base64url')+'.signature';
 function emit(key,planId,body,{stale=false,failed=false,payload={}}={}){const data={variables:{input:{extensionId:'ari:cloud:ecosystem::extension/app/env/static/ppm-dashboard',payload:{contextToken:token(),call:{functionKey:key,payload:{planId,...payload}}}}}},req={isNavigationRequest:()=>false,postDataBuffer:()=>Buffer.from(JSON.stringify(data)),url:()=> 'https://test.atlassian.net/gateway/api/graphql',allHeaders:async()=>({authorization:'Bearer opaque-private-secret'}),response:async()=>response};const response={request:()=>req,status:()=>200,finished:async()=>null,text:async()=>JSON.stringify({data:{invokeExtension:{success:true,errors:null,response:{body},contextToken:{jwt:token(),expiresAt:'future'}}}})};if(stale&&oldLeave){page.emit('response',oldLeave.response);page.emit('requestfinished',oldLeave.req);return;}page.emit('request',req);if(failed)page.emit('requestfailed',req);else{page.emit('response',response);page.emit('requestfinished',req);}if(key==='presenceLeave')oldLeave={req,response};}
 const turn=()=>new Promise(r=>setImmediate(r));
 function mount(name,planId){visible=name;url='https://test.atlassian.net/plugins/servlet/ac';const effects=[];const invoke=(key,payload)=>{if(key==='presenceLeave'&&fault==='missing-leave')return Promise.resolve({success:true});const id=key==='presenceLeave'&&fault==='wrong-owner'?'sim-foreign':payload.planId;return f.presenceCall(key,payload,key==='presenceBeat'&&(fault==='foreign-principal'||fault==='private-foreign-principal'&&planId===f.ack.plan.id)?'foreign':privateAccount).then(body=>{emit(key,id,body,{failed:key==='presenceLeave'&&fault==='failed-leave',stale:key==='presenceLeave'&&fault==='stale-leave'});if(key==='presenceLeave'&&fault==='duplicate-leave')emit(key,id,body);return body;});};
  const hook=new Function('useEffect','useRef','useState','useCallback','callResolver','window','document','setInterval','clearInterval',usePresence+';return usePresence;')((fn)=>effects.push(fn()),v=>({current:v}),v=>[v,()=>{}],fn=>fn,invoke,eventTarget(),eventTarget(),()=>1,()=>{});hook(planId,'planning',true);cleanup=()=>{for(const fn of effects)if(typeof fn==='function')fn();};}
 const construct=make(assert,expect,()=>({appId:'app',envId:'env'}),req=>JSON.parse(req.postDataBuffer()),x=>x,serializeForgeResponse,createReportCaptureObserver,createReportDocumentIdentity,departOwnedPlan,armPresenceLeave,admitPrivateSource,admitPrivateFork,admitPrivateForkIdentity,privateAccount);
 const session=construct(page,{record:(stage,value)=>records.push({stage,value}),timeoutMs:60,retainedOnly:true});session.source(f.source,f.source.meta.name);emit('getCapacitySettings',null,{success:true,version:68,settings:{}});await turn();await session.drain();
 const transition=()=>session.fork(async()=>{cleanup();mount(fault==='private-mount'?'Wrong private mount':f.name,f.ack.plan.id);if(fault==='document-replaced'){await turn();document={};}await turn();return f.ack;},{source:f.source,snapshot:f.snapshot,name:f.name},async()=>({planRead:f.planRead,modelRead:f.modelRead}));
 const inputs={ack:f.ack,source:f.source,snapshot:f.snapshot,name:f.name,planRead:f.planRead,modelRead:f.modelRead};
 const openRetained=async()=>{mount(fault==='private-mount'?'Wrong private mount':f.name,f.ack.plan.id);await turn();if(fault==='document-replaced')document={};};
 return {f,inputs,session,records,posts,transition,emit,turn,openRetained,mount,replaceDocument:()=>document={}};
}
