import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';
import {loadUatReuse,admitUatReuse,assertOwnedPlan,reusePins} from '../../scenarios/lz-ppm/retained-uat-reuse.mjs';
const root=path.resolve('.'),original=path.join(root,'scratch/lz-retained-uat-20260906/ownership.json'),prior=JSON.parse(fs.readFileSync(original)),terminal=path.join(root,'evidence/lz-campaign/retained-uat-acceptance-20260906/terminal-receipt.json');
const input={phase:'reuse-owned',journalPath:original,terminalPath:terminal};
const copy=x=>structuredClone(x),fields=['customfield_11148','customfield_11149'];
function plan(kind){return {meta:{id:prior.plans[kind].id,name:prior.plans[kind].name,createdBy:'harness',createdByName:'harness',calendarKey:'standard',holidayYears:[2026,2027],milestones:[],protectionEnabled:false,members:[],defaultAccess:'none',issueCount:4,sources:[{id:'src-0',type:'jql',label:'harness',query:prior.jql,boardId:null,projectKey:null}],assets:{fieldIds:fields},status:'indexed',version:3},issues:prior.admittedJira.map(i=>({id:i.id,key:i.key,summary:i.fields.summary,startDate:i.fields.customfield_10015,dueDate:i.fields.duedate,duration:i.fields.customfield_10180,buffer:i.fields.customfield_10181.value,parentKey:i.fields.parent?.key||null,predecessors:i.role==='B'?[prior.issues.A.key]:[],successors:i.role==='A'?[prior.issues.B.key]:[],assets:Object.fromEntries(fields.map(k=>[k,{state:(i.fields[k]||[]).length?'present':'empty',objects:(i.fields[k]||[]).map(v=>({workspaceId:v.workspaceId,objectId:v.objectId}))}]))}))};}
function fixture(mutate=()=>{}){const plans={main:plan('main'),mirror:plan('mirror')},calls=[],journal={},f={journal,persist(){},read:async()=>{calls.push('jira-read');return copy(prior.admittedJira);}},roster=[...prior.registry,reusePins.main,reusePins.mirror].map(id=>({id}));
 const hook=async(_,q)=>{calls.push(q.what);if(q.what==='plans')return {plans:copy(roster)};if(q.what==='fieldConfig')return{fields:{startDate:'customfield_10015',dueDate:'duedate',duration:'customfield_10180'}};if(q.what==='plan')return copy(q.planId===reusePins.main?plans.main:q.planId===reusePins.mirror?plans.mirror:{issues:prior.standingSchedule});throw Error('No mutation allowed');};
 const get=async uri=>{calls.push(uri);assert.equal(uri,'/rest/api/3/myself');return {...prior.person,active:true};};
 const invoke=async(name,payload)=>{calls.push(name);const kind=payload.planId===reusePins.main?'main':'mirror';let value;
 if(name==='checkUserRole')value={success:true,role:'admin',isAdmin:true,accountId:reusePins.account};else if(name==='getCapacitySettings')value={success:true,version:68,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}};else if(name==='getPlan')value={success:true,plan:plans[kind].meta};else if(name==='getDraft')value={success:true,draft:null};else if(name==='getActiveDrafts')value={success:true,drafts:{}};else if(name==='listSnapshots'||name==='listSponsorReports')value={success:true,entries:[],nextCursor:null};else if(name==='getTargets')value={success:true,targets:[],scopeOptions:[],version:3};else if(name==='getBaseline')value={baseline:null};else throw Error('No mutation allowed');value=copy(value);mutate(name,value);return value;};
 return {f,calls,plans,roster,hook,get,invoke,scheduleFields:x=>x};}
test('actual failed receipts admit exact IDs and a distinct ledger; originals unchanged',()=>{const before=fs.readFileSync(original);const r=loadUatReuse(input,root);assert.equal(r.prior.state,'retained-after-failure');assert.equal(r.ledgerPath,path.join(root,'scratch/lz-retained-uat-reuse-20260906/ownership.json'));assert.deepEqual(fs.readFileSync(original),before);});
for(const bad of [{...input,phase:'new'}, {...input,journalPath:'relative'}, {...input,extra:true}])test('unknown or incomplete replay intent refuses '+JSON.stringify(bad.phase),()=>assert.throws(()=>loadUatReuse(bad,root)));
test('changed journal or terminal bytes refuse, not normalized into acceptance',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'uat-pin-'));try{for(const k of ['journalPath','terminalPath']){const p=path.join(dir,k);fs.writeFileSync(p,fs.readFileSync(input[k],'utf8')+' ');assert.throws(()=>loadUatReuse({...input,[k]:p},root));}}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('full exact current source, actor, settings and both clean plan contexts admit with only reads',async()=>{const x=fixture();await admitUatReuse(x.f,loadUatReuse(input,root),x);await x.f.admitCurrentUser(x.invoke);assert.equal(x.f.journal.reuseAdmissionComplete,true);assert.equal(x.f.journal.state,'admitted');assert.deepEqual(x.f.journal.registry,prior.registry);assert.equal(Object.keys(x.f.journal.reuseReadiness).length,2);assert(!x.calls.some(n=>/create|delete|save|update|refresh|capture|advance/i.test(n)));});
for(const [name,change]of [
 ['foreign actor', (n,v)=>{if(n==='checkUserRole')v.accountId='foreign';}],
 ['changed settings',(n,v)=>{if(n==='getCapacitySettings')v.version=69;}],
 ['draft',(n,v)=>{if(n==='getDraft')v.draft={changes:[]};}],
 ['foreign draft',(n,v)=>{if(n==='getActiveDrafts')v.drafts.foreign={};}],
 ['retained report',(n,v)=>{if(n==='listSponsorReports')v.entries=[{id:'old'}];}],
 ['history next page',(n,v)=>{if(n==='listSnapshots')v.nextCursor='more';}],
 ['target',(n,v)=>{if(n==='getTargets')v.targets=[{id:'old'}];}],
 ['baseline',(n,v)=>{if(n==='getBaseline')v.baseline={snapshotId:'old'};}],
 ['unknown response',(n,v)=>{if(n==='getPlan')v.success=false;}],
])test('current-user admission refuses '+name+' before business body',async()=>{const x=fixture(change);await admitUatReuse(x.f,loadUatReuse(input,root),x);await assert.rejects(x.f.admitCurrentUser(x.invoke));assert.notEqual(x.f.journal.reuseAdmissionComplete,true);});
for(const [name,change]of [['sourceJQL',s=>s.meta.sources[0].query='project=OTHER'],['foreign plan',s=>s.meta.id='other'],['missing row',s=>s.issues.pop()],['buffer drift',s=>s.issues[1].buffer='Yes'],['asset identity drift',s=>s.issues[1].assets[fields[0]].objects[0].objectId='999'],['dirty target',s=>s.meta.milestones.push({id:'old'})]])test('complete source refuses '+name,()=>{const state=plan('main');change(state);assert.throws(()=>assertOwnedPlan(state,prior,'main'));});
test('all downstream UAT body, math oracles and cleanup/final guards remain byte-exact',()=>{const file='scenarios/lz-ppm/journey-campaign-retained-uat.spec.ts',source=fs.readFileSync(file,'utf8'),old=execFileSync('git',['show','3b771f8:'+file],{encoding:'utf8'}),rest=s=>s.slice(s.indexOf("  stage('scoped target and saved alternatives')"));assert.equal(rest(source),rest(old));assert.match(source,/fullPage:false,subject:/);assert.match(source,/toContainText\('Object 411 \(unavailable\)'\)/);assert.match(source,/toContainText\('411 · label unavailable'\)/);});

test('actual fixture reuse branches before every create and permanent wx blocks another call',async()=>{
 const {createRequire}=await import('node:module'),require=createRequire(import.meta.url),ts=require('typescript'),vm=await import('node:vm'),{pathToFileURL}=await import('node:url'),{expect}=require('@playwright/test'),api=await import('../../scenarios/lz-ppm/retained-uat-reuse.mjs');
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'uat-actual-reuse-')),repo=path.join(tmp,'harness'),out=path.join(tmp,'out'),app=path.join(tmp,'lz-ppm-forge/docs/campaign-2026-09');fs.mkdirSync(app,{recursive:true});fs.copyFileSync('/Users/mihaiperdum/Projects/lz-ppm-forge/docs/campaign-2026-09/retained-uat-oracle.json',path.join(app,'retained-uat-oracle.json'));fs.mkdirSync(path.join(repo,'scratch/lz-retained-uat-20260906'),{recursive:true});fs.copyFileSync(original,path.join(repo,'scratch/lz-retained-uat-20260906/ownership.json'));
 const x=fixture(),filename=path.join(repo,'scenarios/lz-ppm/retained-uat-fixture.ts'),source=fs.readFileSync('scenarios/lz-ppm/retained-uat-fixture.ts','utf8').replaceAll('import.meta.url',JSON.stringify(pathToFileURL(filename).href)),module={exports:{}},get=async uri=>{if(uri==='/rest/api/3/myself')return x.get(uri);x.calls.push(uri);const hit=prior.admittedJira.find(i=>uri.includes('/issue/'+i.id+'?')||uri.includes('/issue/'+i.key+'?'));assert(hit);return copy(hit);};
 const fail=()=>{throw Error('Forbidden mutator reached');},boundary={'../../fixtures/forge':{expect},'../../testhook/client':{getTestState:x.hook},'../../data/jira.mjs':{BASE:'https://wolfaenpak.atlassian.net',get,post:fail,put:fail,request:fail},'../../data/env.mjs':{requireEnv:fail},'./forecast-fixture':{LZPT_PLAN:'plan-msq9dg8l-gz6mz1',scheduleFields:x=>x},'./retained-uat-reuse.mjs':{...api,admitUatReuse:async(f,r,d)=>{const read=f.read;f.read=async()=>JSON.parse(JSON.stringify(await read()));return api.admitUatReuse(f,r,d);}}};
 try{vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{module,exports:module.exports,require:name=>boundary[name]||require(name),Buffer,console,Date,URL,AggregateError,process:{env:{}},fetch:fail});const info={outputDir:out,outputPath:name=>path.join(out,name)},f=await module.exports.createRetainedUat(info,{retainExperiments:true,reuse:input});await f.admitCurrentUser(x.invoke);assert.equal(f.journal.reuseAdmissionComplete,true);assert.deepEqual(JSON.parse(JSON.stringify(f.keys)),{E:'WFH-2997',A:'WFH-2998',B:'WFH-2999',L:'WFH-3000'});const calls=x.calls.length;await assert.rejects(module.exports.createRetainedUat(info,{retainExperiments:true,reuse:input}),/EEXIST/);assert.equal(x.calls.length,calls);assert.equal(fs.readFileSync(path.join(repo,'scratch/lz-retained-uat-20260906/ownership.json'),'utf8'),fs.readFileSync(original,'utf8'));}
 finally{fs.rmSync(tmp,{recursive:true,force:true});}
});
