import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {admitPacedResume,failedSha,recoveredSha} from '../../scenarios/lz-ppm/seventeenth-paced-resume-contract.mjs';
import {admitAggregateResume,continueAggregateReport,pacedFailureSha} from '../../scenarios/lz-ppm/seventeenth-aggregate-resume-contract.mjs';
const load=(p,hash)=>{const bytes=fs.readFileSync(p);if(hash)assert.equal(createHash('sha256').update(bytes).digest('hex'),hash);return JSON.parse(bytes);};
const source=load('evidence/lz-campaign/seventeenth-source-return-readonly-20260906/artifacts/scenarios-lz-ppm-campaign--755d0-eserve-exact-retained-state-chromium/seventeenth-source.json','7226d8e907632eaf8c2d464b50c3a48ba701bd639f9a4ac0af92bf9078eecba5');
const failed=load('evidence/lz-campaign/seventeenth-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--f695f-rt-and-HTML-without-cleanup-chromium/seventeenth-forecast-resume.json',failedSha);
const recovery=load('evidence/lz-campaign/seventeenth-quota-readonly-admission-20260906/receipt.json',recoveredSha);
const paced=load('evidence/lz-campaign/seventeenth-paced-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--6c70d-rt-and-HTML-without-cleanup-chromium/seventeenth-paced-resume.json',pacedFailureSha);
const previous=()=>admitPacedResume(failed,failedSha,recovery,recoveredSha,{job:source.finalJob,probe:source.finalProbe});
const admit=(value=paced,digest=pacedFailureSha)=>admitAggregateResume(value,digest,previous());
const stages=load('tests/seventeenth-paced-resume/advance-reservations.json').remainingAfter126.filter(r=>r.from>=127);
test('actual127 terminal plus both realattempts and126→127→127 physicalsequence admits exact183private',()=>{const x=admit();assert.equal(x.job.checkpoint,127);assert.equal(x.probe.privateArtifacts.length,183);assert.deepEqual(x.job.forecastRuns,{completed:40,total:40});assert.equal(stages.length,56);});
test('wrong latestdigest, absent failedrequest, claimedpass or failedfinalaudit refuses',()=>{assert.throws(()=>admit(paced,'0'.repeat(64)));for(const edit of [x=>x.events=x.events.filter(e=>!(e.stage==='advanceSponsorReportCapture'&&e.value.body.success===false)),x=>x.completed=true,x=>x.sourceAndPreferencesPreserved=false,x=>x.events.push({stage:'independent-audit-error',value:'bad'})]){const x=structuredClone(paced);edit(x);assert.throws(()=>admit(x));}});
test('incorrect request127 or changed explicitrefusal and any changed savedstatus refuses',()=>{for(const edit of [x=>x.events.filter(e=>e.stage==='actual-advance-dispatch')[1].value.payload.expectedCheckpoint=126,x=>x.events.filter(e=>e.stage==='advanceSponsorReportCapture')[1].value.body.error='other',x=>x.events.filter(e=>e.stage==='getSponsorReportCapture').at(-1).value.body.job.checkpoint=128]){const x=structuredClone(paced);edit(x);assert.throws(()=>admit(x));}});
test('originalhash loss, finalmanifest mismatch, publication or changedprefs cannot admit',()=>{for(const edit of [x=>x.probes[1].privateArtifacts.pop(),x=>x.probes[2].privateArtifacts[0].actualHash='0'.repeat(64),x=>x.probes[2].publicArtifacts.push({}),x=>x.events.filter(e=>e.stage==='getCapacitySettings').at(-1).value.body.version=66]){const x=structuredClone(paced);edit(x);assert.throws(()=>admit(x));}});
async function simulate(fault){const admitted=admit();let actual=admitted.job,calls=0,physical=0;let result,error;try{result=await continueAggregateReport({initial:actual,progress:admitted.progress,advance:async payload=>{assert.equal(payload.expectedCheckpoint,actual.checkpoint);calls++;if(fault==='unknown')throw new Error('unknown');const row=stages[calls-1];actual={...actual,checkpoint:row.to,completedUnits:row.to,totalUnits:183,state:row.to===183?'complete':'active',stageLabel:stages[calls]?.priorStage??'Report ready'};if(fault==='premature')actual={...actual,state:'complete'};if(fault==='counter')actual.forecastRuns={completed:39,total:40};return {httpStatus:200,outerSuccess:true,body:{success:fault!=='refused',job:actual}};},status:async()=>fault==='status'?{...actual,checkpoint:999}:actual,probe:async()=>{physical++;if(fault==='physical')throw new Error('physical');}});}catch(e){error=e;}return {result,error,calls,physical};}
test('56 remaining exact ack/status/probe steps publish183 with same40 savedruns',async()=>{const x=await simulate();assert.ifError(x.error);assert.equal(x.result.checkpoint,183);assert.equal(x.calls,56);assert.equal(x.physical,56);assert.deepEqual(x.result.forecastRuns,{completed:40,total:40});});
test('unknown/refusal/status/physical/run-counter failures stop afterone attempt without retry',async()=>{for(const fault of ['unknown','refused','status','physical','counter']){const x=await simulate(fault);assert.ok(x.error);assert.equal(x.calls,1);}});
test('premature publication cannot substitute for exact remaining checkpoint sequence',async()=>{const x=await simulate('premature');assert.ok(x.error);assert.equal(x.calls,1);});
