import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
import {admitPrivatePhase,admitPrivateSource,admitPrivateFork,verifyPrivateSnapshot,finishPrivateWitness,privateDeletedState,privateCleanupStep,privateReportOracle,privateHash} from '../../scenarios/lz-ppm/private-report-witness-contract.mjs';
import {actualPrivateFixture,app} from './actual-fixture.mjs';
import {pathToFileURL} from 'node:url';
const clone=structuredClone;
test('actual current fork, snapshot store and generation roundtrip satisfy exact owner provenance',async()=>{const f=await actualPrivateFixture();admitPrivateSource(f.source,f.source.meta.name);verifyPrivateSnapshot(f.snapshot,f.source,f.calendar,'Source snapshot');const owner=admitPrivateFork(f);assert.equal(owner.planId,f.ack.plan.id);assert.deepEqual(owner.modelRead.model,owner.modelRead.scopeBasis);});
test('same actual fork refuses each foreign identity, permission, stale generation and data substitution',async()=>{const f=await actualPrivateFixture();for(const change of [x=>x.ack.plan.createdBy='foreign',x=>x.ack.plan.id='sim-wrong',x=>x.ack.plan.name='foreign',x=>x.ack.plan.defaultAccess='viewer',x=>x.ack.plan.sources=[{query:'other'}],x=>x.ack.plan.simulationProvenance.sourcePlanId='foreign',x=>x.ack.plan.simulationProvenance.snapshotId='foreign',x=>x.ack.plan.simulationProvenance.snapshotHash='f'.repeat(64),x=>x.modelRead.version++,x=>x.modelRead.model.id='old',x=>x.modelRead.scopeBasis.issues[0].duration++,x=>x.planRead.plan.version++]){const {runtime,values,presenceCall,...serializable}=f;const bad=clone(serializable);change(bad);assert.throws(()=>admitPrivateFork(bad));}});
test('finalization never deletes on unknown outcome and executes every independent audit after failed leave',async()=>{const journal={owned:{sourcePlanId:'plan-test-x',privatePlanId:'sim-known'},completed:false},calls=[];await assert.rejects(finishPrivateWitness({journal,persist(){},stop:async()=>{calls.push('stop');throw Error('unknown');},audits:[async()=>{calls.push('prefs');throw Error('prefs');},async()=>calls.push('source'),async()=>calls.push('jira')]}),e=>e instanceof AggregateError&&e.errors.length===2);assert.deepEqual(calls,['stop','prefs','source','jira']);assert.equal(journal.state,'recovery-required');assert.deepEqual(journal.owned,{sourcePlanId:'plan-test-x',privatePlanId:'sim-known'});});
test('explicit owner phase only, disabled discovery stays inert and unknown phases refuse',()=>{assert.equal(admitPrivatePhase(undefined),false);assert.equal(admitPrivatePhase(''),false);assert.equal(admitPrivatePhase('owner'),true);assert.throws(()=>admitPrivatePhase('other'));});
test('reviewed private cut and current witness preserve existing helper blobs without binding unrelated history',()=>{
 const base='b5a97100363a6f33783c2925554f2edb3a484610',cut='fc67d592ddbc26caa8ee2532e51296b6998acc62';
 for(const name of execFileSync('git',['diff','--name-only',base,cut],{encoding:'utf8'}).trim().split('\n').filter(Boolean))assert.match(name,/^(scenarios\/lz-ppm\/(campaign-private-staged-report\.spec\.ts|private-report-witness-(contract\.mjs|session\.ts))|tests\/private-report-witness\/)/);
 for(const name of ['campaign-private-staged-report.spec.ts','private-report-witness-contract.mjs','private-report-witness-session.ts']){const file='scenarios/lz-ppm/'+name,sourceCut=name==='private-report-witness-session.ts'?'d92e611b9efa16841701e02b7efaf8cd02f5af31':name==='campaign-private-staged-report.spec.ts'?'8106139':cut;assert.deepEqual(fs.readFileSync(file),execFileSync('git',['show',sourceCut+':'+file]),file+' must equal the reviewed private source');}
 // Inspect modifications/deletions of existing source, not unrelated newly added evidence/specs.
 const oldChanged=execFileSync('git',['diff','--name-only','--diff-filter=CDMRTUXB',base,'--','scenarios/lz-ppm','fixtures','forge','config','testhook','capture','data','playwright.config.ts','package.json','package-lock.json'],{encoding:'utf8'}).trim();assert.equal(oldChanged,'','Pre-existing witness helper/config source changed');
 const source=fs.readFileSync('scenarios/lz-ppm/campaign-private-staged-report.spec.ts','utf8');assert(!/reportCaptureState|cleanupOwnedReportCaptures|captureReport\(/.test(source));assert.match(source,/get\(`\/rest\/api\/3\/issue\/WFH-2820\?fields=/);assert(!/\b(?:post|put|del)\(/.test(source));assert.match(source,/retries:0/);
});

test('actual fork model runs through current registered staged handlers and agrees with whole frozen report/page/HTML oracle',async()=>{
 const f=await actualPrivateFixture(),owner=admitPrivateFork(f);const {stagedReportFixture}=await import(pathToFileURL(app+'/test/helpers/staged-report-fixture.mjs'));
 let stage;stage=await stagedReportFixture({planId:owner.planId,rows:clone(owner.modelRead.model.issues),providedAuth:async(id,account)=>({ok:id===owner.planId&&account===f.account,meta:clone(stage.meta)})});Object.assign(stage.meta,clone(owner.plan));Object.assign(stage.calendar,clone(owner.modelRead.model.calendar));stage.seed();
 const call=(name,payload)=>stage.call(name,payload,f.account),name='Private owner immutable report',startMs=Date.now();let result=await call('captureSponsorReport',{name,uncertainty:'medium',requestId:'private-local-complete',expectedVersion:1});
 for(let n=0;n<200&&result.success&&result.job.state==='active';n++)result=await call('advanceSponsorReportCapture',{jobId:result.job.id,expectedCheckpoint:result.job.checkpoint});assert.equal(result.success,true);assert.equal(result.job.state,'complete');const summary=result.report;
 for(let n=0;n<20&&!result.job.cleanupDone;n++)result=await call('cancelSponsorReportCapture',{jobId:result.job.id});assert.equal(result.job.cleanupDone,true);
 const opts={owner,job:result.job,summary,name,captureWindow:{startMs,endMs:Date.now()}},expected=privateReportOracle(opts);for(const page of expected.pages)assert.deepEqual((await call('getSponsorReportPage',{reportId:summary.id,section:page.section,page:page.page})).page,page);
 const {exporter}=await import(pathToFileURL(app+'/test/helpers/staged-report-fixture.mjs'));assert.equal(exporter.sponsorReportHtml(summary,expected.pages),expected.html);
 for(const mutate of [x=>x.summary.forecast.p80='2099-01-01',x=>x.summary.counts.timeline=0,x=>x.summary.mode='ordinary',x=>x.summary.consistency.basisHash='0'.repeat(64)]){const bad=clone(opts);mutate(bad);assert.throws(()=>privateReportOracle(bad));}
 assert.deepEqual(await call('deleteSponsorReport',{reportId:summary.id}),{success:true,deleted:true});const deletedState=await call('getSponsorReportCapture',{jobId:result.job.id});let cleaned=privateDeletedState(result.job,deletedState.job);assert.deepEqual(deletedState,{success:true,job:cleaned});for(let n=0;n<20&&!cleaned.cleanupDone;n++){const reply=await call('cancelSponsorReportCapture',{jobId:result.job.id});cleaned=privateCleanupStep(cleaned,reply.job);assert.deepEqual(reply,{success:true,job:cleaned});}assert.equal(cleaned.state,'cancelled');assert.equal(cleaned.cleanupDone,true);
 for(let n=0;n<2;n++){assert.deepEqual(await call('getSponsorReport',{reportId:summary.id}),{success:false,error:'This sponsor report was deleted or is unavailable'});assert.deepEqual(await call('getSponsorReportPage',{reportId:summary.id,section:'timeline',page:0}),{success:false,error:'This report is unavailable'});assert.deepEqual((await call('listSponsorReports',{})).entries,[]);}
});

test('delete acknowledgement binds a fresh cancelled status, then every cleanup acknowledges exactly one checkpoint',()=>{
 const complete={id:'job',requestId:'nonce',reportId:'report',name:'name',createdAt:'date',expiresAt:'later',checkpoint:10,state:'complete',cleanupDone:true},deleted={...complete,checkpoint:11,state:'cancelled',cleanupDone:false},next={...deleted,checkpoint:12};
 assert.deepEqual(privateDeletedState(complete,deleted),deleted);assert.deepEqual(privateCleanupStep(deleted,next),next);
 for(const change of [x=>x.id='other',x=>x.requestId='other',x=>x.reportId='other',x=>x.checkpoint=10,x=>x.checkpoint=12,x=>x.state='complete',x=>x.cleanupDone=true]){const bad=clone(deleted);change(bad);assert.throws(()=>privateDeletedState(complete,bad));}
 for(const change of [x=>x.id='other',x=>x.requestId='other',x=>x.reportId='other',x=>x.checkpoint=11,x=>x.checkpoint=13,x=>x.state='complete',x=>x.cleanupDone='true']){const bad=clone(next);change(bad);assert.throws(()=>privateCleanupStep(deleted,bad));}
 assert.throws(()=>privateCleanupStep(complete,next));assert.throws(()=>privateCleanupStep({...deleted,cleanupDone:true},next));
});

test('actual snapshot response excludes only its proven read marker from stored hash verification',async()=>{
 const f=await actualPrivateFixture();assert.equal(f.snapshot.assetsReadState,'requires-current-user-read');assert.equal(f.snapshot.hash,f.storedSnapshot.hash);const {assetsReadState,...stored}=f.snapshot;assert.deepEqual(stored,f.storedSnapshot);verifyPrivateSnapshot(f.snapshot,f.source,f.calendar,'Source snapshot');
 for(const change of [x=>delete x.assetsReadState,x=>x.assetsReadState='unrestricted',x=>x.unprovenEnrichment='ignored?',x=>x.issues[0].duration++,x=>x.name='changed']){const bad=clone(f.snapshot);change(bad);assert.throws(()=>verifyPrivateSnapshot(bad,f.source,f.calendar,'Source snapshot'));}
});
