import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {execFileSync} from 'node:child_process';
const source=process.env.LZ_PRIVATE_OLD_FENCE==='1'?execFileSync('git',['show','60ba8ac:scenarios/lz-ppm/campaign-private-staged-report.spec.ts'],{encoding:'utf8'}):fs.readFileSync('scenarios/lz-ppm/campaign-private-staged-report.spec.ts','utf8');
const ast=ts.createSourceFile('actual.ts',source,ts.ScriptTarget.Latest,true);
function actual(name,args){let found;function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)===name)found='const '+n.getText(ast)+';';ts.forEachChild(n,visit);}visit(ast);assert(found);const js=ts.transpileModule(found,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;return new Function(...args,js+';return '+name+';');}
const expect=v=>({toBe:x=>assert.equal(v,x)});
function session(fault){let poison=fault==='already'?Error('uncertain'):null;return {checked(){if(poison)throw poison;},async drain(){if(fault==='pending')poison=Error('late failed response');if(poison)throw poison;},wait(){this.checked();return {promise:Promise.resolve({success:true}),dispose(){}};}};}
test('compiled actual hook fences every fixture mutation for existing and newly drained observation failures',async()=>{for(const what of ['createFixture','clearDrafts','deleteFixture'])for(const fault of ['already','pending']){const writes=[],hook=actual('hook',['getTestState','record','session'])(async(_app,query)=>{writes.push(query);return {};},()=>{},session(fault));await assert.rejects(hook({what,planId:'owned'}));assert.deepEqual(writes,[]);}});
test('compiled actual hook preserves positive writes, independent read audits and rejects unknown actions',async()=>{for(const what of ['createFixture','clearDrafts','deleteFixture','plans','plan']){const calls=[],s=session(['plans','plan'].includes(what)?'already':null),hook=actual('hook',['getTestState','record','session'])(async(_app,query)=>{calls.push(query);return {ok:true};},()=>{},s);assert.deepEqual(await hook({what}),{ok:true});assert.deepEqual(calls,[{what}]);}let unknownDispatches=0;const hook=actual('hook',['getTestState','record','session'])(async()=>{unknownDispatches++;return {};},()=>{},session(null));await assert.rejects(hook({what:'unknown'}));assert.equal(unknownDispatches,0);});
test('compiled actual UI perform refuses poisoned or pending-failure actions and preserves healthy response semantics',async()=>{for(const fault of ['already','pending',null]){let actions=0;const perform=actual('perform',['session','expect'])(session(fault),expect),run=()=>perform('forkSimulationPlan','owned',async()=>{actions++;});if(fault)await assert.rejects(run());else assert.deepEqual(await run(),{success:true});assert.equal(actions,fault?0:1);}});
