import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import {EventEmitter} from 'node:events';
import {actualPrivateFixture,app} from './actual-fixture.mjs';
import {departOwnedPlan,armPresenceLeave} from '../../scenarios/lz-ppm/owned-plan-departure.mjs';
import {createReportDocumentIdentity} from '../../scenarios/lz-ppm/report-document-identity.mjs';
import {createReportCaptureObserver} from '../../scenarios/lz-ppm/report-capture-observer.mjs';
import {serializeForgeResponse} from '../../scenarios/lz-ppm/forge-response-record.mjs';
import {admitPrivateSource,admitPrivateFork,admitPrivateForkIdentity,privateAccount} from '../../scenarios/lz-ppm/private-report-witness-contract.mjs';
const sessionSource=fs.readFileSync('scenarios/lz-ppm/private-report-witness-session.ts','utf8');
const compiled=ts.transpileModule(sessionSource.replace(/^import .*;\n/gm,'').replace('export function','function'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const expect=v=>({toHaveCount:async n=>assert.equal(await v.count(),n),toBeVisible:async()=>assert(await v.isVisible())});
const make=new Function('assert','expect','getTarget','callEnvelope','replayHeaders','serializeForgeResponse','createReportCaptureObserver','createReportDocumentIdentity','departOwnedPlan','armPresenceLeave','admitPrivateSource','admitPrivateFork','admitPrivateForkIdentity','privateAccount',compiled+';return privateWitnessSession;');
const usePresence=fs.readFileSync(app+'/static/ppm-ui/src/hooks/usePresence.js','utf8').replace(/^import .*;\n/gm,'').replace('export function','function');
const eventTarget=()=>({addEventListener(){},removeEventListener(){}});
async function fixture({fault=null}={}){
 const f=await actualPrivateFixture(),page=new EventEmitter(),records=[],posts=[];let visible=null,document={},cleanup=()=>{},oldLeave=null,clock=Date.now(),url='https://test.atlassian.net/plugins/servlet/ac';
 const locator=(type,value)=>({async count(){return type==='back'?(visible?1:0):type==='banner'?(visible===f.name?1:0):type==='capacity'?0:value==='LZPT Scenarios'?visible?0:1:value===visible?1:0;},async isVisible(){return !!await this.count();},first(){return this;},async click(){assert.equal(type,'back');cleanup();visible=null;await turn();},getByRole(){return locator('none','');}});
 const frame={url:()=> 'https://test.cdn.prod.atlassian-dev.net/app/env/build/ppm-ui/index.html',locator:q=>locator(q.includes('Back to plans')?'back':q.includes('simulation-plan-banner')?'banner':'capacity',''),getByText:v=>locator('text',v),evaluateHandle:async()=>{const identity=document;return {evaluate:async()=>identity===document,dispose:async()=>{}};},frameElement:async()=>({getAttribute:async()=> 'hosted-resources-iframe',dispose:async()=>{}})};
 page.frames=()=>url==='about:blank'?[]:[frame];page.mainFrame=()=>({});page.url=()=>url;page.goto=async next=>{if(visible)throw Error('Unloading an active plan is forbidden');url=next;records.push({stage:'actual-blank'});};page.request={post:async()=>{posts.push('post');throw Error('No site call in local controls');}};
 const token=()=> 'eyJlocal.'+Buffer.from(JSON.stringify({exp:fault==='expired-wire'?1:Math.floor(Date.now()/1000)+900})).toString('base64url')+'.signature';
 function emit(key,planId,body,{stale=false,failed=false,payload={}}={}){const data={variables:{input:{extensionId:'ari:cloud:ecosystem::extension/app/env/static/ppm-dashboard',payload:{contextToken:token(),call:{functionKey:key,payload:{planId,...payload}}}}}},req={isNavigationRequest:()=>false,postDataBuffer:()=>Buffer.from(JSON.stringify(data)),url:()=> 'https://test.atlassian.net/gateway/api/graphql',allHeaders:async()=>({authorization:'Bearer opaque-private-secret'}),response:async()=>response};const response={request:()=>req,status:()=>200,finished:async()=>null,text:async()=>JSON.stringify({data:{invokeExtension:{success:true,errors:null,response:{body},contextToken:{jwt:token(),expiresAt:'future'}}}})};if(stale&&oldLeave){page.emit('response',oldLeave.response);page.emit('requestfinished',oldLeave.req);return;}page.emit('request',req);if(failed)page.emit('requestfailed',req);else{page.emit('response',response);page.emit('requestfinished',req);}if(key==='presenceLeave')oldLeave={req,response};}
 const turn=()=>new Promise(r=>setImmediate(r));
 function mount(name,planId){visible=name;url='https://test.atlassian.net/plugins/servlet/ac';const effects=[];const invoke=(key,payload)=>{if(key==='presenceLeave'&&fault==='missing-leave')return Promise.resolve({success:true});const id=key==='presenceLeave'&&fault==='wrong-owner'?'sim-foreign':payload.planId;return f.presenceCall(key,payload,key==='presenceBeat'&&(fault==='foreign-principal'||fault==='private-foreign-principal'&&planId===f.ack.plan.id)?'foreign':privateAccount).then(body=>{emit(key,id,body,{failed:key==='presenceLeave'&&fault==='failed-leave',stale:key==='presenceLeave'&&fault==='stale-leave'});if(key==='presenceLeave'&&fault==='duplicate-leave')emit(key,id,body);return body;});};
  const hook=new Function('useEffect','useRef','useState','useCallback','callResolver','window','document','setInterval','clearInterval',usePresence+';return usePresence;')((fn)=>effects.push(fn()),v=>({current:v}),v=>[v,()=>{}],fn=>fn,invoke,eventTarget(),eventTarget(),()=>1,()=>{});hook(planId,'planning',true);cleanup=()=>{for(const fn of effects)if(typeof fn==='function')fn();};}
 const construct=make(assert,expect,()=>({appId:'app',envId:'env'}),req=>JSON.parse(req.postDataBuffer()),x=>x,serializeForgeResponse,createReportCaptureObserver,createReportDocumentIdentity,departOwnedPlan,armPresenceLeave,admitPrivateSource,admitPrivateFork,admitPrivateForkIdentity,privateAccount);
 const session=construct(page,{record:(stage,value)=>records.push({stage,value}),timeoutMs:60});session.source(f.source,f.source.meta.name);mount(f.source.meta.name,f.source.meta.id);await turn();await session.drain();
 const transition=()=>session.fork(async()=>{cleanup();mount(fault==='private-mount'?'Wrong private mount':f.name,f.ack.plan.id);if(fault==='document-replaced'){await turn();document={};}await turn();return f.ack;},{source:f.source,snapshot:f.snapshot,name:f.name},async()=>({planRead:f.planRead,modelRead:f.modelRead}));
 return {f,session,records,posts,transition,emit,turn,replaceDocument:()=>document={}};
}
test('actual usePresence Create transition emits source leave, binds private generation and uses real Back before blank',async()=>{const f=await fixture();const owner=await f.transition();assert.equal(owner.planId,f.f.ack.plan.id);assert(!f.records.some(r=>r.stage==='actual-blank'));await f.session.stop();assert.equal(f.records.filter(r=>r.stage==='actual-blank').length,1);const leave=f.records.filter(r=>r.stage==='owned-departure-leave-observed');assert.equal(leave.length,2);assert.equal(leave[0].value.planId,f.f.source.meta.id);assert.equal(leave[1].value.planId,f.f.ack.plan.id);await f.session.stop();await f.session.dispose();});
test('actual failed, missing, foreign, duplicate, stale and invalid private mount transitions poison without blank or replay',async()=>{for(const fault of ['failed-leave','missing-leave','wrong-owner','duplicate-leave','private-mount','document-replaced','private-foreign-principal']){const f=await fixture({fault});await assert.rejects(f.transition(),/uncertain/,fault);assert.equal(f.session.owner().kind,'source');const count=f.records.length;await assert.rejects(f.session.stop());assert.equal(f.records.length,count);assert(!f.records.some(r=>r.stage==='actual-blank'));assert.equal(f.posts.length,0);await assert.rejects(f.session.dispose());}});
test('old observed leave cannot satisfy newly armed source transition',async()=>{const f=await fixture({fault:'stale-leave'});f.emit('presenceLeave',f.f.source.meta.id,{success:true});await f.turn();await f.session.drain();await assert.rejects(f.transition());assert.equal(f.session.owner().kind,'source');await assert.rejects(f.session.dispose());});
test('wrong principal or changed request document fails before private creation',async()=>{for(const fault of ['foreign-principal','replace-before-fork']){const f=await fixture({fault});if(fault==='replace-before-fork')f.replaceDocument();let actions=0;await assert.rejects(f.session.fork(async()=>{actions++;return f.f.ack;},{},async()=>({})));assert.equal(actions,0);await assert.rejects(f.session.dispose());}});
test('expired genuine wire refuses before an actual POST, and no raw credential enters retained evidence',async()=>{const f=await fixture({fault:'expired-wire'});await assert.rejects(f.session.invoke('getPlan',{planId:f.f.source.meta.id}),/uncertain/);assert.equal(f.posts.length,0);assert(!JSON.stringify(f.records).includes('opaque-private-secret'));assert(!JSON.stringify(f.records).includes('eyJlocal'));await assert.rejects(f.session.dispose());});

test('unknown actual capture transport poisons all subsequent mutations and preserves acknowledged private owner',async()=>{
 const f=await fixture();await f.transition();const states=[],protocol=f.session.capture(f.f.ack.plan.id,s=>states.push(s));
 f.emit('captureSponsorReport',f.f.ack.plan.id,{}, {failed:true,payload:{requestId:'one-real-intent',name:'Owned report'}});await f.turn();await assert.rejects(f.session.drain());assert(protocol.snapshot().error);
 await assert.rejects(f.session.invoke('deleteSponsorReport',{planId:f.f.ack.plan.id,reportId:'unconfirmed'},true));assert.equal(f.posts.length,0);assert.equal(f.session.owner().planId,f.f.ack.plan.id);assert(!f.records.some(r=>r.stage==='actual-blank'));await assert.rejects(f.session.dispose());
});

test('actual direct mutation drains an already dispatched failed UI response before any POST',async()=>{
 const f=await fixture();await f.transition();f.emit('getPlan',f.f.ack.plan.id,{}, {failed:true});
 // Do not yield to terminal classification. The mutation itself must await it.
 await assert.rejects(f.session.invoke('deleteSponsorReport',{planId:f.f.ack.plan.id,reportId:'known'},true));assert.equal(f.posts.length,0);assert(f.session.failure());await assert.rejects(f.session.dispose());
});

test('presence admission requires the actual own roster entry and rejects invented body success or malformed rosters',async()=>{
 for(const mutate of [x=>x.roster={},x=>x.roster=null,x=>x.roster=[],x=>x.roster[privateAccount].accountId='foreign',x=>x.success=true]){const f=await fixture();const body=await f.f.presenceCall('presenceBeat',{planId:f.f.source.meta.id,view:'planning'});mutate(body);f.emit('presenceBeat',f.f.source.meta.id,body);await f.turn();await f.session.drain();await assert.rejects(f.transition());assert.equal(f.session.owner().kind,'source');assert.equal(f.posts.length,0);await assert.rejects(f.session.dispose());}
});
