import test from 'node:test';
import assert from 'node:assert/strict';
import {createCapacityPreferences} from '../../scenarios/lz-ppm/capacity-preferences.mjs';
const settings=id=>({selectedPlanIds:[id],profiles:{},issueChoices:{}});
const original=settings('original'),owned=settings('owned');
function fixture(){let current=structuredClone(original),version=7;const calls=[];let fail;
 const invoke=async(name,payload)=>{calls.push({name,payload});if(fail)throw fail;if(name==='getCapacitySettings')return{success:true,settings:structuredClone(current),version};assert.equal(payload.expectedVersion,version);current=structuredClone(payload.settings);return{success:true,settings:structuredClone(current),version:++version};};
 return {invoke,calls,get current(){return current;},set current(v){current=v;version++;},set fail(e){fail=e;},get version(){return version;}};
}
test('exact owned state restores through versioned write and two independent reads',async()=>{const f=fixture(),p=createCapacityPreferences({invoke:f.invoke});p.admit(await f.invoke('getCapacitySettings'));await p.write(owned);f.calls.length=0;assert.deepEqual(await p.restore(),{initialized:true,restored:true});assert.deepEqual(f.current,original);assert.deepEqual(f.calls.map(c=>c.name),['getCapacitySettings','saveCapacitySettings','getCapacitySettings','getCapacitySettings']);assert.equal(f.calls[1].payload.expectedVersion,8);});
for(const phase of ['write','restore'])test(`foreign settings before ${phase} refuse without any overwrite`,async()=>{const f=fixture(),p=createCapacityPreferences({invoke:f.invoke});p.admit(await f.invoke('getCapacitySettings'));await p.write(owned);f.current=settings('foreign');f.calls.length=0;await assert.rejects(phase==='write'?p.write(settings('second')):p.restore(),{code:'LZ_CAPACITY_SETTINGS_RECOVERY_REQUIRED'});assert.deepEqual(f.current,settings('foreign'));assert.deepEqual(f.calls.map(c=>c.name),['getCapacitySettings']);});
for(const response of [{success:false,error:'uncertain server failure'},{success:true,settings:owned,version:90}])test(`unacknowledged response ${response.version||'failure'} keeps pending and blocks restoration`,async()=>{const f=fixture(),p=createCapacityPreferences({invoke:f.invoke});p.admit(await f.invoke('getCapacitySettings'));await p.beginWrite();assert.throws(()=>p.acknowledge(response));f.calls.length=0;await assert.rejects(p.restore(),{code:'LZ_CAPACITY_SETTINGS_RECOVERY_REQUIRED'});assert.ok(p.state.pending);assert.deepEqual(f.calls,[]);});
test('transport failure after possibly committed save does not license restoration',async()=>{const f=fixture();const invoke=async(name,payload)=>{const result=await f.invoke(name,payload);if(name==='saveCapacitySettings')throw new Error('response lost');return result;};const p=createCapacityPreferences({invoke});p.admit(await invoke('getCapacitySettings'));await assert.rejects(p.write(owned),/response lost/);assert.deepEqual(f.current,owned);f.calls.length=0;await assert.rejects(p.restore(),{code:'LZ_CAPACITY_SETTINGS_RECOVERY_REQUIRED'});assert.deepEqual(f.calls,[]);});
test('UI save acknowledgement is retained before a later report failure; known state safely restores',async()=>{const f=fixture();let savedResolve,reportReject;const saved=new Promise(r=>savedResolve=r),report=new Promise((_,r)=>reportReject=r);const p=createCapacityPreferences({invoke:f.invoke,observe:name=>name==='saveCapacitySettings'?saved:report});p.admit(await f.invoke('getCapacitySettings'));await assert.rejects(p.calculate(async()=>{savedResolve(await f.invoke('saveCapacitySettings',{settings:owned,expectedVersion:7}));await new Promise(r=>setImmediate(r));assert.deepEqual(p.state.lastOwned,owned);assert.equal(p.state.pending,null);reportReject(new Error('report failure'));}),/report failure/);assert.equal((await p.restore()).restored,true);});
test('unknown restore outcome remains failed and cannot authorize fixture deletion',async()=>{const f=fixture(),p=createCapacityPreferences({invoke:f.invoke});p.admit(await f.invoke('getCapacitySettings'));await p.write(owned);f.fail=new Error('network lost');await assert.rejects(p.restore(),{code:'LZ_CAPACITY_SETTINGS_RECOVERY_REQUIRED'});assert.equal(p.state.restored,false);assert.deepEqual(f.current,owned);});
test('second read changed by another user never reports successful restoration',async()=>{const f=fixture();let reads=0,armed=false;const invoke=async(name,payload)=>{if(armed&&name==='getCapacitySettings'&&++reads===3)f.current=settings('foreign');return f.invoke(name,payload);};const p=createCapacityPreferences({invoke});p.admit(await invoke('getCapacitySettings'));await p.write(owned);armed=true;await assert.rejects(p.restore(),{code:'LZ_CAPACITY_SETTINGS_RECOVERY_REQUIRED'});assert.equal(p.state.restored,false);assert.deepEqual(f.current,settings('foreign'));});
