import test from 'node:test';import assert from 'node:assert/strict';import {createRollingReadBudget} from '../../scenarios/lz-ppm/rolling-read-budget.mjs';
function clock(){let t=0;return {now:()=>t,advance:n=>t+=n,sleep:async ms=>{t+=ms;}};}
test('combined calls never exceed budget at boundary; every cost held61s after response',async()=>{const c=clock(),events=[],b=createRollingReadBudget({...c,onEvent:e=>events.push(e)});await b.run('first',2000,async()=>c.advance(5000));assert.equal(c.now(),5000);await b.run('second',1500,async()=>{});const starts=events.filter(e=>e.stage==='budget-start');assert.deepEqual(starts.map(e=>e.startedMs),[0,66000]);assert.equal(starts[1].waitedMs,61000);});
test('parallel callers cannot both spend unavailable units and wait for active response',async()=>{const c=clock(),events=[],b=createRollingReadBudget({...c,onEvent:e=>events.push(e)});let finish;const blocked=new Promise(r=>finish=r);const first=b.run('first',2000,async()=>{await blocked;c.advance(2000);});await new Promise(r=>setImmediate(r));let secondSent=false;const second=b.run('second',2000,async()=>{secondSent=true;});await new Promise(r=>setImmediate(r));assert.equal(secondSent,false);finish();await Promise.all([first,second]);assert.deepEqual(events.filter(e=>e.stage==='budget-start').map(e=>e.startedMs),[0,63000]);});
test('failed/unknown call is charged and never repeated',async()=>{const c=clock(),b=createRollingReadBudget(c);let sent=0;await assert.rejects(b.run('unknown',2500,async()=>{sent++;throw new Error('unknown');}),/unknown/);await b.run('later audit',1000,async()=>sent++);assert.equal(sent,2);assert.equal(c.now(),61000);});
test('cancelled pending wait sends no operation and does not change active outcome',async()=>{let release;const b=createRollingReadBudget();const a=b.run('active',2500,()=>new Promise(r=>release=r));await new Promise(r=>setImmediate(r));let sent=false;const q=b.run('queued',1000,async()=>{sent=true;});await new Promise(r=>setImmediate(r));b.close();await assert.rejects(q,/cancelled/);release('ok');assert.equal(await a,'ok');assert.equal(sent,false);await assert.rejects(b.run('closed',1,async()=>assert.fail()),/cancelled/);});
test('unknown/unbounded costs refuse before send; cancellation does not poison queue release',async()=>{const b=createRollingReadBudget();for(const cost of [0,-1,NaN,Infinity,3001,1.5])await assert.rejects(b.run('invalid',cost,async()=>assert.fail()));await b.run('valid',1,async()=>{});});
test('receipt failure preserves original operation error',async()=>{const b=createRollingReadBudget({onEvent:e=>{if(e.stage==='budget-return')throw new Error('receipt');}});await assert.rejects(b.run('actual',1,async()=>{throw new Error('body');}),e=>e instanceof AggregateError&&e.errors.map(x=>x.message).join(',')==='body,receipt');});

test('falsy thrown values remain failures rather than successful undefined returns',async()=>{for(const value of [undefined,null,0,false,'']){const b=createRollingReadBudget();let caught=false;try{await b.run('falsy',1,async()=>{throw value;});}catch(error){caught=true;assert.equal(error,value);}assert.equal(caught,true);}});
test('close during held start receipt prevents operation dispatch',async()=>{let release;const b=createRollingReadBudget({onEvent:e=>e.stage==='budget-start'?new Promise(r=>release=r):undefined});let sent=false;const p=b.run('held',1,async()=>{sent=true;});await new Promise(r=>setImmediate(r));b.close();release();await assert.rejects(p,/cancelled/);assert.equal(sent,false);});
test('close cancels finite budget timer promptly',async()=>{const b=createRollingReadBudget();await b.run('spent',3000,async()=>{});let sent=false;const p=b.run('wait',1,async()=>{sent=true;});await new Promise(r=>setImmediate(r));b.close();await assert.rejects(p,/cancelled/);assert.equal(sent,false);});
test('default monotonic pacing does not release costs when wall clock jumps',async()=>{const original=Date.now,b=createRollingReadBudget();try{await b.run('spent',3000,async()=>{});Date.now=()=>original()+86400000;assert.equal(b.snapshot().entries.length,1);assert.ok(b.snapshot().now<86400000);}finally{Date.now=original;b.close();}});
test('invalid response or regressing snapshot clock closes admission without releasing activecost',async()=>{for(const bad of [NaN,Infinity,-1]){let t=0;const b=createRollingReadBudget({now:()=>t});await assert.rejects(b.run('invalidreturn',2000,async()=>{t=bad;}),/budget receipt/);await assert.rejects(b.run('never',1,async()=>assert.fail()),/cancelled/);}let t=100;const b=createRollingReadBudget({now:()=>t});await b.run('old',2000,async()=>{});t=99;assert.throws(()=>b.snapshot(),/Monotonic/);await assert.rejects(b.run('never',1,async()=>assert.fail()),/cancelled/);});
