import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {admitPacedResume,continuePacedReport,failedSha,recoveredSha} from '../../scenarios/lz-ppm/seventeenth-paced-resume-contract.mjs';
import {advanceReadCost,resolverReadCost,hookReadCost} from '../../scenarios/lz-ppm/seventeenth-read-cost.mjs';
const failed=JSON.parse(fs.readFileSync('evidence/lz-campaign/seventeenth-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--f695f-rt-and-HTML-without-cleanup-chromium/seventeenth-forecast-resume.json'));
const recovered=JSON.parse(fs.readFileSync('evidence/lz-campaign/seventeenth-quota-readonly-admission-20260906/receipt.json'));
const source=JSON.parse(fs.readFileSync('evidence/lz-campaign/seventeenth-source-return-readonly-20260906/artifacts/scenarios-lz-ppm-campaign--755d0-eserve-exact-retained-state-chromium/seventeenth-source.json'));
const previous={job:source.finalJob,probe:source.finalProbe};
const admit=(f=failed,r=recovered,d=failedSha,rd=recoveredSha)=>admitPacedResume(f,d,r,rd,previous);
test('actual48 immutable responses plus47 saved statuses/probes and laterstrong126 admit all40 priorruns',()=>{const x=admit();assert.equal(x.job.checkpoint,126);assert.equal(x.probe.privateArtifacts.length,182);assert.equal(x.job.forecastRuns.completed,40);});
test('wrong receipt digest, missing real ack, forged40 counter and erased saved proof refuse',()=>{assert.throws(()=>admit(failed,recovered,'0'.repeat(64)));assert.throws(()=>admit(failed,recovered,failedSha,'0'.repeat(64)));for(const change of [f=>f.events=f.events.filter((e,i)=>i!==f.events.findIndex(x=>x.stage==='advanceSponsorReportCapture')),f=>f.events.find(e=>e.stage==='advanceSponsorReportCapture').value.body.job.forecastRuns.completed=40,f=>f.probes[30].privateArtifacts.pop()]){const f=structuredClone(failed);change(f);assert.throws(()=>admit(f));}});
test('wrong checkpoint/publication/changed original header or unknown read response cannot seed recovery',()=>{for(const change of [r=>r.body.checkpoint=127,r=>r.body.publicArtifacts.push({}),r=>r.body.privateArtifacts[0].actualHash='0'.repeat(64),r=>r.completed=false,r=>r.requestCount=2]){const r=structuredClone(recovered);change(r);assert.throws(()=>admit(failed,r));}});
async function run(fault){const admitted=admit();let actual=admitted.job,calls=0,probes=0;const labels=['Verifying forecast results','Preparing the retained schedule','Preparing forecast results','Publishing the verified report'];return {result:await continuePacedReport({initial:actual,progress:admitted.progress,advance:async payload=>{calls++;assert.equal(payload.expectedCheckpoint,actual.checkpoint);if(fault==='transport')throw new Error('unknown');actual={...actual,checkpoint:actual.checkpoint+1,completedUnits:actual.checkpoint+1,totalUnits:200,stageLabel:labels[calls-1],state:calls===4?'complete':'active'};return {httpStatus:200,outerSuccess:true,body:{success:fault!=='refusal',job:actual}};},status:async()=>fault==='status'?{...actual,checkpoint:999}:actual,probe:async()=>{probes++;if(fault==='probe')throw new Error('physical mismatch');}}).catch(error=>({error,calls,probes})),calls,probes};}
test('seeded continuation completes required remaining stages without rerunning anyforecast',async()=>{const x=await run();assert.equal(x.result.state,'complete');assert.equal(x.calls,4);assert.equal(x.probes,4);});
test('unknown/refused/mismatched savedstatus or physical failure sends no second advance',async()=>{for(const failure of ['transport','refusal','status','probe']){const x=await run(failure);assert.ok(x.result.error);assert.equal(x.result.calls,1);}});
test('exact measured stage lookup uses previousack, sourcechecks conservative768 and unknownfallback768',()=>{const {job}=admit();assert.equal(advanceReadCost(job),96);assert.equal(advanceReadCost({...job,stageLabel:'Checking for plan changes'}),768);assert.equal(advanceReadCost({...job,stageLabel:'Retaining report pages'}),192);assert.equal(advanceReadCost({...job,stageLabel:'new unknown label'}),768);assert.throws(()=>advanceReadCost({...job,id:'foreign'}));assert.equal(resolverReadCost('getSponsorReportPage'),16);assert.equal(resolverReadCost('getSnapshot'),512);assert.equal(hookReadCost({what:'reportCaptureState'}),1024);assert.throws(()=>resolverReadCost('cancelSponsorReportCapture'));assert.throws(()=>hookReadCost({what:'deleteFixture'}));});
