import test from 'node:test';
import assert from 'node:assert/strict';
import {installPortableViewportSizing} from '../../forge/portable-viewport.mjs';
function fake(){
 const events=[], all=[];let failResize,failClose,failSync,failDetach,block;
 const ctx={pages:()=>all.filter(p=>!p.closed),async newPage(){events.push('new');const page={size:{width:1440,height:900},closed:false,viewportSize(){return {...this.size};},isClosed(){return this.closed;},async setViewportSize(v){events.push('resize:'+v.width);if(block)await block;if(failResize)throw failResize;this.size={...v};},async close(){events.push('page-close');if(failClose)throw failClose;this.closed=true;}};all.push(page);return page;},async close(){events.push('context-close');for(const p of all)p.closed=true;},async newCDPSession(p){return{async send(method,arg){events.push([method,arg]);if(method==='Browser.getWindowForTarget')return{windowId:p.window||1};if(failSync)throw failSync;},async detach(){events.push('detach');if(failDetach)throw failDetach;}};}};
 return {ctx,events,all,setFailure(name,value){({resize:x=>failResize=x,close:x=>failClose=x,sync:x=>failSync=x,detach:x=>failDetach=x,block:x=>block=x}[name])(value);}};
}
const sizes=f=>f.events.filter(e=>Array.isArray(e)&&e[0]==='Browser.setContentsSize').map(e=>e[1]);
test('same requested CSS size is preserved; envelope protects both pages',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const a=await f.ctx.newPage();await a.setViewportSize({width:1600,height:1100});const b=await f.ctx.newPage();assert.deepEqual(sizes(f).at(-1),{windowId:1,width:1600,height:1100});assert.deepEqual(b.viewportSize(),{width:1440,height:900});await a.setViewportSize({width:1100,height:1000});assert.deepEqual(sizes(f).at(-1),{windowId:1,width:1440,height:1000});await b.close();assert.deepEqual(sizes(f).at(-1),{windowId:1,width:1100,height:1000});});
test('same-size resize still restores physical contents',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const p=await f.ctx.newPage();const before=sizes(f).length;await p.setViewportSize(p.viewportSize());assert.equal(sizes(f).length,before+1);});
test('actual separate browser windows use separate envelopes',async()=>{const f=fake();const a=await f.ctx.newPage(),b=await f.ctx.newPage();a.window=4;b.window=5;installPortableViewportSizing(f.ctx);await a.setViewportSize({width:1600,height:1100});assert.deepEqual(sizes(f),[{windowId:4,width:1600,height:1100},{windowId:5,width:1440,height:900}]);});
test('concurrent public resize and close serialize before resolving',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const a=await f.ctx.newPage(),b=await f.ctx.newPage();let release;f.setFailure('block',new Promise(r=>release=r));const resizing=a.setViewportSize({width:1100,height:1000}),closing=b.close();await Promise.resolve();assert.equal(b.closed,false);release();await Promise.all([resizing,closing]);assert.deepEqual(sizes(f).at(-1),{windowId:1,width:1100,height:1000});});
test('close failure and restore failure both retained; other cleanup remains usable',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const p=await f.ctx.newPage();const first=Error('close-failed'),second=Error('restore-failed');f.setFailure('close',first);f.setFailure('sync',second);await assert.rejects(p.close(),e=>e instanceof AggregateError&&e.errors[0]===first&&e.errors[1]===second);f.setFailure('close',null);f.setFailure('sync',null);await p.close();assert.equal(p.closed,true);});
test('failed new-page sizing closes the unreturned owned page',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const error=Error('restore-failed');f.setFailure('sync',error);await assert.rejects(f.ctx.newPage(),e=>e===error);assert.equal(f.all[0].closed,true);});
test('failed new-page sizing and failed owned cleanup retain all causes',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const a=Error('restore'),b=Error('close');f.setFailure('sync',a);f.setFailure('close',b);await assert.rejects(f.ctx.newPage(),e=>e instanceof AggregateError&&e.errors.includes(a)&&e.errors.includes(b));});
test('protocol cleanup errors retained after primary error',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const p=await f.ctx.newPage();const a=Error('protocol'),b=Error('detach');f.setFailure('sync',a);f.setFailure('detach',b);await assert.rejects(p.setViewportSize(p.viewportSize()),e=>e instanceof AggregateError&&e.errors[0]===a&&e.errors[1]===b);});
test('context teardown skips repair and rejects new work',async()=>{const f=fake();installPortableViewportSizing(f.ctx);const p=await f.ctx.newPage();const n=sizes(f).length;await f.ctx.close();await p.close();assert.equal(sizes(f).length,n);await assert.rejects(f.ctx.newPage(),/PORTABLE_CONTEXT_CLOSING/);await assert.rejects(p.setViewportSize(p.viewportSize()),/PORTABLE_CONTEXT_CLOSING/);});
test('installation is idempotent and existing pages get public wrappers',async()=>{const f=fake();const p=await f.ctx.newPage();installPortableViewportSizing(f.ctx);const newPage=f.ctx.newPage;installPortableViewportSizing(f.ctx);assert.equal(f.ctx.newPage,newPage);await p.setViewportSize({width:1600,height:1100});assert.equal(sizes(f).length,1);});

test('context close during pending new page cannot return an admitted page',async()=>{const f=fake();let release;const original=f.ctx.newPage.bind(f.ctx);f.ctx.newPage=async()=>{await new Promise(r=>release=r);return original();};installPortableViewportSizing(f.ctx);const creating=f.ctx.newPage();await Promise.resolve();const closing=f.ctx.close();release();await assert.rejects(creating,/PORTABLE_CONTEXT_CLOSING/);await closing;assert.equal(f.all[0].closed,true);assert.equal(sizes(f).length,0);});
