// Read-only completion after exact four deletions; no repeated mutation.
import './campaign-identity.spec';
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {test,expect} from '../../fixtures/forge';import {getTestState} from '../../testhook/client';
import {openPlans,LZPT_PLAN} from './forecast-fixture';import {actualResponse} from './campaign-ui';import {settledScreenshot} from './settled-screenshot.mjs';
import {getHarnessLaunchReceipt} from '../../forge/browser';import {assertDiagnosticReceipt} from './portable-diagnostic-receipt.mjs';
test('confirm cleanup: exact three original plans, original45 and empty version36 preferences remain; deleted diagnostic issue/release/plan are absent on second reads',async({page},info)=>{
 const receipt=assertDiagnosticReceipt(getHarnessLaunchReceipt(page.context()));const dir=process.env.LZ_CAMPAIGN_UNIT_DIR!,identity=JSON.parse(fs.readFileSync(path.join(dir,'before-identity.json'),'utf8'));const originals=[LZPT_PLAN,'plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].sort();expect(identity.planIds).toEqual(originals);
 const source=path.resolve('evidence/lz-campaign/sixth-diagnostic-exact-cleanup-20260906/artifacts/scenarios-lz-ppm-campaign--76f99-references-remain-untouched-chromium/exact-cleanup.json');const raw=fs.readFileSync(source),prior=JSON.parse(raw.toString());expect(prior.owned).toMatchObject({planId:'plan-test-mtozislw-v816ze',issueKey:'WFH-2847',versionId:'10289',reportId:'4fbb1943-7064-4dc1-8faa-e06816c188f6'});expect(prior.acks.map((a:any)=>a.operation)).toEqual(['delete-report','delete-plan','delete-issue','delete-release']);expect(prior.acks[0].value).toEqual({success:true,deleted:true});expect(prior.acks[1].value).toEqual({deleted:prior.owned.planId,registryRemoved:true});for(const item of prior.acks.slice(2))expect(item.value.status).toBe(204);for(const stage of ['report-absent','plan-absent','issue-absent','release-absent'])expect(prior.reads.filter((r:any)=>r.stage===stage)).toHaveLength(2);expect(prior.settings).toEqual({success:true,version:36,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}});
 const journal:any={receipt,priorCleanupSha256:createHash('sha256').update(raw).digest('hex'),originalDestructiveAttemptRemainsFailed:true,reads:[],complete:false};const save=()=>fs.writeFileSync(info.outputPath('readonly-cleanup-confirmation.json'),JSON.stringify(journal,null,2)+'\n');save();
 for(let n=0;n<2;n++){
  for(const url of ['/rest/api/3/issue/WFH-2847?fields=project,summary','/rest/api/3/version/10289']){const r=await page.context().request.get('https://wolfaenpak.atlassian.net'+url,{maxRetries:0,maxRedirects:0});journal.reads.push({url,status:r.status()});save();expect(r.status()).toBe(404);}
  const absent=await getTestState('lz-ppm',{what:'plan',planId:prior.owned.planId});expect(absent.meta==null).toBe(true);expect(absent.issues).toEqual([]);expect((await getTestState('lz-ppm',{what:'plans'})).plans.map((p:any)=>p.id).sort()).toEqual(originals);journal.reads.push({planAbsent:absent,planIds:originals});save();
 }
 const frame=await openPlans(page);await expect(frame.locator('body')).toContainText(/V4\.58\.579/i);await expect(frame.getByRole('button',{name:/Open plan/})).toHaveCount(3);const card=frame.locator('.lz-card',{hasText:'LZPT Scenarios'});await expect(card).toContainText(/45\s*ISSUES/i);await expect(card).toContainText(/0\s*DRAFTS/i);await settledScreenshot(page,{subject:card,path:info.outputPath('original-three-plans-restored.png'),fullPage:true});
 const pending=actualResponse(page,'getCapacitySettings');await frame.getByRole('button',{name:'Capacity',exact:true}).click();journal.settings=await pending;expect(journal.settings).toEqual(prior.settings);const cap=frame.locator('[data-testid="capacity-view"]');await expect(cap.getByRole('status')).toHaveCount(0,{timeout:120000});await expect(cap.getByRole('checkbox')).toHaveCount(3);for(const box of await cap.getByRole('checkbox').all())await expect(box).toHaveAttribute('aria-checked','false');await expect(cap.locator('[data-testid="capacity-cell"]')).toHaveCount(0);await settledScreenshot(cap,{path:info.outputPath('private-settings-still-empty.png')});journal.complete=true;save();
});
