// Read/export only. Exact retained fixture is deliberately NOT deleted by this diagnostic.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
import {test,expect} from '../../fixtures/forge';import {getTestState} from '../../testhook/client';
import {getHarnessLaunchReceipt} from '../../forge/browser';import {openPlans,openPlan,scheduleFields,LZPT_PLAN} from './forecast-fixture';
import {actualResponse,currentUserResolver,planning,callOf} from './campaign-ui';import {settledScreenshot} from './settled-screenshot.mjs';
import {observeCaptureProbe,verifyCaptureProbe} from './report-capture-cleanup.mjs';
const planId='plan-test-mtpbanj1-vfroj0',jobId='ee2cdc5f-28e5-441b-b902-6d236f8560fd',reportId='bfb483ea-abfa-4c1e-829c-5e4907c8a719',issueKey='WFH-2904',name='[harness-test] lz-norm-mtpbakob';
const originals=[LZPT_PLAN,'plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].sort(),expectedPlans=[...originals,planId].sort();
const sha=(s:any)=>createHash('sha256').update(s).digest('hex');
const canonical=(x:any):any=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x;
const sourceDir=path.resolve('evidence/lz-campaign/fourteenth-staged-report-live-20260906/report-capture-jobs-live/attempt-001/tests-artifacts/scenarios-lz-ppm-journey-c-26aea-use-then-full-retained-HTML-chromium');
const expectedRow={key:issueKey,summary:name+' report job resume',startDate:'2026-10-05',dueDate:'2026-10-09',duration:5,buffer:'No',statusCategory:'new',parentKey:null};
test.describe.configure({retries:0,timeout:300000});
test('recovery read: exact retained fourteenth report content, pages and actual HTML stay unchanged; original registry and preferences preserved',async({page},info)=>{
 const bytes=fs.readFileSync(path.join(sourceDir,'job-resume-protocol.json'));expect(sha(bytes)).toBe('56fc4f75f6b6e2cd44b2a06e69fb6867276c589dec93383945330745ce5d16ff');const original=JSON.parse(bytes.toString());expect(original.job).toMatchObject({id:jobId,state:'complete',checkpoint:16,cleanupDone:true,reportId});expect(original.report.id).toBe(reportId);
 expect(sha(JSON.stringify(canonical([expectedRow])))).toBe(original.report.document.timeline.hashes[0]);
 const receipt=getHarnessLaunchReceipt(page.context());if(!receipt||receipt.mode!=='portable-chrome152')throw new Error('An admitted portable Chrome152 receipt is required');expect(receipt).toMatchObject({mode:'portable-chrome152',browserVersion:'152.0.7977.76',principalSha256:'b4cb5211a5e4d44c9f3a6bc909588c2fe62162358d4b0c04da52aa6977433769',executableSha256:'755178ee89130a6f1c94cc4ecb2289fe74240db3e7efe9ec69a6cfcd4b93a6ee',frameworkSha256:'bfea9981cc61dfa72d847c920f274e4e96e362954f451198d8ee1650cbefb2e6'});expect(process.env.LZ_EXPECTED_UI_VERSION).toMatch(/^4\.58\.\d+$/);expect(receipt.uiVersion).toBe(process.env.LZ_EXPECTED_UI_VERSION);
 const journal:any={receipt,readOnly:true,retained:{planId,jobId,reportId,issueKey,name},sourceProtocolSha:sha(bytes),events:[],probes:[],complete:false};const save=()=>fs.writeFileSync(info.outputPath('retained-fourteenth-read.json'),JSON.stringify(journal,null,2));const record=(stage:string,value:any={})=>{journal.events.push({stage,time:new Date().toISOString(),value});save();};save();
 const rpc=currentUserResolver(page,c=>c?.functionKey==='getCapacitySettings');const allowed=new Set(['getCapacitySettings','getDraft','getActiveDrafts','getLockStatus','getSponsorReportCapture','getSponsorReport','getSponsorReportPage','listSponsorReports']);
 const read=async(key:string,payload:any={})=>{expect(allowed.has(key)).toBe(true);const value=await rpc.invoke(key,payload);record(key,value);expect(value.success).toBe(true);return value;};
 const observedMutations:any[]=[];const request=(req:any)=>{const c=callOf(req);if(c&&['captureSponsorReport','advanceSponsorReportCapture','cancelSponsorReportCapture','deleteSponsorReport','deletePlan','saveCapacitySettings'].includes(c.functionKey)){observedMutations.push({key:c.functionKey,payload:c.payload});}};page.on('request',request);
 const source=async()=>{const s=await getTestState('lz-ppm',{what:'plan',planId:LZPT_PLAN});expect(s.issues).toHaveLength(45);const basis={issues:scheduleFields(s.issues),sources:s.meta.sources,calendarKey:s.meta.calendarKey,holidayYears:s.meta.holidayYears,milestones:s.meta.milestones,protectionEnabled:s.meta.protectionEnabled};expect(sha(JSON.stringify(basis))).toBe('2d5c1ea0d3e742ff61ae47701ab6a391d0cbe6f0238e9415fb73b38e8f21f104');return s;};
 const registry=async()=>{const value=await getTestState('lz-ppm',{what:'plans'});expect(value.plans.map((p:any)=>p.id).sort()).toEqual(expectedPlans);return value.plans;};
 const issue=async()=>{const response=await page.context().request.get(`https://wolfaenpak.atlassian.net/rest/api/3/issue/${issueKey}?fields=project,labels,summary,customfield_10015,duedate,customfield_10180`,{maxRetries:0,maxRedirects:0});expect(response.status()).toBe(200);const value=await response.json();expect(value.key).toBe(issueKey);expect(value.id).toMatch(/^\d+$/);expect(value.fields).toMatchObject({project:{key:'WFH'},labels:['lz-norm-mtpbakob'],summary:expectedRow.summary,customfield_10015:expectedRow.startDate,duedate:expectedRow.dueDate,customfield_10180:5});return value;};
 const probe=()=>observeCaptureProbe(()=>getTestState('lz-ppm',{what:'reportCaptureState',planId,jobId}),(value:any)=>{journal.probes.push(value);save();});
 let settings:any,initialSource:any,initialPlan:any,initialIssue:any,bodyError:any;
 try{
  initialSource=await source();record('original-source',initialSource);record('exact-four-registry',await registry());initialPlan=await getTestState('lz-ppm',{what:'plan',planId});expect(initialPlan.meta).toMatchObject({id:planId,name,createdBy:'harness'});expect(initialPlan.issues.map((i:any)=>i.key)).toEqual([issueKey]);record('owned-plan',initialPlan);initialIssue=await issue();record('owned-issue-positive',initialIssue);
  const frame=await openPlans(page);await expect(frame.getByRole('button',{name:/Open plan/})).toHaveCount(4);const pending=actualResponse(page,'getCapacitySettings');await frame.getByRole('button',{name:'Capacity',exact:true}).click();settings=await pending;expect(settings.success).toBe(true);expect(Number.isSafeInteger(settings.version)).toBe(true);expect(settings.version).toBeGreaterThanOrEqual(57);record('admitted-current-private-preferences',settings);
  expect((await read('getDraft',{planId:LZPT_PLAN})).draft).toBeNull();expect((await read('getActiveDrafts',{planId:LZPT_PLAN})).drafts).toEqual({});expect((await read('getDraft',{planId})).draft).toBeNull();expect((await read('getActiveDrafts',{planId})).drafts).toEqual({});expect(await read('getLockStatus',{planId})).toMatchObject({locked:false});
  expect((await read('getSponsorReportCapture',{planId,jobId})).job).toEqual(original.job);const physical=await probe();verifyCaptureProbe(physical,{planId,jobId,...original.job});expect(physical.privateArtifacts).toHaveLength(6);expect(physical.publicArtifacts).toHaveLength(5);
  expect((await read('getSponsorReport',{planId,reportId})).report).toEqual(original.report);const pages:any[]=[];for(const [section,count]of Object.entries(original.report.pages)){expect(Number.isSafeInteger(count)).toBe(true);for(let n=0;n<Number(count);n++){const response=await read('getSponsorReportPage',{planId,reportId,section,page:n});expect(response.page.rows).toHaveLength(original.report.document[section].sizes[n]);expect(sha(JSON.stringify(canonical(response.page.rows)))).toBe(original.report.document[section].hashes[n]);pages.push(response.page);}}
  expect(pages).toHaveLength(1);expect(pages[0].rows).toEqual([expectedRow]);journal.pages=pages;save();
  const pf=await openPlan(page,name),work=await planning(pf);await work.getByRole('button',{name:'Sponsor reports',exact:true}).click();const report=work.locator('[data-testid="sponsor-reports"]');const reportRead=actualResponse(page,'getSponsorReport',planId);await report.getByRole('navigation',{name:'Retained sponsor reports'}).getByRole('button').filter({hasText:'Bounded resume report'}).click();expect((await reportRead).report).toEqual(original.report);
  await expect(report.locator('[data-testid="report-forecast"]')).toContainText('P50 2026-10-09 · P80 2026-10-12 · P90 2026-10-12');await settledScreenshot(report.locator('[data-testid="report-forecast"]'),{path:info.outputPath('retained-fourteenth-forecast.png')});
  record('download-wait');const pendingDownload=page.waitForEvent('download',{timeout:120000});pendingDownload.catch(()=>{});await report.getByRole('button',{name:'Download complete HTML report',exact:true}).click();record('download-click');const download=await pendingDownload;record('download-event',{filename:download.suggestedFilename()});expect(download.suggestedFilename()).toBe(`sponsor-report-${reportId}.html`);const file=info.outputPath('retained-fourteenth-report.html');await download.saveAs(file);expect(await download.failure()).toBeNull();record('download-saved',{file,sha256:sha(fs.readFileSync(file)),bytes:fs.statSync(file).size});
  const doc=await page.context().newPage();let docError:any;const external:string[]=[];doc.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});try{await doc.goto(pathToFileURL(file).href);await expect(doc.locator('script,iframe,img,link')).toHaveCount(0);await expect(doc.locator('tr[data-issue-key]')).toHaveCount(1);await expect(doc.locator('tr[data-target-key],tr[data-capacity-key]')).toHaveCount(0);const row=doc.locator(`tr[data-issue-key="${issueKey}"]`);expect(await row.locator('td').allTextContents()).toEqual([issueKey,expectedRow.summary,expectedRow.startDate,expectedRow.dueDate,'5','new','']);await expect(row.locator('.track .bar')).toHaveCount(1);await expect(doc.locator('body')).toContainText('P50 2026-10-09 · P80 2026-10-12 · P90 2026-10-12');await expect(doc.locator('body')).toContainText(original.report.capacity.reason);expect(external).toEqual([]);await settledScreenshot(doc,{subject:row,path:info.outputPath('retained-fourteenth-complete-html.png'),fullPage:true});await doc.pdf({path:info.outputPath('retained-fourteenth-report.pdf'),printBackground:true,preferCSSPageSize:true});record('pdf-saved',{sha256:sha(fs.readFileSync(info.outputPath('retained-fourteenth-report.pdf')))});}catch(error){docError=error;throw error;}finally{try{await doc.close();record('local-document-closed');}catch(error){throw new AggregateError([...(docError?[docError]:[]),error],'Report document/close errors');}}
  expect((await read('getSponsorReport',{planId,reportId})).report).toEqual(original.report);for(let n=0;n<2;n++){const after=await probe();verifyCaptureProbe(after,{planId,jobId,...original.job},physical);}journal.complete=true;record('read-export-verified-retained');
 }catch(error){bodyError=error;record('original-error',String(error));throw error;}
 finally{const errors:any[]=[];for(const [label,audit]of [
  ['source',async()=>{if(initialSource)expect(await source()).toEqual(initialSource);}],
  ['registry',async()=>{record('final-registry',await registry());}],
  ['original-drafts',async()=>{if(settings){expect((await read('getDraft',{planId:LZPT_PLAN})).draft).toBeNull();expect((await read('getActiveDrafts',{planId:LZPT_PLAN})).drafts).toEqual({});}}],
  ['owned-plan',async()=>{if(initialPlan)expect(await getTestState('lz-ppm',{what:'plan',planId})).toEqual(initialPlan);}],
  ['owned-issue',async()=>{if(initialIssue)expect(await issue()).toEqual(initialIssue);}],
  ['preferences',async()=>{if(settings)for(let n=0;n<2;n++)expect(await read('getCapacitySettings',{})).toEqual(settings);}],
  ['no-mutations',async()=>expect(observedMutations).toEqual([])]
 ]as const){try{await audit();}catch(error){errors.push(error);record('audit-error',{label,error:String(error)});}}if(errors.length)journal.complete=false;rpc.stop();page.off('request',request);save();if(errors.length)throw new AggregateError([...(bodyError?[bodyError]:[]),...errors],'Read-only recovery and independent integrity audit errors');}
});
