// Exact reviewed retained fixture only. No generic registry exception or cleanup retry.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {test,expect} from '../../fixtures/forge';import {getTestState} from '../../testhook/client';import {getHarnessLaunchReceipt} from '../../forge/browser';
import {openPlans,scheduleFields,LZPT_PLAN} from './forecast-fixture';import {actualResponse,currentUserResolver} from './campaign-ui';
import {cleanReportCapture,verifyCaptureProbe,observeCaptureProbe} from './report-capture-cleanup.mjs';import {settledScreenshot} from './settled-screenshot.mjs';
const planId='plan-test-mtpbanj1-vfroj0',jobId='ee2cdc5f-28e5-441b-b902-6d236f8560fd',reportId='bfb483ea-abfa-4c1e-829c-5e4907c8a719',issueKey='WFH-2904',name='[harness-test] lz-norm-mtpbakob';
const originals=[LZPT_PLAN,'plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].sort(),initialIds=[...originals,planId].sort();const sha=(s:any)=>createHash('sha256').update(s).digest('hex');
const acceptedDir=path.resolve('evidence/lz-campaign/fourteenth-report-read-20260906'),artifact=path.join(acceptedDir,'artifacts/scenarios-lz-ppm-campaign--f0e54-y-and-preferences-preserved-chromium');
test.describe.configure({retries:0,timeout:300000});
test('cleanup: exact reviewed fourteenth report staging plan and issue removed once; original three plans and preferences preserved',async({page},info)=>{
 const acceptedBytes=fs.readFileSync(path.join(artifact,'retained-fourteenth-read.json'));expect(sha(acceptedBytes)).toBe('4986e6b82fc27750020150e1e07a843746c212781d61d9706fc74ddf5387c7ad');const accepted=JSON.parse(acceptedBytes.toString());expect(accepted.complete).toBe(true);expect(accepted.retained).toEqual({planId,jobId,reportId,issueKey,name});const result=JSON.parse(fs.readFileSync(path.join(acceptedDir,'result.json'),'utf8'));expect(result.stats.expected).toBe(1);expect(result.stats.unexpected).toBe(0);expect(result.errors).toEqual([]);
 expect(sha(fs.readFileSync(path.join(artifact,'retained-fourteenth-report.html')))).toBe('88de34d1bf4e807d7c7fc214614f5be7bc8259ad06d19bff764c9e3fde118800');expect(sha(fs.readFileSync(path.join(artifact,'retained-fourteenth-report.pdf')))).toBe('f6d198b5a51300112f09603ffaaa36d4249158271f7d8bc00297f4ddbe07df5b');
 const event=(label:string)=>accepted.events.find((e:any)=>e.stage===label).value,originalPlan=event('owned-plan'),originalIssue=event('owned-issue-positive'),originalSource=event('original-source'),originalReport=event('getSponsorReport').report,originalJob=event('getSponsorReportCapture').job,originalSettings=event('admitted-current-private-preferences');
 expect(originalPlan.meta).toMatchObject({id:planId,name,createdBy:'harness'});expect(originalIssue.key).toBe(issueKey);expect(originalReport.id).toBe(reportId);expect(originalJob.id).toBe(jobId);expect(originalSettings).toEqual({success:true,version:57,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}});
 const receipt=getHarnessLaunchReceipt(page.context());if(!receipt||receipt.mode!=='portable-chrome152')throw new Error('Known portable receipt required');expect(receipt).toMatchObject({browserVersion:'152.0.7977.76',principalSha256:'b4cb5211a5e4d44c9f3a6bc909588c2fe62162358d4b0c04da52aa6977433769',executableSha256:'755178ee89130a6f1c94cc4ecb2289fe74240db3e7efe9ec69a6cfcd4b93a6ee',frameworkSha256:'bfea9981cc61dfa72d847c920f274e4e96e362954f451198d8ee1650cbefb2e6'});expect(receipt.uiVersion).toBe(process.env.LZ_EXPECTED_UI_VERSION);
 const journal:any={receipt,owned:{planId,jobId,reportId,issueKey,issueId:originalIssue.id},parentAcceptance:'Root personally inspected actual HTML screenshot and both PDF pages after exact read/export passed',intents:[],acks:[],reads:[],complete:false};const save=()=>fs.writeFileSync(info.outputPath('fourteenth-exact-cleanup.json'),JSON.stringify(journal,null,2));const record=(stage:string,value:any)=>{journal.reads.push({stage,time:new Date().toISOString(),value});save();};const intent=(stage:string)=>{journal.intents.push({stage,time:new Date().toISOString()});save();};const ack=(stage:string,value:any)=>{journal.acks.push({stage,time:new Date().toISOString(),value});save();};save();
 const rpc=currentUserResolver(page,c=>c?.functionKey==='getCapacitySettings');let ready=false,bodyError:any;const invoke=async(key:string,payload:any={})=>{const value=await rpc.invoke(key,payload);record(key,value);return value;};
 const checkPrefs=async()=>expect(await invoke('getCapacitySettings',{})).toEqual(originalSettings);
 const registry=async(expected:string[])=>{const value=await getTestState('lz-ppm',{what:'plans'});record('registry',value.plans);expect(value.plans.map((p:any)=>p.id).sort()).toEqual(expected);};
 const source=async()=>{const value=await getTestState('lz-ppm',{what:'plan',planId:LZPT_PLAN});record('original-source',value);expect(value).toEqual(originalSource);const basis={issues:scheduleFields(value.issues),sources:value.meta.sources,calendarKey:value.meta.calendarKey,holidayYears:value.meta.holidayYears,milestones:value.meta.milestones,protectionEnabled:value.meta.protectionEnabled};expect(sha(JSON.stringify(basis))).toBe('2d5c1ea0d3e742ff61ae47701ab6a391d0cbe6f0238e9415fb73b38e8f21f104');};
 const rest=async(method:'GET'|'DELETE')=>{const response=await page.context().request.fetch(`https://wolfaenpak.atlassian.net/rest/api/3/issue/${issueKey}${method==='GET'?'?fields=project,labels,summary,customfield_10015,duedate,customfield_10180':''}`,{method,maxRetries:0,maxRedirects:0});const text=await response.text();return{status:response.status(),data:text?JSON.parse(text):null};};
 const proveIssue=async()=>{const value=await rest('GET');record('owned-issue-positive',value);expect(value.status).toBe(200);expect(value.data).toEqual(originalIssue);};
 const drafts=async(id:string)=>{expect(await invoke('getDraft',{planId:id})).toEqual({success:true,draft:null});expect(await invoke('getActiveDrafts',{planId:id})).toEqual({success:true,drafts:{}});};
 const probe=()=>observeCaptureProbe(()=>getTestState('lz-ppm',{what:'reportCaptureState',planId,jobId}),(value:any)=>record('physical-probe',value));
 try{
  await source();await registry(initialIds);expect(await getTestState('lz-ppm',{what:'plan',planId})).toEqual(originalPlan);await proveIssue();
  const frame=await openPlans(page),pending=actualResponse(page,'getCapacitySettings');await frame.getByRole('button',{name:'Capacity',exact:true}).click();expect(await pending).toEqual(originalSettings);ready=true;await checkPrefs();await drafts(LZPT_PLAN);await drafts(planId);const lock=await invoke('getLockStatus',{planId});expect(lock.success).toBe(true);expect(lock.locked).toBe(false);
  expect((await invoke('getSponsorReportCapture',{planId,jobId})).job).toEqual(originalJob);const before=await probe();verifyCaptureProbe(before,{planId,jobId,...originalJob});expect((await invoke('getSponsorReport',{planId,reportId})).report).toEqual(originalReport);
  await page.goto('about:blank');await checkPrefs();intent('delete-exact-report');const deleted=await invoke('deleteSponsorReport',{planId,reportId});expect(deleted).toMatchObject({success:true,deleted:true});ack('delete-exact-report',deleted);
  const cleaned:any=await cleanReportCapture({planId,jobId,requestId:originalJob.requestId,invoke,probe:async()=>probe(),onState:(value:any)=>record('job-cleanup-checkpoint',value)});expect(cleaned.cleaned).toBe(true);expect(cleaned.job.state).toBe('cancelled');expect(cleaned.job.cleanupDone).toBe(true);verifyCaptureProbe(cleaned.probes.at(-1),{planId,jobId,...cleaned.job},before);ack('job-public-private-artifacts-absent',cleaned);
  for(let n=0;n<2;n++){const absent=await invoke('getSponsorReport',{planId,reportId});expect(absent).toEqual({success:false,error:'This sponsor report was deleted or is unavailable'});}const list=await invoke('listSponsorReports',{planId});expect(list.success).toBe(true);expect(list.entries).toEqual([]);expect(list.nextCursor==null).toBe(true);
  await checkPrefs();await drafts(planId);expect(await getTestState('lz-ppm',{what:'plan',planId})).toEqual(originalPlan);intent('delete-exact-plan');const deletedPlan=await invoke('deletePlan',{planId});expect(deletedPlan.success).toBe(true);expect(deletedPlan.ghostRowRemoved).not.toBe(true);ack('delete-exact-plan',deletedPlan);
  for(let n=0;n<2;n++){const absent=await getTestState('lz-ppm',{what:'plan',planId});record('plan-strong-absence',absent);expect(absent.meta==null).toBe(true);expect(absent.issues).toEqual([]);await registry(originals);}
  await checkPrefs();await proveIssue();intent('delete-exact-issue');const deletedIssue=await rest('DELETE');expect(deletedIssue.status).toBe(204);ack('delete-exact-issue',deletedIssue);for(let n=0;n<2;n++){const absent=await rest('GET');record('issue-absence',absent);expect(absent.status).toBe(404);}
  await source();await drafts(LZPT_PLAN);await checkPrefs();const finalFrame=await openPlans(page);await expect(finalFrame.getByRole('button',{name:/Open plan/})).toHaveCount(3);await expect(finalFrame.locator('.lz-card',{hasText:'LZPT Scenarios'})).toContainText(/45\s*ISSUES/i);await expect(finalFrame.locator('.lz-card',{hasText:'LZPT Scenarios'})).toContainText(/0\s*DRAFTS/i);await settledScreenshot(page,{subject:finalFrame.locator('.lz-card',{hasText:'LZPT Scenarios'}),path:info.outputPath('fourteenth-original-three-restored.png'),fullPage:true});journal.complete=true;save();
 }catch(error){bodyError=error;journal.bodyError=String(error);save();throw error;}
 finally{const errors:any[]=[];for(const [label,action]of [
 ['source',source],['registry',async()=>{const value=await getTestState('lz-ppm',{what:'plans'});record('final-registry',value.plans);if(journal.complete)expect(value.plans.map((p:any)=>p.id).sort()).toEqual(originals);}],
 ['preferences',async()=>{if(ready)for(let n=0;n<2;n++)await checkPrefs();}],['original-drafts',async()=>{if(ready)await drafts(LZPT_PLAN);}]
 ]as const){try{await action();}catch(error){errors.push(error);record('independent-final-audit-error',{label,error:String(error)});}}if(errors.length)journal.complete=false;rpc.stop();save();if(errors.length)throw new AggregateError([...(bodyError?[bodyError]:[]),...errors],'Exact cleanup and independent final audit errors');}
});
