// Deliberately separate old-code prepare and upgraded finish; no implicit cleanup between deployments.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {test,expect} from '../../fixtures/forge';import {getTestState} from '../../testhook/client';import {getHarnessLaunchReceipt} from '../../forge/browser';
import {openPlans,scheduleFields,LZPT_PLAN} from './forecast-fixture';import {actualResponse,currentUserResolver,planning} from './campaign-ui';import {table} from './normalization-owned-fixture';
import {observeReportCapture} from './report-capture';import {holdFirstReportAdvance,awaitHeldReportStep} from './report-capture-held-step';import {observeCaptureProbe,verifyCaptureProbe} from './report-capture-cleanup.mjs';import {settledScreenshot} from './settled-screenshot.mjs';import {legacyPrincipal as packedPrincipal,legacyForecastInput as packedForecastInput} from './report-legacy-upgrade-contract.mjs';
// Stable shared fixture is READ ONLY in every phase; only the new plan may later be removed.
import {get,BASE} from '../../data/jira.mjs';
import {admitPackedFixture,assertOldEncodedLayout} from './report-packed-upgrade-contract.mjs';
import {oldPackedForecast} from '../../tests/report-packed-upgrade/old-producer-frozen.mjs';
const fixturePath=path.resolve('tests/report-packed-upgrade/fixture-read.json'),fixtureBytes=fs.readFileSync(fixturePath);
const fixture=JSON.parse(fixtureBytes.toString());
const originals=[LZPT_PLAN,'plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].sort(),sha=(s:any)=>createHash('sha256').update(s).digest('hex'),prefs={success:true,version:62,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}};
const expectedForecast={state:'available',reason:null,modelVersion:'duration-triangular-fs-v1',runs:300,seed:42,uncertainty:'medium',p50:'2026-10-09',p80:'2026-10-12',p90:'2026-10-12',onPlannedFinish:197/300,coverage:{totalLeaves:1,datedLeaves:1,sampledLeaves:1,missingDates:0,invalidDates:0,invertedDates:0,invalidBaselines:0}};
test.describe.configure({retries:0,timeout:900000});
for(const phase of ['prepare']as const)test(`packed report ${phase}: real old paused encoded job is paused before packed-layout upgrade`,async({page},info)=>{
 expect(process.env.LZ_PACKED_UPGRADE_PHASE).toBe(phase);expect(BASE).toBe('https://wolfaenpak.atlassian.net');expect(sha(fixtureBytes)).toBe('bac0f90bddbe0d6b368564c929e3931044a590113a2250dec04a3e3db6fd5d1a');expect(fixture.first).toEqual(fixture.second);expect(sha(fs.readFileSync(path.resolve('tests/report-packed-upgrade/old-producer-frozen.mjs')))).toBe('e2c4a56b22c133ee1d7a05adf819b214a5351a54beb1bb7e383cb4f5fd8dc8d4');const receipt=getHarnessLaunchReceipt(page.context());if(!receipt||receipt.mode!=='portable-chrome152')throw new Error('Known portable receipt required');expect(receipt).toMatchObject({browserVersion:'152.0.7977.76',principalSha256:packedPrincipal,executableSha256:'755178ee89130a6f1c94cc4ecb2289fe74240db3e7efe9ec69a6cfcd4b93a6ee',frameworkSha256:'bfea9981cc61dfa72d847c920f274e4e96e362954f451198d8ee1650cbefb2e6'});expect(receipt.uiVersion).toBe(process.env.LZ_EXPECTED_UI_VERSION);
 const marker=`lz-packed-${Date.now().toString(36)}`,name=`[harness-test] ${marker}`,summary=fixture.first.fields.summary;const journal:any={phase,marker,name,receipt,deployedForge:process.env.LZ_DEPLOYED_FORGE,deployedApp:process.env.LZ_DEPLOYED_APP,events:[],probes:[],planId:null,issue:{id:'25020',key:'WFH-2820'},jiraWrites:0,completed:false,integrityPreserved:false,expectedForecast};fs.mkdirSync(info.outputDir,{recursive:true});const save=()=>fs.writeFileSync(info.outputPath(`packed-${phase}.json`),JSON.stringify(journal,null,2));const record=(stage:string,value:any={})=>{journal.events.push({stage,time:new Date().toISOString(),value});save();};save();
 if(phase==='prepare'){expect(journal.deployedForge).toBe('6.17.0');expect(journal.deployedApp).toBe('34372ae3f9cb12b1ff94a58dbda313a6deab6f03');}
 const rpc=currentUserResolver(page,c=>c?.functionKey==='getCapacitySettings');let ready=false,session:any,held:any,bodyError:any,originalSource:any,planDeleted=false;
 const readOnlyRpc=new Set(['getCapacitySettings','getDraft','getActiveDrafts','getPlanCalendar','getSponsorReportCapture','listSponsorReports','getBaseline']);
 const invoke=async(key:string,payload:any={})=>{expect(readOnlyRpc.has(key)).toBe(true);const value=await rpc.invoke(key,payload);record(key,value);return value;};const read=async(key:string,payload:any={})=>{const value=await invoke(key,payload);expect(value.success,value.error).toBe(true);return value;};
 const source=async()=>{const s=await getTestState('lz-ppm',{what:'plan',planId:LZPT_PLAN});expect(s.issues).toHaveLength(45);const basis={issues:scheduleFields(s.issues),sources:s.meta.sources,calendarKey:s.meta.calendarKey,holidayYears:s.meta.holidayYears,milestones:s.meta.milestones,protectionEnabled:s.meta.protectionEnabled};expect(sha(JSON.stringify(basis))).toBe('2d5c1ea0d3e742ff61ae47701ab6a391d0cbe6f0238e9415fb73b38e8f21f104');return s;};
 const registry=async(ids:string[])=>{const v=await getTestState('lz-ppm',{what:'plans'});record('registry',v.plans);expect(v.plans.map((p:any)=>p.id).sort()).toEqual(ids);};const drafts=async(planId:string)=>{expect(await read('getDraft',{planId})).toEqual({success:true,draft:null});expect(await read('getActiveDrafts',{planId})).toEqual({success:true,drafts:{}});};
 const issue=async()=>{const v=await get(`/rest/api/3/issue/WFH-2820?fields=${fixture.fields}`);record('retained-issue-readonly',v);admitPackedFixture(v,fixture.first);return v;};
 const ownPlan=async()=>{const v=await getTestState('lz-ppm',{what:'plan',planId:journal.planId});record('owned-plan',v);expect(v.meta).toMatchObject({id:journal.planId,name,createdBy:'harness',calendarKey:'standard'});expect(v.meta.sources).toEqual([{id:'src-0',type:'jql',label:'harness',query:'key = WFH-2820',boardId:null,projectKey:null}]);expect(v.meta.mode).toBeUndefined();expect(v.issues).toHaveLength(1);expect(v.issues[0]).toMatchObject({id:journal.issue.id,key:journal.issue.key,summary,startDate:'2026-10-05',dueDate:'2026-10-09',duration:5});return v;};
 const probe=async(job:any)=>{const v=await observeCaptureProbe(()=>getTestState('lz-ppm',{what:'reportCaptureState',planId:journal.planId,jobId:job.id}),(v:any)=>{journal.probes.push(v);save();});verifyCaptureProbe(v,{planId:journal.planId,jobId:job.id,...job});return v;};
 const pauseHeld=async(report:any)=>{const response=await awaitHeldReportStep(held,180000)as any;expect(response.responseStatus).toBe(200);expect(response.body.success).toBe(true);await report.getByRole('button',{name:'Pause capture',exact:true}).click();held.release();await expect(report.getByRole('button',{name:'Resume capture',exact:true})).toBeVisible();await session.recorder.wait((s:any)=>s.job?.checkpoint===response.body.job.checkpoint,120000);await held.stop();held=null;await session.settle();const count=session.recorder.snapshot().events.filter((e:any)=>e.type==='request'&&e.key==='advanceSponsorReportCapture').length;for(let n=0;n<2;n++)expect((await read('getSponsorReportCapture',{planId:journal.planId,jobId:response.body.job.id})).job).toEqual(response.body.job);await session.settle();expect(session.recorder.snapshot().events.filter((e:any)=>e.type==='request'&&e.key==='advanceSponsorReportCapture').length).toBe(count);record('paused-no-extra-advance',{job:response.body.job,advanceCount:count});return response.body.job;};
 try{
  originalSource=await source();record('original-source',originalSource);await registry(originals);const plans=await openPlans(page);await settledScreenshot(page,{subject:plans.locator('.lz-card',{hasText:'LZPT Scenarios'}),path:info.outputPath(`packed-${phase}-entry.png`),fullPage:true});const pending=actualResponse(page,'getCapacitySettings');await plans.getByRole('button',{name:'Capacity',exact:true}).click();expect(await pending).toEqual(prefs);ready=true;expect(await read('getCapacitySettings')).toEqual(prefs);for(const originalId of originals)await drafts(originalId);
  if(phase==='prepare'){
   expect((await get('/rest/api/3/myself')).accountId).toBe('712020:937bc860-eec2-4294-a65d-8e0fe7c45086');const config=(await getTestState('lz-ppm',{what:'fieldConfig'})).fields;expect(config).toMatchObject({startDate:'customfield_10015',dueDate:'duedate',duration:'customfield_10180'});
   journal.originalIssue=await issue();expect(await issue()).toEqual(journal.originalIssue);record('stable-input-no-jira-writes',{id:'25020',key:'WFH-2820'});const jql='key = WFH-2820';
   record('create-owned-plan-intent',{name,jql});const made=await getTestState('lz-ppm',{what:'createFixture',name,jql});journal.planId=made.planId;save();journal.originalPlan=await ownPlan();const calendarRead=await read('getPlanCalendar',{planId:journal.planId});const {success,...calendar}=calendarRead;journal.calendar=calendar;journal.expectedInput=packedForecastInput(journal.originalPlan,calendar);journal.oldProducerForecast=oldPackedForecast(journal.originalPlan,calendar);expect(journal.oldProducerForecast).toEqual({...expectedForecast,inputHash:journal.expectedInput.inputHash});save();expect(await invoke('getBaseline',{planId:journal.planId})).toEqual({baseline:null});await drafts(journal.planId);await registry([...originals,journal.planId].sort());
   const frame=await table(page,name),work=await planning(frame);await work.getByRole('button',{name:'Sponsor reports',exact:true}).click();const report=work.locator('[data-testid="sponsor-reports"]');await report.getByLabel('Report name',{exact:true}).fill('Unchanged packed upgrade report');session=observeReportCapture(page,journal.planId,info,'packed-prepare');held=await holdFirstReportAdvance(page,journal.planId,(event:any)=>record('held-response',event),(b:any)=>b?.job?.state==='active'&&b.job.stageLabel==='Calculating the forecast');
   await report.getByRole('button',{name:'Capture sponsor report',exact:true}).click();journal.pausedJob=await pauseHeld(report);expect(journal.pausedJob.stageLabel).toBe('Calculating the forecast');expect(session.recorder.snapshot().events.filter((e:any)=>e.type==='request'&&e.key==='advanceSponsorReportCapture').every((e:any)=>e.expectedCheckpoint<journal.pausedJob.checkpoint)).toBe(true);journal.pausedProbe=await probe(journal.pausedJob);assertOldEncodedLayout(journal.pausedProbe,journal.planId,journal.pausedJob.id);expect(journal.pausedProbe.privateArtifacts.every((v:any)=>v.present)).toBe(true);expect(journal.pausedProbe.publicArtifacts).toEqual([]);expect((await read('listSponsorReports',{planId:journal.planId})).entries).toEqual([]);journal.noAdvanceWhilePaused=true;await settledScreenshot(report.locator('[data-testid="report-capture-progress"]'),{path:info.outputPath('packed-old-code-paused.png')});
   expect(await issue()).toEqual(journal.originalIssue);expect(await ownPlan()).toEqual(journal.originalPlan);expect(await invoke('getBaseline',{planId:journal.planId})).toEqual({baseline:null});journal.completed=true;record('prepared-retained-for-upgrade',{planId:journal.planId,issue:journal.issue,job:journal.pausedJob});

  }
 }catch(error){bodyError=error;record('body-error',String(error));throw error;}
 finally{
  const errors:any[]=[];const attempt=async(label:string,fn:()=>Promise<any>)=>{try{await fn();}catch(error){errors.push(error);record('independent-error',{label,error:String(error)});}};
  await attempt('stop-owned-ui',async()=>{if(!page.isClosed())await page.goto('about:blank');});if(held)await attempt('release-held-response',()=>held.stop());if(session)session.stop();
  await attempt('original-source',async()=>{if(originalSource)expect(await source()).toEqual(originalSource);});await attempt('registry',()=>registry(journal.planId&&!planDeleted?[...originals,journal.planId].sort():originals));
  await attempt('retained-issue-unchanged',async()=>{for(let n=0;n<2;n++)expect(await issue()).toEqual(journal.originalIssue||fixture.first);});await attempt('preferences',async()=>{if(ready)for(let n=0;n<2;n++)expect(await read('getCapacitySettings')).toEqual(prefs);});await attempt('original-drafts',async()=>{if(ready)for(const originalId of originals)await drafts(originalId);});
  await attempt('owned-source-final',async()=>{if(journal.originalPlan)expect(await ownPlan()).toEqual(journal.originalPlan);});
  await attempt('paused-receipt-final',async()=>{if(phase==='prepare'&&journal.pausedJob){for(let n=0;n<2;n++)expect((await read('getSponsorReportCapture',{planId:journal.planId,jobId:journal.pausedJob.id})).job).toEqual(journal.pausedJob);expect(await probe(journal.pausedJob)).toEqual(journal.pausedProbe);record('paused-receipt-after-ui-stop',{job:journal.pausedJob});}});
  journal.integrityPreserved=ready&&errors.length===0;journal.resources={planRetained:!!journal.planId&&!planDeleted,issueRetained:true};if(errors.length)journal.completed=false;save();rpc.stop();if(errors.length)throw new AggregateError([...(bodyError?[bodyError]:[]),...errors],'Packed upgrade preparation and independent audits failed; exact owned resources retained');
 }
});
