// Read first; cancel only the exact old paused job, delete its exact plan, retain its Jira issue untouched.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {test,expect} from '../../fixtures/forge';import {getTestState} from '../../testhook/client';import {getHarnessLaunchReceipt} from '../../forge/browser';
import {openPlans,scheduleFields,LZPT_PLAN} from './forecast-fixture';import {actualResponse,currentUserResolver} from './campaign-ui';import {cleanReportCapture,observeCaptureProbe,verifyCaptureProbe} from './report-capture-cleanup.mjs';import {settledScreenshot} from './settled-screenshot.mjs';import {legacyPrincipal} from './report-legacy-upgrade-contract.mjs';import {get,BASE} from '../../data/jira.mjs';
const planId='plan-test-mtpemgwx-gwhiv5',jobId='c4d0513b-77cf-4f15-98cd-7e4c51cb8a5a',issueKey='WFH-2935',issueId='25167',originals=[LZPT_PLAN,'plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].sort();
const sha=(bytes:any)=>createHash('sha256').update(bytes).digest('hex'),prefs={success:true,version:59,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}};
const load=(folder:string,file:string,hash:string)=>{const bytes=fs.readFileSync(path.resolve(`evidence/lz-campaign/${folder}/artifacts/${file}`));expect(sha(bytes)).toBe(hash);return JSON.parse(bytes.toString());};
test.describe.configure({retries:0,timeout:300000});
test('legacy drift recovery: exact cancelled job and plan absent while acknowledged owned Jira issue is retained unchanged',async({page},info)=>{
 expect(process.env.LZ_DEPLOYED_FORGE).toBe('6.15.0');expect(process.env.LZ_DEPLOYED_APP).toBe('e8d46785d8cda3d2b3680b0e84e52dbd7c1a68ee');
 const prepared=load('sixteenth-legacy-prepare-20260906','scenarios-lz-ppm-campaign--1a7ae-report-across-codec-upgrade-chromium/legacy-prepare.json','2be700183292667acdb21323bd8546c99b6b6e187681fd8662728d63d5d8eeaf');const failed=load('sixteenth-legacy-finish-20260906','scenarios-lz-ppm-campaign--dc1f4-report-across-codec-upgrade-chromium/legacy-finish.json','32d8b532c0869ffe9af943d7d42af0f7f0a27b44f56c3ae933efe68425328411');
 expect(prepared).toMatchObject({completed:true,integrityPreserved:true,planId,issue:{id:issueId,key:issueKey}});expect(failed).toMatchObject({completed:false,integrityPreserved:true,planId});const currentPlan=failed.events.find((e:any)=>e.stage==='owned-plan').value;expect(currentPlan.meta).toMatchObject({id:planId,createdBy:'harness',version:3,updatedAt:'2026-09-06T06:02:51.817Z'});expect(currentPlan.issues).toEqual(prepared.originalPlan.issues);expect(prepared.pausedJob.id).toBe(jobId);
 const receipt=getHarnessLaunchReceipt(page.context());if(!receipt||receipt.mode!=='portable-chrome152')throw Error('Known portable receipt required');expect(receipt).toMatchObject({browserVersion:'152.0.7977.76',principalSha256:legacyPrincipal,uiVersion:process.env.LZ_EXPECTED_UI_VERSION,executableSha256:'755178ee89130a6f1c94cc4ecb2289fe74240db3e7efe9ec69a6cfcd4b93a6ee',frameworkSha256:'bfea9981cc61dfa72d847c920f274e4e96e362954f451198d8ee1650cbefb2e6'});expect(BASE).toBe('https://wolfaenpak.atlassian.net');
 const journal:any={phase:'recover',receipt,deployedForge:process.env.LZ_DEPLOYED_FORGE,deployedApp:process.env.LZ_DEPLOYED_APP,originalPrepare:prepared,currentPlan,events:[],completed:false,integrityPreserved:false,oldPlanDeleted:false,issueRetained:true};const save=()=>fs.writeFileSync(info.outputPath('legacy-recovery.json'),JSON.stringify(journal,null,2));const record=(stage:string,value:any)=>{journal.events.push({stage,time:new Date().toISOString(),value});save();};save();
 const rpc=currentUserResolver(page,c=>c?.functionKey==='getCapacitySettings');let ready=false,bodyError:any;const invoke=async(key:string,payload:any={})=>{const value=await rpc.invoke(key,payload);record(key,value);return value;};const read=async(key:string,payload:any={})=>{const value=await invoke(key,payload);expect(value.success,value.error).toBe(true);return value;};
 const source=async()=>{const v=await getTestState('lz-ppm',{what:'plan',planId:LZPT_PLAN});record('original-source',v);expect(v).toEqual(prepared.events.find((e:any)=>e.stage==='original-source').value);const basis={issues:scheduleFields(v.issues),sources:v.meta.sources,calendarKey:v.meta.calendarKey,holidayYears:v.meta.holidayYears,milestones:v.meta.milestones,protectionEnabled:v.meta.protectionEnabled};expect(sha(JSON.stringify(basis))).toBe('2d5c1ea0d3e742ff61ae47701ab6a391d0cbe6f0238e9415fb73b38e8f21f104');};
 const registry=async()=>{const v=await getTestState('lz-ppm',{what:'plans'});record('registry',v.plans);expect(v.plans.map((v:any)=>v.id).sort()).toEqual(journal.oldPlanDeleted?originals:[...originals,planId].sort());};
 const issue=async()=>{const value=await get(`/rest/api/3/issue/${issueKey}?fields=project,issuetype,labels,summary,customfield_10015,duedate,customfield_10180`);record('owned-issue-read-only',value);expect(value).toEqual(prepared.originalIssue);};const drafts=async(id:string)=>{expect(await read('getDraft',{planId:id})).toEqual({success:true,draft:null});expect(await read('getActiveDrafts',{planId:id})).toEqual({success:true,drafts:{}});};
 const probe=()=>observeCaptureProbe(()=>getTestState('lz-ppm',{what:'reportCaptureState',planId,jobId}),(v:any)=>record('physical-probe',v));
 try{
  expect((await get('/rest/api/3/myself')).accountId).toBe('712020:937bc860-eec2-4294-a65d-8e0fe7c45086');await source();await registry();await issue();expect(await getTestState('lz-ppm',{what:'plan',planId})).toEqual(currentPlan);
  const frame=await openPlans(page);await settledScreenshot(page,{subject:frame.locator('.lz-card',{hasText:'LZPT Scenarios'}),path:info.outputPath('legacy-recovery-entry.png'),fullPage:true});const pending=actualResponse(page,'getCapacitySettings');await frame.getByRole('button',{name:'Capacity',exact:true}).click();expect(await pending).toEqual(prefs);ready=true;expect(await read('getCapacitySettings')).toEqual(prefs);for(const id of[...originals,planId])await drafts(id);expect(await read('getLockStatus',{planId})).toMatchObject({locked:false});
  for(let n=0;n<2;n++)expect((await read('getSponsorReportCapture',{planId,jobId})).job).toEqual(prepared.pausedJob);const before=await probe();verifyCaptureProbe(before,{planId,jobId,...prepared.pausedJob});expect(before).toEqual(prepared.pausedProbe);expect((await read('listSponsorReports',{planId})).entries).toEqual([]);await page.goto('about:blank');
  record('cancel-owned-stale-job-intent',{planId,jobId,requestId:prepared.pausedJob.requestId});const clean:any=await cleanReportCapture({planId,jobId,requestId:prepared.pausedJob.requestId,invoke,probe:async()=>probe(),onState:(v:any)=>record('cleanup-checkpoint',v)});expect(clean.cleaned).toBe(true);expect(clean.job).toMatchObject({state:'cancelled',cleanupDone:true});verifyCaptureProbe(clean.probes.at(-1),{planId,jobId,...clean.job},before);journal.cleaned=clean;save();expect((await read('listSponsorReports',{planId})).entries).toEqual([]);
  expect(await getTestState('lz-ppm',{what:'plan',planId})).toEqual(currentPlan);await issue();await drafts(planId);expect(await read('getCapacitySettings')).toEqual(prefs);record('delete-owned-plan-intent',{planId});const removed=await read('deletePlan',{planId});expect(removed.ghostRowRemoved).not.toBe(true);journal.oldPlanDeleted=true;save();for(let n=0;n<2;n++){const absent=await getTestState('lz-ppm',{what:'plan',planId});record('plan-strong-absence',absent);expect(absent.meta==null).toBe(true);expect(absent.issues).toEqual([]);await registry();await issue();}
  const final=await openPlans(page);await expect(final.getByRole('button',{name:/Open plan/})).toHaveCount(3);await settledScreenshot(page,{subject:final.locator('.lz-card',{hasText:'LZPT Scenarios'}),path:info.outputPath('legacy-old-plan-removed-issue-retained.png'),fullPage:true});journal.completed=true;save();
 }catch(error){bodyError=error;record('body-error',String(error));throw error;}
 finally{const errors:any[]=[];for(const[label,fn]of[['source',source],['registry',registry],['issue-retained',issue],['preferences',async()=>{if(ready)for(let n=0;n<2;n++)expect(await read('getCapacitySettings')).toEqual(prefs);}],['drafts',async()=>{if(ready)for(const id of originals)await drafts(id);}]]as const){try{await fn();}catch(error){errors.push(error);record('independent-error',{label,error:String(error)});}}journal.integrityPreserved=ready&&errors.length===0;if(errors.length)journal.completed=false;save();rpc.stop();if(errors.length)throw new AggregateError([...(bodyError?[bodyError]:[]),...errors],'Legacy recovery and independent audit failed; remaining exact resources retained');}
});
