// Exact retained same-job continuation. Only acknowledged advances; report/resources retained for root inspection.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {test,expect as baseExpect} from '../../fixtures/forge';import {loadEnv} from '../../data/env.mjs';import {getHarnessLaunchReceipt} from '../../forge/browser';
import {scheduleFields,LZPT_PLAN} from './forecast-fixture';import {callEnvelope} from './campaign-ui';import {replayHeaders} from './replay-headers.mjs';
import {observeCaptureProbe,verifyCaptureProbe} from './report-capture-cleanup.mjs';import {retained,checkedJob} from './seventeenth-report-recovery-contract.mjs';
import {admitSource,verifySourceResult} from './seventeenth-source-contract.mjs';
import {sourceOracle,hash as canonicalHash} from './seventeenth-source-oracle.mjs';
import {admitForecastResume,preservedArtifacts,uiRequestClass} from './seventeenth-forecast-resume-contract.mjs';
import {pinnedForecast,verifyPublished,verifyReportPage,expectedHtml} from './seventeenth-forecast-report-oracle.mjs';
import {getTarget} from '../../config/targets';import {assertLoggedIn} from '../../forge/browser';import {enterForgeSurface} from '../../forge/frame';import {settledScreenshot,waitForAppReady} from './settled-screenshot.mjs';import {pathToFileURL} from 'node:url';
import {get,BASE} from '../../data/jira.mjs';import {admitPackedFixture} from './report-packed-upgrade-contract.mjs';

import {createRollingReadBudget} from './rolling-read-budget.mjs';
import {continueUntilFinished} from './paced-ui-transport.mjs';
import {boundedRead} from './paced-read-transport.mjs';
import {resolverReadCost,hookReadCost,advanceReadCost} from './seventeenth-read-cost.mjs';
import {admitPacedResume} from './seventeenth-paced-resume-contract.mjs';
import {admitAggregateResume,continueAggregateReport} from './seventeenth-aggregate-resume-contract.mjs';
const expect=baseExpect.configure({timeout:600000});
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
// These local UI helpers preserve the original surface/semantic gates with an explicit ten-minute queue allowance.
async function openPlans(page:any){await page.setViewportSize({width:1600,height:1100});await assertLoggedIn(page);const target=getTarget('lz-ppm-dashboard');await page.goto(target.deepLink(target.envId)!,{waitUntil:'domcontentloaded'});await page.locator('iframe[data-testid="hosted-resources-iframe"], iframe[title*="Iframe"]').first().waitFor({state:'attached',timeout:600000});const surface=await enterForgeSurface(page,{surface:'custom',timeout:600000});if(surface.kind!=='custom')throw new Error('No Forge frame');await surface.frame.getByText('LZPT Scenarios',{exact:true}).first().waitFor({timeout:600000});return surface.frame;}
async function openPlan(page:any,name:string){const frame=await openPlans(page);await frame.getByText(name,{exact:true}).first().click();await frame.getByRole('button',{name:/^Dashboard/i}).first().waitFor({timeout:600000});return frame;}
async function planning(frame:any){await frame.getByRole('button',{name:/^Planning/i}).first().click();await expect(frame.locator('[data-testid="tab-loading-overlay"]')).toHaveCount(0);const workspace=frame.locator('[data-testid="planning-workspace"]');await waitForAppReady(workspace,{timeout:600000});return workspace;}
function actualResponse(page:any,key:string,planId?:string){return page.waitForResponse((r:any)=>{const c=callEnvelope(r.request())?.variables?.input?.payload?.call;return c?.functionKey===key&&(!planId||c.payload?.planId===planId);},{timeout:600000}).then(async(r:any)=>{expect(r.status()).toBe(200);await r.finished();const data=await r.json(),body=data.data?.invokeExtension?.response?.body;expect(data.data?.invokeExtension?.success).toBe(true);expect(body?.success,body?.error).toBe(true);return body;});}

const {planId,jobId,reportId,requestId,snapshotId,name}=retained;
const originals=[LZPT_PLAN,'plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].sort(),ownedRegistry=[...originals,planId].sort();
const archived=path.resolve('evidence/lz-campaign/seventeenth-packed-report-live-20260906/large-history-report-live/attempt-001/tests-artifacts/scenarios-lz-ppm-journey-c-2f98e-without-mutating-the-source-chromium');
const sha=(value:any)=>createHash('sha256').update(value).digest('hex');
const canonical=(x:any):any=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x;
const fields=(rows:any[])=>rows.map(i=>({key:i.key,id:i.id,summary:i.summary,statusCategory:i.statusCategory??'unknown',startDate:i.startDate??null,dueDate:i.dueDate??null,duration:i.duration??null,buffer:i.buffer||'No',parentKey:i.parentKey??null,predecessors:[...(i.predecessors||[])].sort(),successors:[...(i.successors||[])].sort()})).sort((a,b)=>a.key.localeCompare(b.key));
const expectedPrefs={success:true,version:65,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}};
test.describe.configure({retries:0,timeout:10800000});
test('seventeenth aggregate resume: same retained5300 job completes exact40-run report and HTML without cleanup',async({page},info)=>{
 expect(process.env.LZ_SEVENTEENTH_AGGREGATE_PHASE).toBe('resume127');
 expect(BASE).toBe('https://wolfaenpak.atlassian.net');const fixtureBytes=fs.readFileSync(path.resolve('tests/report-packed-upgrade/fixture-read.json'));expect(sha(fixtureBytes)).toBe('bac0f90bddbe0d6b368564c929e3931044a590113a2250dec04a3e3db6fd5d1a');const fixture=JSON.parse(fixtureBytes.toString());expect(fixture.first).toEqual(fixture.second);
 const previousPath=path.resolve('evidence/lz-campaign/seventeenth-retained-analysis-diagnostic-20260906/artifacts/scenarios-lz-ppm-campaign--8294a-pendent-integrity-preserved-chromium/seventeenth-advance.json');const previousBytes=fs.readFileSync(previousPath),previous=JSON.parse(previousBytes.toString());const latestPath=path.resolve('evidence/lz-campaign/seventeenth-context-first-diagnostic-20260906/artifacts/scenarios-lz-ppm-campaign--bc021-pendent-integrity-preserved-chromium/seventeenth-context-first-advance.json');const latestBytes=fs.readFileSync(latestPath),latest=JSON.parse(latestBytes.toString());const preludePath=path.resolve('evidence/lz-campaign/seventeenth-prelude-diagnostic-20260906/artifacts/scenarios-lz-ppm-campaign--0a513-pendent-integrity-preserved-chromium/seventeenth-prelude-advance.json');const preludeBytes=fs.readFileSync(preludePath),prelude=JSON.parse(preludeBytes.toString());const forensicPath=path.resolve('evidence/lz-campaign/seventeenth-forensic-readonly-20260906/artifacts/scenarios-lz-ppm-campaign--bce08-eserve-exact-retained-state-chromium/seventeenth-forensic.json');const forensicBytes=fs.readFileSync(forensicPath),forensic=JSON.parse(forensicBytes.toString());const previousSource=admitSource(forensic,sha(forensicBytes),prelude,sha(preludeBytes),latest,sha(latestBytes),previous,sha(previousBytes),Date.now());
 const sourcePath=path.resolve('evidence/lz-campaign/seventeenth-source-return-readonly-20260906/artifacts/scenarios-lz-ppm-campaign--755d0-eserve-exact-retained-state-chromium/seventeenth-source.json'),sourceBytes=fs.readFileSync(sourcePath),sourceReceipt=JSON.parse(sourceBytes.toString()),previousAdmitted=admitForecastResume(sourceReceipt,sha(sourceBytes),previousSource);
 const failedPath=path.resolve('evidence/lz-campaign/seventeenth-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--f695f-rt-and-HTML-without-cleanup-chromium/seventeenth-forecast-resume.json'),failedBytes=fs.readFileSync(failedPath),failedReceipt=JSON.parse(failedBytes.toString());const recoveryPath=path.resolve('evidence/lz-campaign/seventeenth-quota-readonly-admission-20260906/receipt.json'),recoveryBytes=fs.readFileSync(recoveryPath),recoveryReceipt=JSON.parse(recoveryBytes.toString());const previousRecovery=admitPacedResume(failedReceipt,sha(failedBytes),recoveryReceipt,sha(recoveryBytes),previousAdmitted);
 const pacedFailurePath=path.resolve('evidence/lz-campaign/seventeenth-paced-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--6c70d-rt-and-HTML-without-cleanup-chromium/seventeenth-paced-resume.json'),pacedFailureBytes=fs.readFileSync(pacedFailurePath),pacedFailure=JSON.parse(pacedFailureBytes.toString());const recovered=admitAggregateResume(pacedFailure,sha(pacedFailureBytes),previousRecovery);
 const originalBytes=fs.readFileSync(path.join(archived,'large-history-journal.json'));expect(sha(originalBytes)).toBe('3b47f1e7f32779ebf2ad9671d09aaded34e6052e2236e875e43166bcbb296617');const original=JSON.parse(originalBytes.toString());
 const rawBytes=fs.readFileSync(path.join(archived,'large-capture-raw-expected.json'));expect(sha(rawBytes)).toBe('30117abfe6ad551e6c5a8d8ceb4d8622e43e51258af8659026b8d25ca1641709');const expectedRows=JSON.parse(rawBytes.toString());expect(expectedRows).toHaveLength(5300);
 const protocolBytes=fs.readFileSync(path.join(archived,'report-capture-protocol.json'));expect(sha(protocolBytes)).toBe('556e97bad26581731a88d2098c0f178e00808bfcb03ee4aee5099945d8cd7211');const initialJob=JSON.parse(protocolBytes.toString()).job;checkedJob(initialJob);expect(initialJob).toMatchObject({checkpoint:78,state:'active',cleanupDone:false});
 const receipt=getHarnessLaunchReceipt(page.context());if(!receipt||receipt.mode!=='portable-chrome152')throw new Error('Known portable Chrome152 receipt required');expect(receipt).toMatchObject({mode:'portable-chrome152',browserVersion:'152.0.7977.76',principalSha256:'b4cb5211a5e4d44c9f3a6bc909588c2fe62162358d4b0c04da52aa6977433769',executableSha256:'755178ee89130a6f1c94cc4ecb2289fe74240db3e7efe9ec69a6cfcd4b93a6ee',frameworkSha256:'bfea9981cc61dfa72d847c920f274e4e96e362954f451198d8ee1650cbefb2e6'});expect(receipt!.uiVersion).toBe(process.env.LZ_EXPECTED_UI_VERSION);
 const journal:any={phase:"paced-resume127",pacedFailureReceipt:{path:pacedFailurePath,sha256:sha(pacedFailureBytes)},failedReceipt:{path:failedPath,sha256:sha(failedBytes)},quotaAdmission:{path:recoveryPath,sha256:sha(recoveryBytes)},budgetEvents:[],uiRequests:[],sourceReceipt:{path:sourcePath,sha256:sha(sourceBytes)},retained,receipt,forensicDiagnostic:{path:forensicPath,sha256:sha(forensicBytes)},preludeDiagnostic:{path:preludePath,sha256:sha(preludeBytes)},previousDiagnostic:{path:latestPath,sha256:sha(latestBytes)},olderDiagnostic:{path:previousPath,sha256:sha(previousBytes)},events:[],probes:[],advanceCalls:0,publicationObserved:false,sourceAndPreferencesPreserved:false,completed:false};fs.mkdirSync(info.outputDir,{recursive:true});const save=()=>fs.writeFileSync(info.outputPath('seventeenth-aggregate-resume.json'),JSON.stringify(journal,null,2));const record=(stage:string,value:any={})=>{journal.events.push({stage,time:new Date().toISOString(),value});save();};save();
 const budget=createRollingReadBudget({capacity:3000,windowMs:61000,onEvent:(event:any)=>{journal.budgetEvents.push(event);save();}});page.setDefaultTimeout(600000);page.setDefaultNavigationTimeout(600000);loadEnv();
 let wire:any,ready=false,bodyError:any,bodyFailed=false,originalSource:any,originalOwned:any,planDeleted=false,admittedProbe:any,publishedProbe:any,latestVerifiedProbe:any;
 const capture=(req:any)=>{const envelope=callEnvelope(req);if(envelope?.variables?.input?.payload?.call?.functionKey==='getCapacitySettings')wire={url:req.url(),data:envelope,headers:req.allHeaders()};};page.on('request',capture);
 const forbiddenUi:any[]=[],uiRouteErrors:any[]=[],uiPending=new Set<Promise<any>>();let uiCount=0;const blockUiWrites=async(route:any)=>{const call=callEnvelope(route.request())?.variables?.input?.payload?.call,classification=uiRequestClass(call);if(classification==='forbidden'){forbiddenUi.push(call);record('forbidden-ui-write-blocked',call);await route.abort('blockedbyclient');return;}if(classification==='owned-presence')record('owned-ui-presence',call);if(classification==='unrelated'){await route.continue();return;}const requestId=++uiCount;const work=Promise.resolve().then(()=>budget.run(`ui:${requestId}:${call.functionKey}`,resolverReadCost(call.functionKey),()=>continueUntilFinished(page,route,{onObserved:async(result:any)=>{const observed:any={requestId,key:call.functionKey,...result};if(result.state==='finished'){const response=await route.request().response();observed.httpStatus=response?.status()??null;observed.raw=response?await response.text():null;observed.responseBytes=observed.raw?Buffer.byteLength(observed.raw):0;observed.responseSha256=observed.raw?sha(observed.raw):null;let data:any;try{data=JSON.parse(observed.raw);}catch{data=null;}const extension=data?.data?.invokeExtension;observed.outerSuccess=extension?.success??null;observed.body=extension?.response?.body??null;observed.errors=extension?.errors??data?.errors??null;if(observed.httpStatus!==200||observed.outerSuccess!==true||observed.errors?.length||observed.body?.success===false||observed.responseBytes>8388608)uiRouteErrors.push(`${call.functionKey}: unsuccessful actual UI response`);}else uiRouteErrors.push(`${call.functionKey}: ${result.error}`);journal.uiRequests.push(observed);save();}})));uiPending.add(work);try{await work;}catch(error){uiRouteErrors.push(String(error));record('ui-budget-or-transport-error',{requestId,error:String(error)});await route.abort('failed').catch(()=>{});}finally{uiPending.delete(work);}};await page.route('**/*',blockUiWrites);
 const drainUi=async()=>{const deadline=performance.now()+600000;while(uiPending.size){expect(performance.now()<deadline,'bounded UI queue drain').toBe(true);await Promise.race([Promise.allSettled([...uiPending]),sleep(1000)]);}};
 const stopUi=async()=>{await drainUi();await page.goto('about:blank');await drainUi();};
 const hook=async(query:any)=>budget.run(`hook:${query.what}:${query.planId??'registry'}`,hookReadCost(query),async()=>{const url=new URL(process.env.LZ_PPM_TESTHOOK_URL!);expect(url.protocol).toBe('https:');for(const[k,v]of Object.entries(query))url.searchParams.set(k,String(v));const startedMs=Date.now(),value=await boundedRead(url,{headers:{Authorization:`Bearer ${process.env.HARNESS_SECRET}`}});record('hook-response',{query,startedMs,returnedMs:Date.now(),...value,responseSha256:sha(value.raw)});expect(value.httpStatus).toBe(200);expect(value.body).toBeTruthy();return value.body;});
 const allowed=new Set(['getCapacitySettings','getDraft','getActiveDrafts','getLockStatus','getSponsorReportCapture','getSnapshot','getBaseline','listSponsorReports','getSponsorReport','getSponsorReportPage','advanceSponsorReportCapture']);
 const rawInvoke=async(key:string,payload:any={},cost=resolverReadCost(key))=>budget.run(`rpc:${key}`,cost,async()=>{
  expect(allowed.has(key)).toBe(true);expect(wire).toBeTruthy();
  const envelope=structuredClone(wire.data);envelope.variables.input.payload.call={functionKey:key,payload};
  const startedMs=Date.now();if(key==='advanceSponsorReportCapture'){journal.advanceCalls++;journal.lastWriteStartedMs=startedMs;record('actual-advance-dispatch',{payload,reservedUnits:cost,startedMs});console.log('PACED_ADVANCE',JSON.stringify({checkpoint:payload.expectedCheckpoint,startedAt:new Date(startedMs).toISOString(),reservedUnits:cost}));}try{const response=await page.request.post(wire.url,{headers:replayHeaders(await wire.headers),data:JSON.stringify(envelope),maxRetries:0,maxRedirects:0,timeout:60000});const text=await response.text();let data:any;try{data=JSON.parse(text);}catch{data=null;}
   const returnedMs=Date.now(),extension=data?.data?.invokeExtension;const observed={startedMs,returnedMs,elapsedMs:returnedMs-startedMs,...(key==='advanceSponsorReportCapture'?{raw:text,responseBytes:Buffer.byteLength(text),responseSha256:sha(text)}:{}),httpStatus:response.status(),outerSuccess:extension?.success??null,body:extension?.response?.body??null,errors:extension?.errors??data?.errors??null,...(!data?{nonJson:{bytes:Buffer.byteLength(text),sha256:sha(text)}}:{}),traceId:response.headers()['atl-traceid']??null};record(key,observed);return observed;
  }catch(error){record('transport-error',{key,message:String(error)});throw error;}finally{if(key==='advanceSponsorReportCapture'){journal.lastWriteReturnedMs=Date.now();save();}}
 });
 const invoke=async(key:string,payload:any={})=>{const result=await rawInvoke(key,payload);expect(result.httpStatus).toBe(200);expect(result.outerSuccess).toBe(true);expect(result.body).toBeTruthy();return result.body;};
 const read=async(key:string,payload:any={})=>{const value=await invoke(key,payload);expect(value.success,value.error).toBe(true);return value;};
 const registry=async(ids:string[])=>{const value=await hook({what:'plans'});record('registry',value.plans);expect(value.plans.map((p:any)=>p.id).sort()).toEqual(ids);};
 const source=async()=>{const s=await hook({what:'plan',planId:LZPT_PLAN});const basis={issues:scheduleFields(s.issues),sources:s.meta.sources,calendarKey:s.meta.calendarKey,holidayYears:s.meta.holidayYears,milestones:s.meta.milestones,protectionEnabled:s.meta.protectionEnabled};expect(s.issues).toHaveLength(45);expect(sha(JSON.stringify(basis))).toBe('2d5c1ea0d3e742ff61ae47701ab6a391d0cbe6f0238e9415fb73b38e8f21f104');return s;};
 const owned=async()=>{const value=await hook({what:'plan',planId});record('owned-plan',value);expect(value.meta).toMatchObject({id:planId,name,createdBy:'harness',calendarKey:'standard',sources:[{id:'src-0',type:'jql',label:'harness',query:'project = LZPP ORDER BY key ASC',boardId:null,projectKey:null}]});expect(value.meta.mode).toBeUndefined();expect(fields(value.issues)).toEqual(expectedRows);return value;};
 const snapshot=async()=>{const value=(await read('getSnapshot',{planId,snapshotId})).snapshot;expect(value).toMatchObject({id:snapshotId,hash:original.snapshot.hash,issueCount:5300,workingChangeCount:0});expect(value.mode).toBeUndefined();expect(value.calendar.workingDays).toEqual([1,2,3,4,5]);expect(value.calendar.holidays).toEqual([]);expect(fields(value.issues)).toEqual(expectedRows);expect(value).toEqual(sourceReceipt.events.find((e:any)=>e.stage==='getSnapshot').value.body.snapshot);return value;};
 const baseline=async()=>{expect(await invoke('getBaseline',{planId})).toEqual({baseline:null});};
 const drafts=async(id:string)=>{expect(await read('getDraft',{planId:id})).toEqual({success:true,draft:null});expect(await read('getActiveDrafts',{planId:id})).toEqual({success:true,drafts:{}});};
 const probe=async()=>observeCaptureProbe(()=>hook({what:'reportCaptureState',planId,jobId}),(v:any)=>{journal.probes.push(v);save();});
 const sharedIssue=async()=>{const value=await get(`/rest/api/3/issue/WFH-2820?fields=${fixture.fields}`);record('shared-issue-readonly',value);admitPackedFixture(value,fixture.first);return value;};

 try{
  await stopUi();expect(page.context().pages()).toEqual([page]);expect(page.frames().length).toBe(1);record('bootstrap-quiet-start',{bootstrapReceipt:receipt.admittedAt,outstandingAllowanceMs:30000,rollingWindowMs:61000});const quietRequests=uiCount;await budget.run('bootstrap-outstanding-allowance',3000,()=>sleep(30000));await budget.run('bootstrap-window-cleared',1,async()=>{});expect(uiCount).toBe(quietRequests);record('bootstrap-quiet-complete',{elapsedBoundMs:91000,budgetBegins:true});
  expect((await get('/rest/api/3/myself')).accountId).toBe('712020:937bc860-eec2-4294-a65d-8e0fe7c45086');expect(await sharedIssue()).toEqual(await sharedIssue());
  originalSource=await source();expect(originalSource).toEqual(sourceReceipt.events.find((e:any)=>e.stage==='original-source').value);record('original-source',originalSource);await registry(ownedRegistry);originalOwned=await owned();
  const frame=await openPlans(page),pending=actualResponse(page,'getCapacitySettings');await frame.getByRole('button',{name:'Capacity',exact:true}).click();expect(await pending).toEqual(expectedPrefs);ready=true;expect(await read('getCapacitySettings')).toEqual(expectedPrefs);for(const id of originals)await drafts(id);await drafts(planId);await baseline();expect(await read('getLockStatus',{planId})).toMatchObject({locked:false});const originalSnapshot=await snapshot();record('snapshot-hash-and-full-fields',{id:snapshotId,hash:originalSnapshot.hash,count:5300});
  let job=checkedJob((await read('getSponsorReportCapture',{planId,jobId})).job);const before=await probe();admittedProbe=before;verifyCaptureProbe(before,{planId,jobId,...job});
  expect(job).toEqual(recovered.job);expect(before).toEqual(recovered.probe);preservedArtifacts(before,job,previousAdmitted.probe);expect(before.privateArtifacts).toHaveLength(183);expect(before.publicArtifacts).toEqual([]);expect((await read('listSponsorReports',{planId})).entries).toEqual([]);
  await stopUi();
  const contextKeyHash=sha(JSON.stringify(`p:${planId}:report-jobs:data:${jobId}:source-context`));const contextArtifact=before.privateArtifacts.find((a:any)=>a.keyHash===contextKeyHash);expect(contextArtifact).toBeTruthy();expect(contextArtifact.present).toBe(true);const metaHash=sha(JSON.stringify(canonical(originalOwned.meta)));
  const payloadBytes=fs.readFileSync(path.resolve('tests/seventeenth-source-return/capture-payload.json'));expect(sha(payloadBytes)).toBe('08f3c91aad50cf4f6b36a03439b14b2eb98e90704d6f28097f0f0e8a856cabe4');const payload=JSON.parse(payloadBytes.toString()).payload;expect(sha(JSON.stringify(payload))).toBe(JSON.parse(protocolBytes.toString()).begin.inputHash);
  const pinnedPlan=forensic.events.find((e:any)=>e.stage==='owned-plan').value,pinnedSnapshot=forensic.events.find((e:any)=>e.stage==='getSnapshot').value.body.snapshot;expect(originalOwned).toEqual(pinnedPlan);const oracle=sourceOracle(pinnedPlan,pinnedSnapshot.calendar,payload,contextArtifact.expectedHash);expect(oracle.source.basisHash).toBe(pinnedSnapshot.consistency.basisHash);journal.expectedSource=oracle.source;save();const oldContext=forensic.events.find((e:any)=>e.stage==='forensic-verified'&&e.value.mode==='context').value;expect(oldContext.metaHashBefore).toBe(metaHash);
  const forecast=pinnedForecast();expect(forecast.sourceHashes).toEqual(oracle.source);journal.expectedForecast=forecast;const resumeStartedMs=Date.now();journal.resumeStartedMs=resumeStartedMs;save();
  latestVerifiedProbe=before;job=await continueAggregateReport({initial:job,progress:recovered.progress,advance:async(payload:any,priorJob:any)=>{expect(uiRouteErrors).toEqual([]);return rawInvoke('advanceSponsorReportCapture',payload,advanceReadCost(priorJob));},status:async()=>checkedJob((await read('getSponsorReportCapture',{planId,jobId})).job),probe:async(current:any)=>{journal.finalJob=current;save();const observed=await probe();journal.finalProbe=observed;save();preservedArtifacts(observed,current,latestVerifiedProbe);latestVerifiedProbe=observed;},onObserved:(value:any)=>record('continuation',value)});
  journal.finalJob=job;journal.publicationObserved=true;publishedProbe=structuredClone(journal.finalProbe);save();
  const summary=(await read('getSponsorReport',{planId,reportId})).report;journal.report=summary;save();const graded=verifyPublished(summary,{oracle,forecast,initialJob,resumeStartedMs});expect((await read('listSponsorReports',{planId})).entries.map((r:any)=>r.id)).toEqual([reportId]);
  const pages:any[]=[];for(let n=0;n<106;n++){const part=(await read('getSponsorReportPage',{planId,reportId,section:'timeline',page:n})).page;verifyReportPage(part,summary,n,graded.rows);pages.push(part);}journal.pages=pages;journal.all5300ReportFieldsVerified=true;save();
  const pf=await openPlan(page,name),work=await planning(pf);await work.getByRole('button',{name:'Sponsor reports',exact:true}).click();const report=work.locator('[data-testid="sponsor-reports"]'),pendingReport=actualResponse(page,'getSponsorReport',planId);await report.getByRole('navigation',{name:'Retained sponsor reports'}).getByRole('button').filter({hasText:'Every existing performance row'}).click();expect((await pendingReport).report).toEqual(summary);
  const forecastText='P50 2052-02-26 · P80 2052-03-04 · P90 2052-03-14';await expect(report.locator('[data-testid="report-forecast"]')).toContainText(forecastText);await settledScreenshot(report.locator('[data-testid="report-forecast"]'),{stabilityTimeout:600000,path:info.outputPath('retained5300-forecast.png')});
  record('download-before-wait');const pendingDownload=page.waitForEvent('download',{timeout:600000});pendingDownload.catch(()=>{});record('download-before-click');await report.getByRole('button',{name:'Download complete HTML report',exact:true}).click();record('download-click');const download=await pendingDownload;record('download-event',{filename:download.suggestedFilename()});expect(download.suggestedFilename()).toBe(`sponsor-report-${reportId}.html`);const htmlFile=info.outputPath('retained5300-actual-report.html');record('download-before-save');await download.saveAs(htmlFile);expect(await download.failure()).toBeNull();const htmlBytes=fs.readFileSync(htmlFile);record('download-saved',{sha256:sha(htmlBytes),bytes:htmlBytes.length});expect(htmlBytes.toString()).toBe(expectedHtml(summary,pages));
  record('local-document-before-open');const doc=await page.context().newPage(),external:string[]=[];let docError:any;doc.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});
  try{record('local-document-before-navigation');await doc.goto(pathToFileURL(htmlFile).href);await expect(doc.locator('script,iframe,img,link')).toHaveCount(0);await expect(doc.locator('tr[data-issue-key]')).toHaveCount(5300);await expect(doc.locator('tr[data-target-key],tr[data-capacity-key]')).toHaveCount(0);expect(external).toEqual([]);
   const rendered=await doc.locator('tr[data-issue-key]').evaluateAll((rows:any[])=>rows.map(r=>({key:r.getAttribute('data-issue-key'),cells:[...r.querySelectorAll('td')].map((c:any)=>c.textContent.trim()),bars:r.querySelectorAll('.track .bar').length})));expect(rendered).toEqual(graded.rows.map((r:any)=>({key:r.key,cells:[r.key,r.summary,r.startDate??'—',r.dueDate??'—',String(r.duration??'—'),r.statusCategory,''],bars:1})));journal.all5300HtmlFieldsVerified=true;save();await expect(doc.locator('body')).toContainText(forecastText);await expect(doc.locator('body')).toContainText('seed 42, 40 simulated finishes');await expect(doc.locator('.report-provenance')).toContainText(reportId);await expect(doc.locator('.report-provenance')).toContainText(summary.hash);
   for(const key of ['LZPP-1','LZPP-5300','LZPP-6']){const row=doc.locator(`tr[data-issue-key="${key}"]`);await row.scrollIntoViewIfNeeded();await settledScreenshot(doc,{subject:row,path:info.outputPath(`retained5300-${key}.png`)});}
  }catch(error){docError=error;throw error;}finally{try{await doc.close();record('local-document-closed');}catch(error){throw new AggregateError([...(docError?[docError]:[]),error],'Full report body/document close errors');}}
  await stopUi();const againFrame=await openPlan(page,name),againWork=await planning(againFrame);await againWork.getByRole('button',{name:'Sponsor reports',exact:true}).click();const againReport=againWork.locator('[data-testid="sponsor-reports"]'),againRead=actualResponse(page,'getSponsorReport',planId);await againReport.getByRole('navigation',{name:'Retained sponsor reports'}).getByRole('button').filter({hasText:'Every existing performance row'}).click();expect((await againRead).report).toEqual(summary);await stopUi();
  for(let n=0;n<106;n++)expect((await read('getSponsorReportPage',{planId,reportId,section:'timeline',page:n})).page).toEqual(pages[n]);expect((await read('getSponsorReport',{planId,reportId})).report).toEqual(summary);journal.reopenedAllPagesImmutable=true;await snapshot();await baseline();expect(await owned()).toEqual(originalOwned);expect(await read('getCapacitySettings')).toEqual(expectedPrefs);journal.reviewRequired=true;journal.completed=true;record('stopped-for-root-report-inspection',{state:job.state,checkpoint:job.checkpoint,cleanupDone:job.cleanupDone});

 }catch(error){bodyFailed=true;bodyError=error;record('body-error',String(error));throw error;}
 finally{const errors:any[]=[];for(const[label,audit]of[
  ['no-unexpected-ui-writes',async()=>{expect(forbiddenUi).toEqual([]);expect(uiRouteErrors).toEqual([]);}],['stop-owned-ui',async()=>{if(!page.isClosed())await stopUi();}],['retained-job',async()=>{if(ready){const final=checkedJob((await read('getSponsorReportCapture',{planId,jobId})).job);journal.finalJob=final;journal.publicationObserved=final.state==='complete';save();const physical=await probe();journal.finalProbe=physical;save();verifyCaptureProbe(physical,{planId,jobId,...final});if(latestVerifiedProbe)preservedArtifacts(physical,final,latestVerifiedProbe);else if(admittedProbe)preservedArtifacts(physical,final,admittedProbe);if(publishedProbe)expect(physical).toEqual(publishedProbe);}}],['pristine-snapshot',async()=>{if(ready)await snapshot();}],['shared-issue',async()=>{for(let n=0;n<2;n++)await sharedIssue();}],['original-source',async()=>{if(originalSource)expect(await source()).toEqual(originalSource);}],['registry',async()=>await registry(planDeleted?originals:ownedRegistry)],
  ['source-plan',async()=>{if(originalOwned&&!planDeleted)expect(await owned()).toEqual(originalOwned);}],['preferences',async()=>{if(ready)for(let n=0;n<2;n++)expect(await read('getCapacitySettings')).toEqual(expectedPrefs);}],['original-drafts',async()=>{if(ready)for(const id of originals)await drafts(id);}],['owned-baseline',async()=>{if(ready&&!planDeleted){await drafts(planId);await baseline();}}]
 ]as const){try{await audit();}catch(error){errors.push(error);record('independent-audit-error',{label,error:String(error)});}}try{await drainUi();expect(uiRouteErrors).toEqual([]);expect(forbiddenUi).toEqual([]);}catch(error){errors.push(error);record('independent-audit-error',{label:'final-ui-transport-drain',error:String(error)});}budget.close();try{journal.finalBudget=budget.snapshot();}catch(error){errors.push(error);record('independent-audit-error',{label:'final-budget-clock',error:String(error)});}journal.sourceAndPreferencesPreserved=ready&&errors.length===0;if(errors.length)journal.completed=false;page.off('request',capture);await page.unroute('**/*',blockUiWrites);save();if(errors.length)throw new AggregateError([...(bodyFailed?[bodyError]:[]),...errors],'Retained diagnostic/recovery and independent audit errors');}
});
