import {proveDeletedPlanTwice} from './deleted-plan-absence.mjs';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';
import {test,expect} from '../../fixtures/forge';
import {getHarnessLaunchReceipt} from '../../forge/browser';
import {getTestState} from '../../testhook/client';
import {get,BASE} from '../../data/jira.mjs';
import {openPlans} from './forecast-fixture';
import {table} from './normalization-owned-fixture';
import {planning} from './campaign-ui';
import {settledScreenshot} from './settled-screenshot.mjs';
import {privateAccount,privateDeletedState,privateCleanupStep,finishPrivateWitness} from './private-report-witness-contract.mjs';
import {retainedPhase,retainedPins,originalPlans,shaBytes,admitRetainedBytes,verifyRetainedFresh,requireCleanupAuthority} from './private-retained-continuation-contract.mjs';
import {privateWitnessSession} from './private-report-witness-session';
const enabled=retainedPhase(process.env.LZ_PRIVATE_RETAINED_PHASE);
// With a phase present, missing/wrong bound input refuses before registration.
const pinned:any=enabled?admitRetainedBytes(fs.readFileSync(process.env.LZ_PRIVATE_RETAINED_JOURNAL||''),fs.readFileSync(process.env.LZ_PRIVATE_RETAINED_TERMINAL||'')):null;
test.describe.configure({retries:0,timeout:900000});
test('retained private report: exact failed-run owner reopen export and guarded cleanup without recapture',async({page},info)=>{
 test.skip(!enabled,'Explicit retained continuation phase required');expect(BASE).toBe('https://wolfaenpak.atlassian.net');
 const launch=getHarnessLaunchReceipt(page.context());if(!launch||launch.mode!=='portable-chrome152')throw new Error('Actual portable launch receipt required');expect(launch?.principalSha256).toBe(shaBytes(privateAccount));expect(launch?.uiVersion).toBe('4.58.588');
 await page.context().tracing.stop();fs.mkdirSync(info.outputDir,{recursive:true});
 const journal:any={schema:1,phase:'reopen-cleanup',priorJournalSha256:retainedPins.journalSha256,priorTerminalSha256:retainedPins.terminalSha256,launch,owned:pinned.owned,events:[],completed:false,physicalKvsVerified:false,secondPrincipalVerified:false,jiraWrites:0,newForks:0,newCaptures:0,advanceCalls:0};
 const persist=()=>fs.writeFileSync(info.outputPath('private-retained-continuation.json'),JSON.stringify(journal,null,2));
 const step=(value:string)=>{journal.step=value;persist();};
 const record=(stage:string,value:any)=>{journal.events.push({stage,atMs:Date.now(),value});persist();};persist();
 const session=privateWitnessSession(page,{record,retainedOnly:true});let owner:any,bodyFailed=false,documentPage:any,cleanupArmed=false;
 const mutationFence=async()=>{expect(cleanupArmed).toBe(true);expect(owner).toEqual(pinned.owner);session.checked();await session.drain();session.checked();};
 const hook=async(query:any)=>{if(['clearDrafts','deleteFixture'].includes(query.what)){expect(query).toEqual({what:query.what,planId:retainedPins.sourcePlanId});await mutationFence();}else if(!['plans','plan'].includes(query.what))throw new Error('Unknown retained hook action');const result=await getTestState('lz-ppm',query);record('retained-hook',{query,result});return result;};
 const read=async(key:string,payload:any={})=>{const result=await session.invoke(key,payload);expect(result.success).toBe(true);return result;};
 const principal=async()=>{const response=await page.request.get(`${BASE}/rest/api/3/myself`);expect(response.status()).toBe(200);const body=await response.json();expect(body.accountId).toBe(privateAccount);record('browser-principal',{accountId:body.accountId});return body.accountId;};
 const issue=async()=>{const fixture=JSON.parse(fs.readFileSync('tests/report-packed-upgrade/fixture-read.json','utf8'));const value=await get(`/rest/api/3/issue/WFH-2820?fields=${fixture.fields}`);expect(value).toEqual(pinned.events.find((e:any)=>e.stage==='shared-issue-get-only').value);record('shared-issue-get-only',value);return value;};
 const registry=async()=>{const result=await hook({what:'plans'});return result.plans.map((p:any)=>p.id).sort();};
 const standing=async()=>{const result=await hook({what:'plan',planId:originalPlans[0]});expect(result).toEqual(pinned.events.find((e:any)=>e.stage==='private-hook'&&e.value.query.what==='plan'&&e.value.query.planId===originalPlans[0]).value.result);return result;};
 const draft=async(planId:string)=>({draft:await read('getDraft',{planId}),active:await read('getActiveDrafts',{planId})});
 const allDrafts=async()=>{const result:any={};for(const id of [...originalPlans,retainedPins.sourcePlanId,retainedPins.privatePlanId])result[id]=await draft(id);return result;};
 const fresh=async()=>({principal:await principal(),registry:await registry(),standing:await standing(),issueFirst:await issue(),issueSecond:await issue(),settings:await read('getCapacitySettings'),source:await hook({what:'plan',planId:retainedPins.sourcePlanId}),snapshot:(await read('getSnapshot',{planId:retainedPins.sourcePlanId,snapshotId:pinned.snapshot.id})).snapshot,planRead:await read('getPlan',{planId:retainedPins.privatePlanId}),modelRead:await read('getSimulationModel',{planId:retainedPins.privatePlanId}),drafts:await allDrafts()});
 const performDelete=async(action:()=>Promise<any>)=>{await mutationFence();const pending=session.wait('deletePlan',retainedPins.privatePlanId);try{session.checked();await action();expect(await pending.promise).toEqual({success:true});}finally{pending.dispose();}};
 const openOwned=async()=>{await session.stop();return table(page,pinned.privateName);};
 const reportView=async(frame:any)=>{const work=await planning(frame);await work.getByRole('button',{name:'Sponsor reports',exact:true}).click();const report=work.locator('[data-testid="sponsor-reports"]');await report.getByRole('navigation',{name:'Retained sponsor reports'}).getByRole('button').filter({hasText:pinned.report.name}).click();return report;};
 const status=async()=>{let current:any;for(const payload of [{planId:retainedPins.privatePlanId,jobId:retainedPins.jobId},{planId:retainedPins.privatePlanId}]){current=await read('getSponsorReportCapture',payload);expect(current).toEqual({success:true,job:pinned.finalJob,report:pinned.report});}return current;};
 const pages=async()=>{const result=[];for(const section of Object.keys(pinned.report.pages))for(let n=0;n<pinned.report.pages[section];n++)result.push((await read('getSponsorReportPage',{planId:retainedPins.privatePlanId,reportId:retainedPins.reportId,section,page:n})).page);expect(result).toEqual(pinned.expected.pages);return result;};
 const download=async(report:any,file:string)=>{const pending=page.waitForEvent('download',{timeout:180000});session.checked();await report.getByRole('button',{name:'Download complete HTML report',exact:true}).click();const value=await pending;expect(value.suggestedFilename()).toBe(`sponsor-report-${retainedPins.reportId}.html`);const path=info.outputPath(file);await value.saveAs(path);expect(await value.failure()).toBeNull();const html=fs.readFileSync(path,'utf8');expect(html).toBe(pinned.expected.html);record('retained-html',{file,sha256:shaBytes(html),bytes:Buffer.byteLength(html)});return{path,html};};
 const inspect=async(path:string,file:string)=>{documentPage=await page.context().newPage();await documentPage.goto(pathToFileURL(path).href);await expect(documentPage.locator('script,iframe,img,link')).toHaveCount(0);await expect(documentPage.locator('[data-issue-key="WFH-2820"]')).toHaveCount(1);await expect(documentPage.locator('body')).toContainText('Private simulation model');await settledScreenshot(documentPage,{subject:documentPage.locator('body'),path:info.outputPath(file),fullPage:true});await documentPage.close();documentPage=null;};
 try{
  // Acquire only a genuine non-plan Capacity wire before admitting retained reads.
  step('fresh-admission');await principal();expect(await registry()).toEqual([...originalPlans,retainedPins.sourcePlanId,retainedPins.privatePlanId].sort());await standing();await issue();
  let frame=await openPlans(page);const capacity=session.wait('getCapacitySettings');try{await frame.getByRole('button',{name:'Capacity',exact:true}).click();expect(await capacity.promise).toEqual(pinned.settings);}finally{capacity.dispose();}expect(await read('getCapacitySettings')).toEqual(pinned.settings);
  const source=await hook({what:'plan',planId:retainedPins.sourcePlanId});expect(source).toEqual(pinned.source);session.source(source,pinned.sourceName);
  const snapshot=(await read('getSnapshot',{planId:retainedPins.sourcePlanId,snapshotId:pinned.snapshot.id})).snapshot;expect(snapshot).toEqual(pinned.snapshot);
  session.retainedCandidate({ack:pinned.fork,source,snapshot,name:pinned.privateName});
  const admission=await fresh();const inputs=verifyRetainedFresh(pinned,admission);record('retained-fresh-admission',admission);await session.stop();owner=await session.admitRetained(inputs,()=>table(page,pinned.privateName));expect(owner).toEqual(pinned.owner);journal.owner=owner;persist();
  step('retained-report-first-export');frame=session.frame();await status();expect((await read('getSponsorReport',{planId:owner.planId,reportId:retainedPins.reportId})).report).toEqual(pinned.report);const firstPages=await pages();let report=await reportView(frame);const first=await download(report,'private-retained-report.html');await inspect(first.path,'private-retained-report.png');
  step('retained-report-reopen-export');frame=await openOwned();report=await reportView(frame);await status();expect((await read('getSponsorReport',{planId:owner.planId,reportId:retainedPins.reportId})).report).toEqual(pinned.report);expect(await pages()).toEqual(firstPages);const reopened=await download(report,'private-retained-reopened.html');await inspect(reopened.path,'private-retained-reopened.png');journal.reopened=true;persist();
  step('fresh-cleanup-admission');const beforeCleanup=await fresh();const latest=await status();cleanupArmed=requireCleanupAuthority(pinned,{fresh:beforeCleanup,owner,summary:latest.report,job:latest.job,pages:firstPages,html:first.html,reopenedHtml:reopened.html});record('retained-cleanup-authority',{admission:beforeCleanup,reportId:retainedPins.reportId,job:pinned.finalJob});await session.stop();
  step('delete-retained-report');await mutationFence();expect(await session.invoke('deleteSponsorReport',{planId:owner.planId,reportId:retainedPins.reportId},true)).toEqual({success:true,deleted:true});journal.reportDeleted=true;persist();
  const deleted=await read('getSponsorReportCapture',{planId:owner.planId,jobId:retainedPins.jobId});let cleaned=privateDeletedState(pinned.finalJob,deleted.job);expect(deleted).toEqual({success:true,job:cleaned});journal.deletedState=deleted;persist();
  for(let n=0;n<20&&!cleaned.cleanupDone;n++){await mutationFence();const result=await session.invoke('cancelSponsorReportCapture',{planId:owner.planId,jobId:retainedPins.jobId},true);const next=privateCleanupStep(cleaned,result.job);expect(result).toEqual({success:true,job:next});cleaned=next;journal.cleaned=cleaned;persist();}expect(cleaned.cleanupDone).toBe(true);
  for(let n=0;n<2;n++){expect(await read('getPlan',{planId:owner.planId})).toEqual({success:true,plan:owner.plan});expect(await read('getSimulationModel',{planId:owner.planId})).toEqual(owner.modelRead);expect(await read('getSponsorReportCapture',{planId:owner.planId,jobId:retainedPins.jobId})).toEqual({success:true,job:cleaned});expect(await session.invoke('getSponsorReport',{planId:owner.planId,reportId:retainedPins.reportId})).toEqual({success:false,error:'This sponsor report was deleted or is unavailable'});expect(await session.invoke('getSponsorReportPage',{planId:owner.planId,reportId:retainedPins.reportId,section:'timeline',page:0})).toEqual({success:false,error:'This report is unavailable'});const listed=await read('listSponsorReports',{planId:owner.planId});expect(listed.entries).toEqual([]);expect(listed.cursor??null).toBeNull();}journal.publicAbsenceTwice=true;persist();
  step('delete-retained-private-plan');frame=await openPlans(page);const card=frame.locator('.lz-card').filter({hasText:pinned.privateName});await expect(card.locator('[data-testid="plan-card-simulation"]')).toHaveText('Private simulation');await card.getByRole('button',{name:'More',exact:true}).click();await card.getByRole('button',{name:'Delete plan',exact:true}).click();await performDelete(()=>frame.getByRole('dialog',{name:'Delete Plan',exact:true}).getByRole('button',{name:'Delete',exact:true}).click());await expect(card).toHaveCount(0);
  for(let n=0;n<2;n++){expect(await session.invoke('getPlan',{planId:owner.planId})).toEqual({success:false,error:'Plan not found'});expect(await registry()).toEqual([...originalPlans,retainedPins.sourcePlanId].sort());}journal.privateDeleted=true;persist();
  step('delete-retained-source-plan');expect(await hook({what:'plan',planId:retainedPins.sourcePlanId})).toEqual(pinned.source);expect((await read('getSnapshot',{planId:retainedPins.sourcePlanId,snapshotId:pinned.snapshot.id})).snapshot).toEqual(pinned.snapshot);await session.stop();await hook({what:'clearDrafts',planId:retainedPins.sourcePlanId});expect(await hook({what:'deleteFixture',planId:retainedPins.sourcePlanId})).toEqual({deleted:retainedPins.sourcePlanId,registryRemoved:true});
  await proveDeletedPlanTwice({planId:retainedPins.sourcePlanId,expectedRegistry:originalPlans,readPlan:(planId:string)=>hook({what:'plan',planId}),readRegistry:registry});journal.sourceDeleted=true;journal.completed=true;persist();
 }catch(error){bodyFailed=true;let detail;try{detail=String((error as any)?.message??error);}catch{detail='unprintable';}journal.failure={reason:'Retained private continuation failed; no retry or inferred cleanup',detailSha256:shaBytes(detail),detailBytes:Buffer.byteLength(detail)};persist();throw new Error(journal.failure.reason);}
 finally{
  const audits=[async()=>{if(documentPage&&!documentPage.isClosed())await documentPage.close();},principal,standing,issue,issue,async()=>{expect(await read('getCapacitySettings')).toEqual(pinned.settings);},async()=>{for(const id of originalPlans)expect(await draft(id)).toEqual({draft:{success:true,draft:null},active:{success:true,drafts:{}}});},async()=>{expect(await registry()).toEqual([...originalPlans,...(journal.sourceDeleted?[]:[retainedPins.sourcePlanId]),...(journal.privateDeleted?[]:[retainedPins.privatePlanId])].sort());}];
  try{await finishPrivateWitness({journal,persist,stop:()=>session.stop(),audits});}finally{try{await session.dispose();}catch{journal.completed=false;journal.state='recovery-required';persist();throw new Error('Retained private observation remained incomplete');}if(bodyFailed){journal.completed=false;journal.state='recovery-required';persist();}}
 }
});
