import fs from 'node:fs';import {test,expect} from '../../fixtures/forge';import {getTestState} from '../../testhook/client';import {get} from '../../data/jira.mjs';
import {table} from './normalization-owned-fixture';import {planning,currentUserResolver,actualResponse,callEnvelope} from './campaign-ui';import {settledScreenshot,waitForAppReady} from './settled-screenshot.mjs';import {withReportDeparture,setReportDepartureOwner,stopReportUi} from './report-departure';import {loadVisualReceipt,visualPins,visibleGeometry,visualCall} from './uat-comparison-visual.mjs';
const phase=process.env.LZ_UAT_COMPARISON_PHASE;if(phase&&phase!=='readonly')throw Error('Unknown comparison witness phase');
test.describe.configure({retries:0,timeout:600000});
test('read-only retained UAT comparison viewport proof at 1100 and 1440',async({page},info)=>{
 test.skip(!phase,'Explicit read-only comparison dispatch required');const {journal:prior,audit}=loadVisualReceipt() as any,planId=prior.plans.main.id,name=prior.plans.main.name,base=prior.steps.find((s:any)=>s.name==='baseline and original').data.base,alternative=prior.steps.find((s:any)=>s.name==='saved alternative').data,expected=prior.handoff.expected;
 const expectedAudit=Object.fromEntries(audit.reads.map((r:any)=>[r.name,r.body]));const receipt:any={pins:visualPins,reads:[],requests:[],captures:[],passed:false};const persist=()=>fs.writeFileSync(info.outputPath('comparison-visual.json'),JSON.stringify(receipt,null,2));persist();
 const hook=async(what:string,payload:any={})=>{const body=await getTestState('lz-ppm',{what,...payload});receipt.reads.push({kind:'hook',what,payload,body,at:new Date().toISOString()});persist();return body;};
 const source=async()=>{expect(await hook('plans')).toEqual(expectedAudit['current registry']);for(const id of ['plan-msq9dg8l-gz6mz1',prior.plans.main.id,prior.plans.mirror.id])expect(await hook('plan',{planId:id})).toEqual(expectedAudit[id]);for(const i of prior.admittedJira){const uri=`/rest/api/3/issue/${i.key}?fields=project,summary,labels,issuetype,parent,issuelinks,status,assignee,timeestimate,customfield_10015,duedate,customfield_10180,customfield_10181,customfield_11148,customfield_11149`,body=await get(uri);receipt.reads.push({kind:'jira',key:i.key,body,at:new Date().toISOString()});persist();expect(body).toEqual(expectedAudit[i.key]);}};
 await source();let rpc:any,poison:any;const graph='**/gateway/api/graphql**',route=async(route:any)=>{const data=callEnvelope(route.request()),input=data?.variables?.input;if(input?.extensionId!=='ari:cloud:ecosystem::extension/087a8e18-d45a-4cb7-9d87-3e84101ac4f3/d6096af9-3082-4ee1-a05e-f8b61d766b77/static/ppm-dashboard')return route.continue();try{receipt.requests.push({...visualCall(input.payload.call,planId),at:new Date().toISOString()});persist();await route.continue();}catch(error){poison=error;receipt.refusal=String(error);persist();await route.abort();}};await page.route(graph,route);
 try{await withReportDeparture(page,info,async()=>{setReportDepartureOwner(page,planId,name);rpc=currentUserResolver(page,(c:any)=>c?.payload?.planId===planId||c?.functionKey==='getCapacitySettings');
 const read=async(functionKey:string,payload:any={})=>{visualCall({functionKey,payload},planId);const body=await rpc.invoke(functionKey,payload);receipt.reads.push({kind:'rpc',functionKey,payload,body,at:new Date().toISOString()});persist();if(poison)throw poison;return body;};
 try{const frame=await table(page,name);expect((await frame.locator('body').innerText()).match(/REV\s+V(\d+\.\d+\.\d+)/i)?.[1]).toBe('4.58.588');expect(await read('checkUserRole')).toEqual({success:true,role:'admin',isAdmin:true,accountId:prior.person.accountId});
 const settings={success:true,version:prior.privateSettingsOwnership.version,settings:prior.privateSettingsOwnership.original};
 const intact=async()=>{expect(await read('getCapacitySettings')).toEqual(settings);expect(await read('getPlan',{planId})).toEqual({success:true,plan:expectedAudit[planId].meta});expect(await read('getDraft',{planId})).toEqual({success:true,draft:null});expect(await read('getActiveDrafts',{planId})).toEqual({success:true,drafts:{}});for(const snapshot of [base,alternative])expect((await read('getSnapshot',{planId,snapshotId:snapshot.id})).snapshot).toEqual(snapshot);expect((await read('getSponsorReport',{planId,reportId:prior.handoff.reportId})).report).toEqual(prior.steps.find((s:any)=>s.name==='retained sponsor report').data.summary);};await intact();
 const work=await planning(frame);await work.getByRole('button',{name:'Scenarios & history',exact:true}).click();
 const choose=async(snapshot:any)=>{const pending=actualResponse(page,'getSnapshot',planId);await work.getByRole('navigation',{name:'Retained captures'}).getByRole('button').filter({hasText:snapshot.name}).click();expect((await pending).snapshot).toEqual(snapshot);};await choose(base);await work.getByRole('button',{name:'Use as comparison basis',exact:true}).click();await choose(alternative);
 const comp=work.locator('[data-testid="scenario-comparison"]');await expect(comp).toContainText('0 added, 0 removed, 1 changed rows.');await comp.getByRole('button',{name:'Calculate both forecasts',exact:true}).click();for(const p of ['p50','p80','p90']){const cells=comp.locator('tr').filter({hasText:new RegExp(`^${p.toUpperCase()}`)}).locator('td');await expect(cells.nth(0)).toHaveText(expected.original[p]);await expect(cells.nth(1)).toHaveText(expected.alternative[p]);}for(const side of ['original','alternative'])await expect(comp).toContainText(`UAT October 16 commitment: ${expected[side].displayedTargetPercent}% of runs finish by 2026-10-16`);
 const geometry=async(subject:any)=>{const local=await subject.evaluate((el:any)=>{const r=el.getBoundingClientRect(),w=el.ownerDocument.defaultView,points=[[r.left+2,r.top+2],[r.right-2,r.top+2],[r.left+2,r.bottom-2],[r.right-2,r.bottom-2],[r.left+r.width/2,r.top+r.height/2]];return {top:r.top,left:r.left,right:r.right,bottom:r.bottom,width:r.width,height:r.height,viewportWidth:w.innerWidth,viewportHeight:w.innerHeight,visible:getComputedStyle(el).visibility==='visible',clear:points.every(([x,y])=>{const top=el.ownerDocument.elementFromPoint(x,y);return top&&(el.contains(top)||top.contains(el));})};});const box=await subject.boundingBox();expect(box).toBeTruthy();const host=await page.evaluate((r:any)=>{const frame=document.querySelector('iframe[data-testid="hosted-resources-iframe"]');let visible=!!frame;for(let el:any=frame;el;el=el.parentElement){const style=getComputedStyle(el);if(style.visibility!=='visible'||style.display==='none'||Number(style.opacity)<.99)visible=false;}const points=[[r.x+2,r.y+2],[r.x+r.width-2,r.y+2],[r.x+2,r.y+r.height-2],[r.x+r.width-2,r.y+r.height-2],[r.x+r.width/2,r.y+r.height/2]];return {top:r.y,left:r.x,right:r.x+r.width,bottom:r.y+r.height,width:r.width,height:r.height,viewportWidth:window.innerWidth,viewportHeight:window.innerHeight,visible,clear:points.every(([x,y])=>document.elementFromPoint(x,y)===frame)};},box);return visibleGeometry({...local,host});};
 for(const width of [1100,1440]){await page.setViewportSize({width,height:1000});await waitForAppReady(comp);const tables=comp.locator('table'),targetBlocks=comp.locator(':scope > div').filter({hasText:'UAT October 16 commitment'});await expect(tables).toHaveCount(3);await expect(targetBlocks).toHaveCount(4);
  const groups=[{name:'overview',anchor:tables.nth(0),subjects:[comp.getByRole('heading',{level:3}),tables.nth(0)]},{name:'changes',anchor:comp.getByRole('heading',{name:'Dependency changes',exact:true}),subjects:[comp.getByRole('heading',{name:'Schedule and scope changes',exact:true}),tables.nth(1),comp.getByText('Same dependency network.',{exact:true}),comp.getByRole('heading',{name:'Saved target scopes',exact:true}),targetBlocks.nth(0),targetBlocks.nth(1)]},{name:'forecast',anchor:tables.nth(2),subjects:[comp.getByRole('heading',{name:'Forecast comparison',exact:true}),tables.nth(2),targetBlocks.nth(2),targetBlocks.nth(3)]}];
  for(const group of groups){await group.anchor.evaluate((el:any)=>el.scrollIntoView({block:'center',inline:'nearest'}));await waitForAppReady(group.anchor);const before=[];for(const subject of group.subjects)before.push(await geometry(subject));const shot=await settledScreenshot(page,{path:info.outputPath(`comparison-${width}-${group.name}.png`),fullPage:false,subject:group.anchor});const after=[];for(const subject of group.subjects)after.push(await geometry(subject));receipt.captures.push({width,name:group.name,before,after,shot,at:new Date().toISOString()});persist();}
 }
 await intact();if(poison)throw poison;
 }finally{try{await stopReportUi(page,async()=>{if(!page.isClosed())await page.goto('about:blank');});}finally{rpc?.stop();await page.unroute(graph,route);await source();}}if(poison)throw poison;receipt.passed=true;persist();});}catch(error){receipt.passed=false;receipt.failure=String(error);persist();throw error;}
});
