// Deliberately separate old-code prepare and upgraded finish; no implicit cleanup between deployments.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
import {test,expect} from '../../fixtures/forge';import {getTestState} from '../../testhook/client';import {getHarnessLaunchReceipt} from '../../forge/browser';
import {openPlans,scheduleFields,LZPT_PLAN} from './forecast-fixture';import {actualResponse,currentUserResolver,planning} from './campaign-ui';import {table} from './normalization-owned-fixture';
import {observeReportCapture} from './report-capture';import {holdFirstReportAdvance,awaitHeldReportStep} from './report-capture-held-step';import {observeCaptureProbe,verifyCaptureProbe,cleanReportCapture} from './report-capture-cleanup.mjs';import {settledScreenshot} from './settled-screenshot.mjs';import {legacyPrincipal as packedPrincipal,legacyForecastInput as packedForecastInput} from './report-legacy-upgrade-contract.mjs';
// Shared WFH-2820 is read-only; no issue mutation/deletion import exists.
import {get,BASE} from '../../data/jira.mjs';
import {admitPackedReceipt,admitPackedFixture,assertPackedExpansion} from './report-packed-upgrade-contract.mjs';
import {oldPackedForecast} from '../../tests/report-packed-upgrade/old-producer-frozen.mjs';
const fixture=JSON.parse(fs.readFileSync(path.resolve('tests/report-packed-upgrade/fixture-read.json'),'utf8'));
const originals=[LZPT_PLAN,'plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].sort(),sha=(s:any)=>createHash('sha256').update(s).digest('hex'),prefs={success:true,version:62,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}};
const expectedForecast={state:'available',reason:null,modelVersion:'duration-triangular-fs-v1',runs:300,seed:42,uncertainty:'medium',p50:'2026-10-09',p80:'2026-10-12',p90:'2026-10-12',onPlannedFinish:197/300,coverage:{totalLeaves:1,datedLeaves:1,sampledLeaves:1,missingDates:0,invalidDates:0,invertedDates:0,invalidBaselines:0}};
const canonical=(x:any):any=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x;
test.describe.configure({retries:0,timeout:900000});
for(const phase of ['finish']as const)test(`packed report ${phase}: real old paused encoded job preserves identical report across packed-layout upgrade`,async({page},info)=>{
 expect(process.env.LZ_PACKED_UPGRADE_PHASE).toBe(phase);expect(BASE).toBe('https://wolfaenpak.atlassian.net');expect(sha(fs.readFileSync(path.resolve('tests/report-packed-upgrade/old-producer-frozen.mjs')))).toBe('e2c4a56b22c133ee1d7a05adf819b214a5351a54beb1bb7e383cb4f5fd8dc8d4');expect(sha(fs.readFileSync(path.resolve('tests/report-packed-upgrade/fixture-read.json')))).toBe('bac0f90bddbe0d6b368564c929e3931044a590113a2250dec04a3e3db6fd5d1a');const receipt=getHarnessLaunchReceipt(page.context());if(!receipt||receipt.mode!=='portable-chrome152')throw new Error('Known portable receipt required');expect(receipt).toMatchObject({browserVersion:'152.0.7977.76',principalSha256:packedPrincipal,executableSha256:'755178ee89130a6f1c94cc4ecb2289fe74240db3e7efe9ec69a6cfcd4b93a6ee',frameworkSha256:'bfea9981cc61dfa72d847c920f274e4e96e362954f451198d8ee1650cbefb2e6'});expect(receipt.uiVersion).toBe(process.env.LZ_EXPECTED_UI_VERSION);
 let prepared:any;if(phase==='finish'){const bytes=fs.readFileSync(path.resolve(process.env.LZ_PACKED_PREPARE_JOURNAL||''));expect(process.env.LZ_PACKED_PREPARE_SHA).toBe('76aa65a2282c21ddbf710aee88d217480983226f34a26fb53459f942d4f5fd26');expect(sha(bytes)).toBe(process.env.LZ_PACKED_PREPARE_SHA);prepared=JSON.parse(bytes.toString());expect(prepared.completed).toBe(true);expect(process.env.LZ_DEPLOYED_APP).toMatch(/^[a-f0-9]{40}$/);expect(process.env.LZ_DEPLOYED_APP).not.toBe(prepared.deployedApp);expect(process.env.LZ_DEPLOYED_FORGE).toMatch(/^\d+\.\d+\.\d+$/);}
 const marker=prepared.marker,name=prepared.name,summary=prepared.originalIssue.fields.summary;const journal:any={phase,marker,name,receipt,deployedForge:process.env.LZ_DEPLOYED_FORGE,deployedApp:process.env.LZ_DEPLOYED_APP,events:[],probes:[],planId:prepared.planId,issue:prepared.issue,jiraWrites:0,completed:false,integrityPreserved:false,expectedForecast};fs.mkdirSync(info.outputDir,{recursive:true});const save=()=>fs.writeFileSync(info.outputPath(`packed-${phase}.json`),JSON.stringify(journal,null,2));const record=(stage:string,value:any={})=>{journal.events.push({stage,time:new Date().toISOString(),value});save();};save();

 const rpc=currentUserResolver(page,c=>c?.functionKey==='getCapacitySettings');let ready=false,session:any,held:any,bodyError:any,originalSource:any,planDeleted=false;
 const allowedRpc=new Set(['getCapacitySettings','getDraft','getActiveDrafts','getLockStatus','getPlanCalendar','getSponsorReportCapture','getSponsorReport','getSponsorReportPage','getBaseline','deleteSponsorReport','cancelSponsorReportCapture','deletePlan']);
 const invoke=async(key:string,payload:any={})=>{expect(allowedRpc.has(key)).toBe(true);const value=await rpc.invoke(key,payload);record(key,value);return value;};const read=async(key:string,payload:any={})=>{const value=await invoke(key,payload);expect(value.success,value.error).toBe(true);return value;};
 const source=async()=>{const s=await getTestState('lz-ppm',{what:'plan',planId:LZPT_PLAN});expect(s.issues).toHaveLength(45);const basis={issues:scheduleFields(s.issues),sources:s.meta.sources,calendarKey:s.meta.calendarKey,holidayYears:s.meta.holidayYears,milestones:s.meta.milestones,protectionEnabled:s.meta.protectionEnabled};expect(sha(JSON.stringify(basis))).toBe('2d5c1ea0d3e742ff61ae47701ab6a391d0cbe6f0238e9415fb73b38e8f21f104');return s;};
 const registry=async(ids:string[])=>{const v=await getTestState('lz-ppm',{what:'plans'});record('registry',v.plans);expect(v.plans.map((p:any)=>p.id).sort()).toEqual(ids);};const drafts=async(planId:string)=>{expect(await read('getDraft',{planId})).toEqual({success:true,draft:null});expect(await read('getActiveDrafts',{planId})).toEqual({success:true,drafts:{}});};
 const issue=async()=>{const v=await get(`/rest/api/3/issue/WFH-2820?fields=${fixture.fields}`);record('retained-issue-readonly',v);admitPackedFixture(v,prepared.originalIssue);return v;};
 const ownPlan=async()=>{const v=await getTestState('lz-ppm',{what:'plan',planId:journal.planId});record('owned-plan',v);expect(v.meta).toMatchObject({id:journal.planId,name,createdBy:'harness',calendarKey:'standard'});expect(v.meta.mode).toBeUndefined();expect(v.issues).toHaveLength(1);expect(v.issues[0]).toMatchObject({id:journal.issue.id,key:journal.issue.key,summary,startDate:'2026-10-05',dueDate:'2026-10-09',duration:5});return v;};
 const probe=async(job:any)=>{const v=await observeCaptureProbe(()=>getTestState('lz-ppm',{what:'reportCaptureState',planId:journal.planId,jobId:job.id}),(v:any)=>{journal.probes.push(v);save();});verifyCaptureProbe(v,{planId:journal.planId,jobId:job.id,...job});return v;};
 const pauseHeld=async(report:any)=>{const response=await awaitHeldReportStep(held,180000)as any;expect(response.responseStatus).toBe(200);expect(response.body.success).toBe(true);await report.getByRole('button',{name:'Pause capture',exact:true}).click();held.release();await expect(report.getByRole('button',{name:'Resume capture',exact:true})).toBeVisible();await session.recorder.wait((s:any)=>s.job?.checkpoint===response.body.job.checkpoint,120000);await held.stop();held=null;await session.settle();const count=session.recorder.snapshot().events.filter((e:any)=>e.type==='request'&&e.key==='advanceSponsorReportCapture').length;for(let n=0;n<2;n++)expect((await read('getSponsorReportCapture',{planId:journal.planId,jobId:response.body.job.id})).job).toEqual(response.body.job);await session.settle();expect(session.recorder.snapshot().events.filter((e:any)=>e.type==='request'&&e.key==='advanceSponsorReportCapture').length).toBe(count);record('paused-no-extra-advance',{job:response.body.job,advanceCount:count});return response.body.job;};
 try{
  originalSource=await source();record('original-source',originalSource);await registry([...originals,journal.planId].sort());const plans=await openPlans(page);await settledScreenshot(page,{subject:plans.locator('.lz-card',{hasText:'LZPT Scenarios'}),path:info.outputPath(`packed-${phase}-entry.png`),fullPage:true});const pending=actualResponse(page,'getCapacitySettings');await plans.getByRole('button',{name:'Capacity',exact:true}).click();expect(await pending).toEqual(prefs);ready=true;expect(await read('getCapacitySettings')).toEqual(prefs);for(const originalId of originals)await drafts(originalId);
  {
   expect(await issue()).toEqual(prepared.originalIssue);expect(await ownPlan()).toEqual(prepared.originalPlan);await drafts(journal.planId);expect(await invoke('getBaseline',{planId:journal.planId})).toEqual({baseline:null});expect(await read('getLockStatus',{planId:journal.planId})).toMatchObject({locked:false});const job=(await read('getSponsorReportCapture',{planId:journal.planId,jobId:prepared.pausedJob.id})).job;admitPackedReceipt(prepared,job,journal.planId,receipt);const {success,...calendar}=await read('getPlanCalendar',{planId:journal.planId});expect(calendar).toEqual(prepared.calendar);expect(packedForecastInput(prepared.originalPlan,calendar)).toEqual(prepared.expectedInput);expect(oldPackedForecast(prepared.originalPlan,calendar)).toEqual(prepared.oldProducerForecast);expect(await probe(job)).toEqual(prepared.pausedProbe);
   const frame=await table(page,name),work=await planning(frame);session=observeReportCapture(page,journal.planId,info,'packed-finish',job);await work.getByRole('button',{name:'Sponsor reports',exact:true}).click();const report=work.locator('[data-testid="sponsor-reports"]');await expect(report.getByRole('button',{name:'Resume capture',exact:true})).toBeVisible();await session.settle();expect(session.recorder.snapshot().events.some((e:any)=>e.type==='request'&&e.key==='advanceSponsorReportCapture')).toBe(false);
   held=await holdFirstReportAdvance(page,journal.planId,(event:any)=>record('held-response',event),(b:any)=>b?.job?.state==='active'&&b.job.stageLabel==='Preparing the retained schedule');await report.getByRole('button',{name:'Resume capture',exact:true}).click();journal.conversionEntered=await pauseHeld(report);expect(journal.conversionEntered.checkpoint).toBe(job.checkpoint+1);const entering=await probe(journal.conversionEntered);expect(entering.privateArtifacts).toEqual(prepared.pausedProbe.privateArtifacts);expect(entering.publicArtifacts).toEqual([]);
   held=await holdFirstReportAdvance(page,journal.planId,(event:any)=>record('held-response',event),(b:any)=>b?.job?.state==='active'&&b.job.stageLabel==='Calculating the forecast');await report.getByRole('button',{name:'Resume capture',exact:true}).click();journal.conversionCompleted=await pauseHeld(report);expect(journal.conversionCompleted.checkpoint).toBeGreaterThan(journal.conversionEntered.checkpoint);journal.encodedProbe=await probe(journal.conversionCompleted);assertPackedExpansion(prepared.pausedProbe,journal.encodedProbe,journal.planId,job.id);await settledScreenshot(report.locator('[data-testid="report-capture-progress"]'),{path:info.outputPath('packed-converted-paused.png')});expect(await issue()).toEqual(prepared.originalIssue);expect(await ownPlan()).toEqual(prepared.originalPlan);
   await report.getByRole('button',{name:'Resume capture',exact:true}).click();const completed:any=await session.recorder.wait((s:any)=>s.job?.state==='complete'&&s.job.cleanupDone&&!!s.report,180000);journal.completedJob=completed.job;const physical=await probe(completed.job);for(const old of journal.encodedProbe.privateArtifacts)expect(physical.privateArtifacts.find((v:any)=>v.keyHash===old.keyHash)).toMatchObject({expectedHash:old.expectedHash,present:false,actualHash:null});
   const result=(await read('getSponsorReport',{planId:journal.planId,reportId:completed.job.reportId})).report;expect(result).toEqual(completed.report);expect(result).toMatchObject({name:'Unchanged packed upgrade report',plannedFinish:'2026-10-09',counts:{timeline:1,targets:0},uncertainty:'medium',forecast:expectedForecast});expect(result.forecast).toEqual(prepared.oldProducerForecast);expect(result.forecast.inputHash).toBe(prepared.expectedInput.inputHash);expect(result.calendar).toEqual(prepared.calendar);journal.report=result;save();
   const timeline=(await read('getSponsorReportPage',{planId:journal.planId,reportId:result.id,section:'timeline',page:0})).page;const expectedRow={key:journal.issue.key,summary,startDate:'2026-10-05',dueDate:'2026-10-09',duration:5,buffer:'No',statusCategory:'new',parentKey:null};expect(timeline.rows).toEqual([expectedRow]);expect(sha(JSON.stringify(canonical(timeline.rows)))).toBe(result.document.timeline.hashes[0]);
   record('open-captured-report-intent');await report.getByRole('button',{name:'Open captured report',exact:true}).click();record('download-listener-before-click');const download=page.waitForEvent('download',{timeout:120000});await report.getByRole('button',{name:'Download complete HTML report',exact:true}).click();record('download-click-returned');const file=await download;record('download-event',{filename:file.suggestedFilename()});expect(file.suggestedFilename()).toBe(`sponsor-report-${result.id}.html`);const local=info.outputPath('packed-upgraded-actual-report.html');record('download-save-start',{path:local});await file.saveAs(local);expect(await file.failure()).toBeNull();record('actual-html-saved',{sha256:sha(fs.readFileSync(local))});record('local-document-new-page-start');const doc=await page.context().newPage();record('local-document-new-page-complete');let htmlError:any;try{const external:string[]=[];doc.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});record('local-document-navigation-start');await doc.goto(pathToFileURL(local).href);record('local-document-navigation-complete');await expect(doc.locator('script,iframe,img,link')).toHaveCount(0);await expect(doc.locator('tr[data-issue-key]')).toHaveCount(1);await expect(doc.locator('tr[data-target-key],tr[data-capacity-key]')).toHaveCount(0);const row=doc.locator(`tr[data-issue-key="${journal.issue.key}"]`);expect(await row.locator('td').allTextContents()).toEqual([journal.issue.key,summary,'2026-10-05','2026-10-09','5','new','']);await expect(row.locator('.track .bar')).toHaveCount(1);await expect(doc.locator('body')).toContainText('P50 2026-10-09 · P80 2026-10-12 · P90 2026-10-12');expect(external).toEqual([]);await settledScreenshot(doc,{subject:row,path:info.outputPath('packed-upgraded-complete-html.png'),fullPage:true});journal.actualHtmlVerified=true;}catch(error){htmlError=error;throw error;}finally{try{await doc.close();}catch(error){throw new AggregateError([...(htmlError?[htmlError]:[]),error],'Packed HTML verification/close failed');}}
   expect((await read('getSponsorReport',{planId:journal.planId,reportId:result.id})).report).toEqual(result);expect(await issue()).toEqual(prepared.originalIssue);expect(await ownPlan()).toEqual(prepared.originalPlan);session.stop();await page.goto('about:blank');expect(await read('getCapacitySettings')).toEqual(prefs);
   record('delete-owned-report-intent',{id:result.id});expect(await read('deleteSponsorReport',{planId:journal.planId,reportId:result.id})).toMatchObject({deleted:true});const cleaned:any=await cleanReportCapture({planId:journal.planId,jobId:completed.job.id,requestId:completed.job.requestId,invoke,probe:()=>getTestState('lz-ppm',{what:'reportCaptureState',planId:journal.planId,jobId:completed.job.id}),onState:(v:any)=>record('cleanup-state',v)});expect(cleaned.cleaned).toBe(true);expect(cleaned.job.state).toBe('cancelled');verifyCaptureProbe(cleaned.probes.at(-1),{planId:journal.planId,jobId:completed.job.id,...cleaned.job},physical);journal.allOriginalAndPackedArtifactsAbsent=true;
   await drafts(journal.planId);expect(await ownPlan()).toEqual(prepared.originalPlan);record('delete-owned-plan-intent',{id:journal.planId});expect((await read('deletePlan',{planId:journal.planId})).ghostRowRemoved).not.toBe(true);planDeleted=true;for(let n=0;n<2;n++){const absent=await getTestState('lz-ppm',{what:'plan',planId:journal.planId});record('plan-absence',absent);expect(absent.meta==null).toBe(true);expect(absent.issues).toEqual([]);await registry(originals);}
   expect(await issue()).toEqual(prepared.originalIssue);const final=await openPlans(page);await expect(final.getByRole('button',{name:/Open plan/})).toHaveCount(3);await settledScreenshot(page,{subject:final.locator('.lz-card',{hasText:'LZPT Scenarios'}),path:info.outputPath('packed-upgrade-original-three-restored.png'),fullPage:true});journal.completed=true;save();
  }
 }catch(error){bodyError=error;record('body-error',String(error));throw error;}
 finally{
  const errors:any[]=[];const attempt=async(label:string,fn:()=>Promise<any>)=>{try{await fn();}catch(error){errors.push(error);record('independent-error',{label,error:String(error)});}};
  await attempt('stop-owned-ui',async()=>{if(!page.isClosed())await page.goto('about:blank');});if(held)await attempt('release-held-response',()=>held.stop());if(session)session.stop();
  await attempt('original-source',async()=>{if(originalSource)expect(await source()).toEqual(originalSource);});await attempt('registry',()=>registry(journal.planId&&!planDeleted?[...originals,journal.planId].sort():originals));
  await attempt('retained-issue-unchanged',async()=>{for(let n=0;n<2;n++)expect(await issue()).toEqual(prepared.originalIssue);});await attempt('preferences',async()=>{if(ready)for(let n=0;n<2;n++)expect(await read('getCapacitySettings')).toEqual(prefs);});await attempt('original-drafts',async()=>{if(ready)for(const originalId of originals)await drafts(originalId);});
  await attempt('owned-source-final',async()=>{if(!planDeleted)expect(await ownPlan()).toEqual(prepared.originalPlan);});

  journal.integrityPreserved=ready&&errors.length===0;journal.resources={planRetained:!!journal.planId&&!planDeleted,issueRetained:true};if(errors.length)journal.completed=false;save();rpc.stop();if(errors.length)throw new AggregateError([...(bodyError?[bodyError]:[]),...errors],'Packed upgrade and independent audits failed; exact owned resources retained');
 }
});
