import fs from 'node:fs';
import {test,expect as baseExpect} from '../../fixtures/forge';
import {loadEnv} from '../../data/env.mjs';
import {getHarnessLaunchReceipt,assertLoggedIn} from '../../forge/browser';
import {getTarget} from '../../config/targets';
import {enterForgeSurface} from '../../forge/frame';
import {scheduleFields,LZPT_PLAN} from './forecast-fixture';
import {callEnvelope} from './campaign-ui';
import {replayHeaders} from './replay-headers.mjs';
import {createRollingReadBudget} from './rolling-read-budget.mjs';
import {continueUntilFinished} from './paced-ui-transport.mjs';
import {boundedRead} from './paced-read-transport.mjs';
import {hookReadCost,resolverReadCost} from './seventeenth-read-cost.mjs';
import {createCapacityWireLifecycle,assertCapacityWireFresh} from './capacity-wire-lifecycle.mjs';
import {capacityWireIdentity,capacityWireToken,expectedCapacityWire,verifiedAcquisition,guardedCapacityRoute,settledRequest,safeTransportFailure,browserPrincipal} from './seventeenth-wire-acquisition.mjs';
import {serializeForgeResponse,ForgeResponseRecordError} from './forge-response-record.mjs';
import {pinned,sha,recoveryAdmission,recoveryUiClass,recoverThree} from './eighteenth-recovery-contract.mjs';
const acceptance=recoveryAdmission();
const cleanupTest=acceptance?test:test.skip;
const expect=baseExpect.configure({timeout:600000});
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const BASE='https://wolfaenpak.atlassian.net';
const expectedPrefs=pinned.preferences;
// Existing measured full-5300 cleanup reservations are conservative for these one-row jobs.
const cleanupReadCost=(key:string)=>key==='cancelSponsorReportCapture'?192:key==='deletePlan'?768:resolverReadCost(key);
async function openPlans(page:any){await page.setViewportSize({width:1600,height:1100});await assertLoggedIn(page);const target=getTarget('lz-ppm-dashboard');await page.goto(target.deepLink(target.envId)!,{waitUntil:'domcontentloaded'});await page.locator('iframe[data-testid="hosted-resources-iframe"], iframe[title*="Iframe"]').first().waitFor({state:'attached',timeout:600000});const surface=await enterForgeSurface(page,{surface:'custom',timeout:600000});if(surface.kind!=='custom')throw new Error('No Forge frame');await surface.frame.getByText('LZPT Scenarios',{exact:true}).first().waitFor({timeout:600000});return surface.frame;}
function actualResponse(page:any,key:string,planId?:string){return page.waitForResponse((r:any)=>{const c=callEnvelope(r.request())?.variables?.input?.payload?.call;return c?.functionKey===key&&(!planId||c.payload?.planId===planId);},{timeout:600000}).then(async(r:any)=>{expect(r.status()).toBe(200);await r.finished();const {data}=serializeForgeResponse(await r.text(),{requestToken:capacityWireToken({data:callEnvelope(r.request())}),requestHeaders:await r.request().allHeaders()}),body=data.data?.invokeExtension?.response?.body;expect(data.data?.invokeExtension?.success).toBe(true);const errors=data.data?.invokeExtension?.errors??data.errors??null;expect(errors==null||Array.isArray(errors)&&errors.length===0).toBe(true);expect(body?.success,body?.error).toBe(true);return body;});}
test.describe.configure({retries:0,timeout:7200000});
cleanupTest('eighteenth exact three retained fixtures: approved owner staging cleanup then plan and owned Jira deletion',async({page},info)=>{
 if(!acceptance)throw new Error('Externally approved exact recovery required');
 await page.context().tracing.stop();
 const receipt=getHarnessLaunchReceipt(page.context());if(receipt?.mode!=='portable-chrome152')throw new Error('Known portable receipt required');expect(receipt).toMatchObject({mode:'portable-chrome152',browserVersion:'152.0.7977.76',principalSha256:'b4cb5211a5e4d44c9f3a6bc909588c2fe62162358d4b0c04da52aa6977433769',executableSha256:'755178ee89130a6f1c94cc4ecb2289fe74240db3e7efe9ec69a6cfcd4b93a6ee',frameworkSha256:'bfea9981cc61dfa72d847c920f274e4e96e362954f451198d8ee1650cbefb2e6'});expect(receipt!.uiVersion).toBe(process.env.LZ_EXPECTED_UI_VERSION);
 const journal:any={phase:'eighteenth-exact-recovery',acceptance,receipt,traceDiscarded:true,events:[],budgetEvents:[],wireEvents:[],uiRequests:[],mutationCalls:0,completed:false};fs.mkdirSync(info.outputDir,{recursive:true});const save=()=>fs.writeFileSync(info.outputPath('eighteenth-recovery.json'),JSON.stringify(journal,null,2));const record=(stage:string,value:any={})=>{journal.events.push({stage,time:new Date().toISOString(),value});save();};save();
 const budget=createRollingReadBudget({capacity:3000,windowMs:61000,onEvent:(event:any)=>{journal.budgetEvents.push(event);save();}});page.setDefaultTimeout(600000);page.setDefaultNavigationTimeout(600000);loadEnv();
 let planId=pinned.fixtures[0].planId,armedPlanDelete=false,planDeleteDispatches=0;
 const uiObservations=new WeakMap<any,any>(),departureObservers=new Set<(value:any)=>void>();
 const forbiddenUi:any[]=[],uiRouteErrors:any[]=[],uiPending=new Set<Promise<any>>();let uiCount=0;const blockUiWrites=async(route:any)=>{const call=callEnvelope(route.request())?.variables?.input?.payload?.call,classification=recoveryUiClass(call,armedPlanDelete?planId:null);if(classification==='forbidden'){forbiddenUi.push(call);record('forbidden-ui-write-blocked',call);await route.abort('blockedbyclient');return;}if(classification==='unrelated'){await route.continue();return;}const requestId=++uiCount,request=route.request(),timing:any={requestedAtMs:Date.now()};uiObservations.set(request,timing);const actualRoute={request:()=>request,continue:async()=>{if(classification==='approved-plan-delete'){expect(armedPlanDelete).toBe(true);armedPlanDelete=false;planDeleteDispatches++;record('actual-plan-delete-dispatch',{payload:call.payload,dispatchedAtMs:Date.now()});}return route.continue();}};const guardedRoute=guardedCapacityRoute(actualRoute,timing,{wire:{url:request.url(),data:callEnvelope(request)}});const work=Promise.resolve().then(()=>budget.run(`ui:${requestId}:${call.functionKey}`,cleanupReadCost(call.functionKey),()=>continueUntilFinished(page,guardedRoute,{onObserved:async(result:any)=>{timing.completedAtMs=Date.now();const observed:any={requestId,key:call.functionKey,planId:call.payload?.planId??null,...timing,...result};if(result.state==='finished'){const response=await route.request().response();observed.httpStatus=response?.status()??null;let data:any;try{const serialized=serializeForgeResponse(response?await response.text():'',{requestToken:capacityWireToken({data:callEnvelope(request)}),requestHeaders:await request.allHeaders()});const {data:parsed,...evidence}=serialized;data=parsed;Object.assign(observed,evidence);}catch(error){if(error instanceof ForgeResponseRecordError)Object.assign(observed,error.receipt);timing.observed=observed;journal.uiRequests.push(observed);save();for(const observe of departureObservers)observe(observed);throw error;}const extension=data?.data?.invokeExtension;observed.outerSuccess=extension?.success??null;observed.body=extension?.response?.body??null;observed.errors=extension?.errors??data?.errors??null;if(observed.httpStatus!==200||observed.outerSuccess!==true||(observed.errors!=null&&(!Array.isArray(observed.errors)||observed.errors.length>0))||observed.body?.success===false||observed.responseBytes>8388608)uiRouteErrors.push(`${call.functionKey}: unsuccessful actual UI response`);}else uiRouteErrors.push(`${call.functionKey}: ${result.error}`);timing.observed=observed;journal.uiRequests.push(observed);save();for(const observe of departureObservers)observe(observed);}})));uiPending.add(work);try{await work;}catch(error){uiRouteErrors.push(String(error));record('ui-budget-or-transport-error',{requestId,error:String(error)});await route.abort('failed').catch(()=>{});}finally{uiPending.delete(work);}};await page.route('**/*',blockUiWrites);
 const drainUi=async()=>{const deadline=performance.now()+600000;while(uiPending.size){expect(performance.now()<deadline,'bounded UI queue drain').toBe(true);await Promise.race([Promise.allSettled([...uiPending]),sleep(1000)]);}};
 const stopUi=async()=>{await drainUi();expect(uiRouteErrors).toEqual([]);expect(forbiddenUi).toEqual([]);if(page.url()!=='about:blank'){let identified=false;for(const frame of page.frames()){expect(await frame.locator('button[aria-label="Back to plans"][title="Back to plans"]').count(),'Recovery never mounts PlanView').toBe(0);const capacity=frame.locator('[data-testid="capacity-view"]');if(await capacity.count()&&await capacity.isVisible()){await expect(capacity.getByRole('heading',{name:'Portfolio capacity',exact:true})).toBeVisible();identified=true;}const card=frame.getByText('LZPT Scenarios',{exact:true}).first();if(await card.count()&&await card.isVisible())identified=true;}expect(identified).toBe(true);await page.goto('about:blank');await drainUi();expect(uiRouteErrors).toEqual([]);}};
 const acquire=async()=>{try{
  await stopUi();expect(uiRouteErrors).toEqual([]);expect(forbiddenUi).toEqual([]);
  const principal=await browserPrincipal(page,BASE);expect(principal.httpStatus).toBe(200);expect(principal.accountId).toBe(expectedCapacityWire.accountId);record('wire-browser-principal',principal);
  const frame=await openPlans(page);const pending=page.waitForResponse((response:any)=>callEnvelope(response.request())?.variables?.input?.payload?.call?.functionKey==='getCapacitySettings',{timeout:600000});pending.catch(()=>{});await frame.getByRole('button',{name:'Capacity',exact:true}).click();const response=await pending;await response.finished();await drainUi();const request=response.request(),timing=uiObservations.get(request);expect(uiRouteErrors).toEqual([]);const principalAfter=await browserPrincipal(page,BASE);expect(principalAfter.httpStatus).toBe(200);expect(principalAfter.accountId).toBe(principal.accountId);record('wire-browser-principal-after',principalAfter);
  const candidate=verifiedAcquisition({wire:{url:request.url(),data:callEnvelope(request),headers:await request.allHeaders()},accountId:principal.accountId,timing});
  await stopUi();return candidate;
 }catch(error){if((error as any)?.receipt)record('wire-acquisition-failure',(error as any).receipt);throw error;}};
 const lifecycle=createCapacityWireLifecycle({acquire,expected:{...expectedCapacityWire,preferences:expectedPrefs},identityOf:capacityWireIdentity,tokenOf:capacityWireToken,onEvent:(event:any)=>{journal.wireEvents.push({...event,recordedAt:new Date().toISOString()});save();}});
 const hook=async(query:any)=>budget.run(`hook:${query.what}:${query.planId??'registry'}`,hookReadCost(query),async()=>{const url=new URL(process.env.LZ_PPM_TESTHOOK_URL!);expect(url.protocol).toBe('https:');for(const[k,v]of Object.entries(query))url.searchParams.set(k,String(v));const startedMs=Date.now(),value=await boundedRead(url,{headers:{Authorization:`Bearer ${process.env.HARNESS_SECRET}`}});record('hook-response',{query,startedMs,returnedMs:Date.now(),...value,responseSha256:sha(value.raw)});expect(value.httpStatus).toBe(200);expect(value.body).toBeTruthy();return value.body;});
 const allowed=new Set(['getCapacitySettings','getDraft','getActiveDrafts','getLockStatus','getSponsorReportCapture','getBaseline','listSponsorReports','cancelSponsorReportCapture']);
 const rawInvoke=async(key:string,payload:any={},cost=cleanupReadCost(key))=>lifecycle.run({budget,label:`rpc:${key}`,cost,dispatch:async(wire:any,wireReceipt:any)=>{
  expect(allowed.has(key)).toBe(true);if(key==='getCapacitySettings')expect(payload).toEqual({});else{expect([...pinned.originals,...pinned.fixtures.map((f:any)=>f.planId)]).toContain(payload.planId);if(['getSponsorReportCapture','cancelSponsorReportCapture'].includes(key)){const f=pinned.fixtures.find((f:any)=>f.planId===payload.planId);expect(f).toBeTruthy();expect(payload).toEqual({planId:f.planId,jobId:f.job.id});}}
  const envelope=structuredClone(wire.data);envelope.variables.input.payload.call={functionKey:key,payload};
  const headers=replayHeaders(wire.headers),requestData=JSON.stringify(envelope);let startedMs=0;try{const response=await settledRequest(()=>{assertCapacityWireFresh(wire,{tokenOf:capacityWireToken,now:Date.now()});startedMs=Date.now();return page.request.post(wire.url,{headers,data:requestData,maxRetries:0,maxRedirects:0,timeout:60000});},()=>{if(['cancelSponsorReportCapture'].includes(key)){journal.mutationCalls++;journal.lastWriteStartedMs=startedMs;record('actual-cleanup-dispatch',{payload,reservedUnits:cost,startedMs,wireReceipt});console.log('OWNER_CLEANUP',JSON.stringify({key,startedAt:new Date(startedMs).toISOString(),reservedUnits:cost}));}});const text=await response.text();let serialized:any;try{serialized=serializeForgeResponse(text,{requestToken:capacityWireToken(wire),requestHeaders:wire.headers});}catch(error){if(error instanceof ForgeResponseRecordError)record(key,{wireReceipt,startedMs,returnedMs:Date.now(),httpStatus:response.status(),...error.receipt});throw error;}const {data,...evidence}=serialized;
   const returnedMs=Date.now(),extension=data?.data?.invokeExtension;const observed={wireReceipt,startedMs,returnedMs,elapsedMs:returnedMs-startedMs,...evidence,httpStatus:response.status(),outerSuccess:extension?.success??null,body:extension?.response?.body??null,errors:extension?.errors??data?.errors??null,traceId:response.headers()['atl-traceid']??null};record(key,observed);return observed;
  }catch(error){const safe=error instanceof ForgeResponseRecordError?error:safeTransportFailure(error,'report-rpc');record('transport-error',{key,...safe.receipt});throw safe;}finally{if(['cancelSponsorReportCapture'].includes(key)){journal.lastWriteReturnedMs=Date.now();save();}}
 }});
 const invoke=async(key:string,payload:any={})=>{const result=await rawInvoke(key,payload);expect(result.httpStatus).toBe(200);expect(result.outerSuccess).toBe(true);expect(result.errors==null||Array.isArray(result.errors)&&result.errors.length===0).toBe(true);expect(result.body).toBeTruthy();return result.body;};
 const read=async(key:string,payload:any={})=>{const value=await invoke(key,payload);expect(value.success,value.error).toBe(true);return value;};

 const principal=async()=>{const p=await browserPrincipal(page,BASE);record('principal',p);expect(p.httpStatus).toBe(200);return p.accountId;};
 const originalSource=async()=>{const s=await hook({what:'plan',planId:LZPT_PLAN});const basis={issues:scheduleFields(s.issues),sources:s.meta.sources,calendarKey:s.meta.calendarKey,holidayYears:s.meta.holidayYears,milestones:s.meta.milestones,protectionEnabled:s.meta.protectionEnabled};expect(s.issues).toHaveLength(45);expect(sha(JSON.stringify(basis))).toBe(pinned.sourceFingerprint);return s;};
 const issue=async(method:string,key:string)=>{expect(['GET','DELETE']).toContain(method);expect(pinned.fixtures.map((f:any)=>f.issue)).toContain(key);const url=`${BASE}/rest/api/3/issue/${key}${method==='GET'?'?fields=project,issuetype,labels,summary,customfield_10015,duedate,customfield_10180,issuelinks,parent':''}`;const startedMs=Date.now();try{const r=await settledRequest(()=>page.request.fetch(url,{method,maxRetries:0,maxRedirects:0,timeout:60000}),()=>{record('jira-dispatch',{method,key,startedMs});if(method==='DELETE')journal.mutationCalls++;});const raw=await r.text();const result={httpStatus:r.status(),body:raw?JSON.parse(raw):null};record('jira-response',{method,key,startedMs,returnedMs:Date.now(),responseSha256:sha(raw),responseBytes:Buffer.byteLength(raw),...result});return result;}catch(error){const safe=safeTransportFailure(error,'report-rpc');record('jira-transport-error',{method,key,...safe.receipt});throw safe;}};
 const otherSources=async()=>{const values=[];for(const id of pinned.originals.filter((id:string)=>id!==LZPT_PLAN))values.push(await hook({what:'plan',planId:id}));expect(values.map(v=>v.issues.length)).toEqual([54,5300]);return values;};
 const removed=new Set<string>();let failure:any,failed=false,originalStanding:any,otherStanding:any;
 const io={principal,originalSource,otherSources,registry:async()=>{const r=await hook({what:'plans'});return r.plans;},preferences:()=>read('getCapacitySettings'),source:(id:string)=>hook({what:'plan',planId:id}),emptyDrafts:async(id:string)=>{expect(await read('getDraft',{planId:id})).toEqual({success:true,draft:null});expect(await read('getActiveDrafts',{planId:id})).toEqual({success:true,drafts:{}});expect(await read('getLockStatus',{planId:id})).toMatchObject({locked:false});},baseline:(id:string)=>invoke('getBaseline',{planId:id}),reports:(id:string)=>read('listSponsorReports',{planId:id}),job:(f:any)=>read('getSponsorReportCapture',{planId:f.planId,jobId:f.job.id}),probe:(f:any)=>hook({what:'reportCaptureState',planId:f.planId,jobId:f.job.id}),cancel:(f:any)=>read('cancelSponsorReportCapture',{planId:f.planId,jobId:f.job.id}),issue,
 deletePlan:async(f:any)=>{planId=f.planId;const result=await lifecycle.withExport(async()=>{const frame=await openPlans(page);const card=frame.locator('.lz-card').filter({has:frame.getByText(f.name,{exact:true})});await expect(card).toHaveCount(1);await card.getByTitle('More',{exact:true}).click();await card.getByRole('button',{name:'Delete plan',exact:true}).click();const dialog=frame.getByRole('dialog');await expect(dialog).toContainText(f.name);await expect(dialog).toContainText('Delete Plan');const before=planDeleteDispatches;armedPlanDelete=true;const pending=actualResponse(page,'deletePlan',f.planId);pending.catch(()=>{});await dialog.getByRole('button',{name:'Delete',exact:true}).click();const result=await pending;expect(planDeleteDispatches).toBe(before+1);removed.add(f.planId);await drainUi();await expect(card).toHaveCount(0);await page.screenshot({path:info.outputPath(`after-${f.kind}-plan-delete.png`),fullPage:true});await stopUi();return result;},{maxMs:600000});return result;}};
 try{await stopUi();expect(page.context().pages()).toEqual([page]);record('bootstrap-quiet-start');const initial=uiCount;await budget.run('bootstrap-outstanding-allowance',3000,()=>sleep(30000));await budget.run('bootstrap-window-cleared',1,async()=>{});expect(uiCount).toBe(initial);await lifecycle.ensureFresh();originalStanding=await originalSource();otherStanding=await otherSources();const result=await recoverThree({approval:acceptance,io,record});journal.result=result;journal.completed=true;}
 catch(error){failed=true;failure=error;record('body-error',{name:(error as any)?.name,message:String((error as any)?.message||error)});}
 finally{const errors:any[]=[];for(const [label,audit]of[
 ['stop-ui',stopUi],['principal',async()=>expect(await principal()).toBe(pinned.principal)],['standing-source',async()=>{if(originalStanding)expect(await originalSource()).toEqual(originalStanding);}],['other-original-sources',async()=>{if(otherStanding)expect(await otherSources()).toEqual(otherStanding);}],['preferences',async()=>expect(await read('getCapacitySettings')).toEqual(expectedPrefs)],['registry',async()=>{const rows=await io.registry();expect(rows.map((r:any)=>r.id).sort()).toEqual([...pinned.originals,...pinned.fixtures.map((f:any)=>f.planId).filter((id:string)=>!removed.has(id))].sort());}],['original-drafts',async()=>{for(const id of pinned.originals)await io.emptyDrafts(id);}],['retained-fixture-evidence',async()=>{
 const failures:any[]=[];
 for(const f of pinned.fixtures){
  const observations:Array<[string,()=>Promise<any>]>=[['source',()=>io.source(f.planId)],['jira',()=>issue('GET',f.issue)]];
  if(!removed.has(f.planId))observations.push(['job',()=>io.job(f)],['probe',()=>io.probe(f)]);
  for(const [kind,action]of observations){try{record('terminal-fixture-observation',{planId:f.planId,key:f.issue,kind,result:await action()});}catch(error){failures.push(error);record('terminal-fixture-observation-error',{planId:f.planId,kind,message:String((error as any)?.message||error)});}}
 }
 if(failures.length)throw new AggregateError(failures,'Some exact terminal observations unavailable');
 }]
 ]as const){try{await audit();}catch(error){errors.push(error);record('final-audit-error',{label,message:String((error as any)?.message||error)});}}
 await drainUi();if(uiRouteErrors.length||forbiddenUi.length)errors.push(new Error('Unsuccessful UI requests or unexpected writes'));budget.close();journal.finalBudget=budget.snapshot();journal.uiPlanDeleteDispatches=planDeleteDispatches;journal.completed=journal.completed&&!failed&&!errors.length;save();await page.unroute('**/*',blockUiWrites);if(failed||errors.length)throw new AggregateError([...(failed?[failure]:[]),...errors],'Exact recovery failed; no automatic retries or follow-on mutations');}
});
