import {settledScreenshot} from './settled-screenshot.mjs';
import fs from 'node:fs';
import {test,expect} from '../../fixtures/forge';
import {get,post} from '../../data/jira.mjs';
import {withOwnedSchedule,table} from './normalization-owned-fixture';
import {openPlan} from './forecast-fixture';
import {actualResponse,planning,currentUserResolver} from './campaign-ui';
test.describe.configure({retries:0,timeout:900000});
const state=async(key:string)=>{const r=await get(`/rest/api/3/issue/${key}?fields=status,resolution,resolutiondate,statuscategorychangedate`);return{id:r.id,statusCategory:r.fields.status.statusCategory.key,resolutionId:r.fields.resolution?.id??null,resolutionDate:r.fields.resolutiondate??null,statusCategoryChangedDate:r.fields.statuscategorychangedate??null};};
const outcomes=async(frame:any)=>{const work=await planning(frame);await work.getByRole('button',{name:'Forecast outcomes',exact:true}).click();return frame.locator('[data-testid="forecast-evaluation"]');};

test('completed private observation: real later resolution survives reopen and source forecast deletion; reopened Jira cannot rewrite earlier evidence',async({page},info)=>{
 await withOwnedSchedule(page,info,[{label:'retained completed outcome',duration:5,start:'2026-10-05',due:'2026-10-09'}],async(f)=>{
  const key=f.keys[0],beforeDates=await f.read(key),label='Prospective retained completion';let frame=await table(page,f.name),panel=await outcomes(frame);
  const rpc=currentUserResolver(page,c=>c?.functionKey==='captureForecast'&&c.payload?.planId===f.planId);
  const journal:any={key,steps:[]};const retain=()=>fs.writeFileSync(info.outputPath('completed-private-observation-journal.json'),JSON.stringify(journal,null,2));retain();
  try{
   expect((await state(key)).statusCategory).not.toBe('done');await panel.getByLabel('Forecast name',{exact:true}).fill(label);let pending=actualResponse(page,'captureForecast',f.planId);await panel.getByRole('button',{name:'Record working forecast',exact:true}).click();const forecast=(await pending).snapshot;expect(forecast.forecast.runs).toBe(300);journal.forecast=forecast;retain();
   const transitions=await get(`/rest/api/3/issue/${key}/transitions?expand=transitions.fields`),done=transitions.transitions.find((t:any)=>t.to.statusCategory.key==='done');expect(done,'actual owned workflow exposes Done').toBeTruthy();await post(`/rest/api/3/issue/${key}/transitions`,{transition:{id:done.id}});const completed=await state(key);expect(completed.statusCategory).toBe('done');expect(completed.resolutionId).toBeTruthy();expect(Date.parse(completed.resolutionDate)).toBeGreaterThan(Date.parse(forecast.takenAt));
   const actualDate=new Date(completed.resolutionDate).toISOString().slice(0,10);let item=panel.getByRole('heading',{name:label,exact:true}).locator('..'),privatePanel=item.locator('[data-testid="retained-forecast-observations"]');pending=actualResponse(page,'finishForecastObservation',f.planId);await privatePanel.getByRole('button',{name:'Record private observation',exact:true}).click();const receipt=await pending;
   expect(receipt.result).toMatchObject({state:'observed',actualFinish:actualDate,memberCount:1,hits:{p50:true,p80:true,p90:true}});expect(receipt.observation).toMatchObject({memberCount:1,scopeId:'plan'});await expect(privatePanel.locator('[data-testid="observation-receipt"]')).toContainText(`Observed Jira resolution completion ${actualDate}`);await expect(privatePanel.locator('[data-testid="observation-receipt"]')).toContainText('P80 hit');journal.completed=completed;journal.receipt=receipt;retain();await settledScreenshot(privatePanel,{path:info.outputPath('retained-completed-observation-receipt.png')});
   frame=await openPlan(page,f.name);panel=await outcomes(frame);await panel.getByRole('button',{name:'Load recorded forecasts',exact:true}).click();item=panel.getByRole('heading',{name:label,exact:true}).locator('..');privatePanel=item.locator('[data-testid="retained-forecast-observations"]');await privatePanel.getByRole('button',{name:'Load private observations',exact:true}).click();await expect(privatePanel.locator('[data-testid="retained-observation-result"]')).toHaveCount(0);pending=actualResponse(page,'finishForecastObservationReview',f.planId);await privatePanel.getByRole('button',{name:'Verify access and view retained result',exact:true}).click();const unchanged=await pending;expect(unchanged.state).toBe('unchanged');expect(unchanged.saved.result).toEqual(receipt.result);await expect(privatePanel.locator('[data-testid="retained-observation-result"]')).toContainText('Jira state matched at the latest check');
   // A real reopen changes current completion eligibility. Do not manufacture a
   // new resolution timestamp if this workflow keeps its old resolution field.
   const next=await get(`/rest/api/3/issue/${key}/transitions?expand=transitions.fields`),reopen=next.transitions.find((t:any)=>t.to.statusCategory.key==='indeterminate')||next.transitions.find((t:any)=>t.to.statusCategory.key!=='done');expect(reopen,'actual Done issue exposes an open transition').toBeTruthy();await post(`/rest/api/3/issue/${key}/transitions`,{transition:{id:reopen.id}});const reopened=await state(key);expect(reopened.statusCategory).not.toBe('done');journal.reopened=reopened;retain();
   pending=actualResponse(page,'finishForecastObservationReview',f.planId);await privatePanel.getByRole('button',{name:'Verify access and view retained result',exact:true}).click();const superseded=await pending;expect(superseded.state).toBe('superseded');expect(superseded.saved.result).toEqual(receipt.result);expect(superseded.checked.result.state).toBe('insufficient');await expect(privatePanel).toContainText('must not be treated as the current completion state');
   const work=frame.locator('[data-testid="planning-workspace"]');await work.getByRole('button',{name:'Scenarios & history',exact:true}).click();await work.getByRole('navigation',{name:'Retained captures'}).getByRole('button').filter({hasText:label}).click();await work.getByRole('button',{name:'Delete capture',exact:true}).click();await frame.getByRole('dialog',{name:'Delete capture',exact:true}).getByRole('button',{name:'Delete capture',exact:true}).click();await expect(work).toContainText('Capture deleted.');const absent=await rpc.invoke('getSnapshot',{planId:f.planId,snapshotId:forecast.id});expect(absent.success).toBe(true);expect(absent.snapshot).toBeNull();
   frame=await openPlan(page,f.name);panel=await outcomes(frame);await panel.getByRole('button',{name:'Load recorded forecasts',exact:true}).click();await expect(panel.getByRole('heading',{name:label,exact:true})).toHaveCount(0);
   const archive=panel.locator('details').filter({hasText:'Review private observations, including deleted forecasts'});await archive.locator('summary').first().click();privatePanel=archive.locator('[data-testid="retained-forecast-observations"]');await privatePanel.getByRole('button',{name:'Load private observations',exact:true}).click();await expect(privatePanel.getByRole('button',{name:'Verify access and view retained result',exact:true})).toHaveCount(1);await expect(privatePanel.locator('[data-testid="retained-observation-result"]')).toHaveCount(0);
   pending=actualResponse(page,'finishForecastObservationReview',f.planId);await privatePanel.getByRole('button',{name:'Verify access and view retained result',exact:true}).click();const afterDeletion=await pending;expect(afterDeletion.state).toBe('superseded');expect(afterDeletion.saved.result).toEqual(receipt.result);expect(afterDeletion.checked.result.state).toBe('insufficient');await expect(privatePanel).toContainText(`Observed Jira resolution completion ${actualDate}`);await expect(privatePanel).toContainText('still open or has been reopened');
   pending=actualResponse(page,'getForecastObservationEvidence',f.planId);await privatePanel.getByRole('button',{name:'Show checked evidence',exact:true}).click();const evidence=await pending;expect(evidence.state).toBe('read');expect(evidence.rows).toHaveLength(1);expect(evidence.rows[0].saved).toMatchObject({...completed,readable:true});expect(evidence.rows[0].checked).toMatchObject({...reopened,readable:true});await expect(privatePanel.locator('tbody tr td').nth(0)).toHaveText(completed.id);await expect(privatePanel.locator('tbody tr td').nth(1)).toContainText(completed.resolutionDate);await expect(privatePanel.locator('tbody tr td').nth(2)).toContainText(reopened.statusCategory);await settledScreenshot(privatePanel,{path:info.outputPath('completed-evidence-after-source-deletion.png')});
   expect(await f.read(key)).toEqual(beforeDates);journal.steps.push({name:'after-source-deletion',review:afterDeletion,evidence});journal.originalScheduleUnchanged=true;retain();
  }finally{rpc.stop();}
 });
});
