import {settledScreenshot} from './settled-screenshot.mjs';
import {gunzipSync} from 'node:zlib';
import {test,expect} from '../../fixtures/forge';
import {getTestState} from '../../testhook/client';
import {withForecastFixture,openPlan,scheduleFields} from './forecast-fixture';
import {withOwnedSchedule,table} from './normalization-owned-fixture';
test.describe.configure({retries:0,timeout:600000});
const call=(req:any)=>{try{let raw=req.postDataBuffer();if(raw?.[0]===31&&raw?.[1]===139)raw=gunzipSync(raw);return JSON.parse(raw.toString()).variables?.input?.payload?.call;}catch{return null;}};
const result=(page:any,name:string,planId:string)=>page.waitForResponse((r:any)=>{const c=call(r.request());return c?.functionKey===name&&c.payload?.planId===planId;},{timeout:90000}).then(async(r:any)=>{expect(r.status()).toBe(200);await r.finished();const b=(await r.json()).data.invokeExtension.response.body;expect(b.success).toBe(true);return b;});
const planning=async(frame:any)=>{await frame.getByRole('button',{name:/^Planning/i}).first().click();await expect(frame.locator('[data-testid="tab-loading-overlay"]')).toHaveCount(0);return frame.locator('[data-testid="planning-workspace"]');};
async function date(frame:any,within:any,label:string,iso:string){await within.getByRole('button',{name:label,exact:true}).click();const cal=frame.locator('.lz-datepicker');const[y,m]=iso.split('-').map(Number);const months=['January','February','March','April','May','June','July','August','September','October','November','December'];for(let n=0;n<30;n++){const txt=(await cal.locator('span').first().textContent()).trim();if(txt===`${months[m-1]} ${y}`)break;const[a,b]=txt.split(' ');await cal.getByRole('button',{name:Number(b)*12+months.indexOf(a)<y*12+m-1?'Next month':'Previous month',exact:true}).click();}await expect(cal.locator('span').first()).toHaveText(`${months[m-1]} ${y}`);await cal.getByRole('button',{name:iso,exact:true}).click();}

test('sensitivity: real full-network counterfactual distinguishes early variability from causal finish movement',async({page},info)=>{
 await withForecastFixture(page,'sensitivity',async(f)=>{
  const original=scheduleFields((await getTestState('lz-ppm',{what:'plan',planId:f.planId})).issues);const frame=await openPlan(page,f.name);await frame.getByRole('button',{name:/^Dashboard/i}).first().click();await expect(frame.locator('[data-testid="tab-loading-overlay"]')).toHaveCount(0);const panel=frame.locator('[data-testid="finish-sensitivity"]');await panel.getByRole('button',{name:'Test finish sensitivity',exact:true}).click();await expect(panel).toContainText('settled finish 2026-10-12');await expect(panel).toContainText('3 tasks tested');await panel.getByRole('button',{name:'Show all tested tasks',exact:true}).click();await expect(panel.locator('[data-testid="finish-effect"]')).toHaveCount(3);
  const early=panel.locator('[data-testid="finish-effect"][data-key="LZPT-215"]');await expect(early.locator('td').nth(0)).toHaveText('2026-10-12 (0 calendar days earlier)');await expect(early.locator('td').nth(1)).toHaveText('2026-10-12 (0 calendar days later)');const terminal=panel.locator('[data-testid="finish-effect"][data-key="LZPT-209"]');await expect(terminal.locator('td').nth(0)).toHaveText('2026-10-09 (3 calendar days earlier)');await expect(terminal.locator('td').nth(1)).toHaveText('2026-10-13 (1 calendar days later)');
  await settledScreenshot(panel,{path:info.outputPath('finish-sensitivity-causal-proof.png')});expect(scheduleFields((await getTestState('lz-ppm',{what:'plan',planId:f.planId})).issues)).toEqual(original);
 });
});

test('scenario: saved calendar and scope alternatives preserve original and working schedules and compare actual forecasts',async({page},info)=>{
 await withOwnedSchedule(page,info,[{label:'scenario predecessor',duration:5,start:'2026-03-02',due:'2026-03-06'},{label:'scenario successor',duration:5,start:'2026-03-09',due:'2026-03-13'}],async(f)=>{
  const[pred,succ]=f.keys;let frame=await table(page,f.name);const sourceBefore=scheduleFields((await getTestState('lz-ppm',{what:'plan',planId:f.planId})).issues);const jiraBefore=await Promise.all(f.keys.map((key:string)=>f.read(key)));let work=await planning(frame);
  const baseRead=result(page,'getSnapshot',f.planId);await work.getByLabel('Capture name').fill('Original decision');await work.getByRole('button',{name:'Capture working plan',exact:true}).click();const base=(await baseRead).snapshot;await expect(work.locator('[data-testid="snapshot-detail"] h3').first()).toHaveText('Original decision');
  await work.getByRole('button',{name:'Create alternative',exact:true}).click();let editor=work.locator('[data-testid="scenario-editor"]');await editor.getByLabel('Alternative name',{exact:true}).fill('Holiday and six days');await editor.getByLabel(`${pred} duration`,{exact:true}).fill('6');await editor.getByRole('textbox',{name:'Holiday dates, one YYYY-MM-DD per line',exact:true}).fill('2026-03-04');await expect(editor.getByRole('button',{name:'Save new scenario',exact:true})).toBeDisabled();await editor.getByRole('button',{name:'Preview alternative',exact:true}).click();let preview=editor.locator('[data-testid="scenario-preview"]');await expect(preview.locator('tbody tr').filter({hasText:pred})).toContainText('2026-03-10');await expect(preview.locator('tbody tr').filter({hasText:succ})).toContainText('2026-03-11');await expect(preview.locator('tbody tr').filter({hasText:succ})).toContainText('2026-03-17');await settledScreenshot(preview,{path:info.outputPath('scenario-calendar-preview.png')});
  await editor.getByRole('button',{name:'Save new scenario',exact:true}).click();await expect(editor).toHaveCount(0);let comparison=work.locator('[data-testid="scenario-comparison"]');await expect(comparison).toContainText('Original decision compared with Holiday and six days');await expect(comparison.locator('tr').filter({hasText:'Scheduled finish'})).toHaveText('Scheduled finish2026-03-132026-03-17');await comparison.getByRole('button',{name:'Calculate both forecasts',exact:true}).click();const p90=comparison.locator('tr').filter({hasText:/^P90/});await expect(p90.locator('td').nth(1)).toHaveText(/^\d{4}-\d{2}-\d{2}$/);expect((await p90.locator('td').nth(1).innerText())>(await p90.locator('td').nth(0).innerText())).toBe(true);await settledScreenshot(comparison,{path:info.outputPath('scenario-saved-forecast-comparison.png')});
  const unchanged=result(page,'getSnapshot',f.planId);await work.getByRole('navigation',{name:'Retained captures'}).getByRole('button').filter({hasText:'Original decision'}).click();const original=(await unchanged).snapshot;expect(original.hash).toBe(base.hash);expect(original.issues).toEqual(base.issues);expect(original.calendar).toEqual(base.calendar);
  await work.getByRole('button',{name:'Create alternative',exact:true}).click();editor=work.locator('[data-testid="scenario-editor"]');await editor.getByLabel('Alternative name',{exact:true}).fill('Successor only');await editor.getByRole('checkbox',{name:`Include ${pred}`,exact:true}).click();await date(frame,editor,`${succ} start`,'2026-03-02');await editor.getByRole('button',{name:'Preview alternative',exact:true}).click();preview=editor.locator('[data-testid="scenario-preview"]');await expect(preview).toContainText(`Removed links: ${pred} → ${succ}`);await expect(preview.locator('tbody tr')).toHaveCount(1);await expect(preview.locator('tbody tr')).toContainText('2026-03-06');await editor.getByRole('button',{name:'Save new scenario',exact:true}).click();await expect(editor).toHaveCount(0);comparison=work.locator('[data-testid="scenario-comparison"]');await expect(comparison.locator('tr').filter({hasText:'Leaf tasks'})).toHaveText('Leaf tasks21');await expect(comparison.locator('tr').filter({hasText:'Scheduled finish'})).toHaveText('Scheduled finish2026-03-132026-03-06');
  frame=await openPlan(page,f.name);work=await planning(frame);await work.getByRole('navigation',{name:'Retained captures'}).getByRole('button').filter({hasText:'Successor only'}).click();await expect(work.locator('[data-testid="snapshot-detail"] h3').first()).toHaveText('Successor only');await expect(work.locator('[data-testid="snapshot-detail"]')).toContainText('1 retained issues');await settledScreenshot(work,{path:info.outputPath('scenario-scope-reopen.png')});expect(scheduleFields((await getTestState('lz-ppm',{what:'plan',planId:f.planId})).issues)).toEqual(sourceBefore);expect(await Promise.all(f.keys.map((key:string)=>f.read(key)))).toEqual(jiraBefore);
 },true);
});
