import {settledScreenshot} from './settled-screenshot.mjs';
import {test,expect} from '../../fixtures/forge';
import {withOwnedSchedule,table,editDuration,save} from './normalization-owned-fixture';
import {openPlan} from './forecast-fixture';
test.describe.configure({retries:0,timeout:600000});
test('baseline: shortened live task visibly exposes retained original ghost span after reopen',async({page},info)=>{
 await withOwnedSchedule(page,info,[{label:'visible baseline span',duration:5,start:'2026-10-05',due:'2026-10-09'}],async(f)=>{
  const key=f.keys[0],original=await f.read(key);let frame=await table(page,f.name);await frame.getByRole('button',{name:/^Planning/i}).first().click();let work=frame.locator('[data-testid="planning-workspace"]');await work.getByLabel('Capture name').fill('Visible original span');await work.locator('form').getByRole('combobox').first().click();await frame.getByRole('option',{name:'Baseline',exact:true}).click();await work.getByRole('button',{name:'Capture working plan',exact:true}).click();await expect(work.locator('[data-testid="snapshot-detail"] h3').first()).toHaveText('Visible original span');await work.getByRole('button',{name:'Use as baseline',exact:true}).click();await expect(work).toContainText('Baseline set to Visible original span');
  await frame.getByRole('button',{name:/^Table/i}).first().click();await editDuration(frame,key,'3');await save(frame);frame=await openPlan(page,f.name);await frame.getByRole('button',{name:/^Table/i}).first().click();const reopened=frame.locator(`[data-testid="table-row"][data-row-key="${key}"]`);await expect(reopened).toHaveAttribute('data-row-duration','3');await expect(reopened).toHaveAttribute('data-row-due','2026-10-07');await frame.getByRole('button',{name:/^Gantt/i}).first().click();const show=frame.getByTitle('Show baseline ghost bars');if(await show.count())await show.click();await expect(frame.locator('[data-testid="tab-loading-overlay"]')).toHaveCount(0);
  const row=frame.locator(`[data-testid="gantt-row"][data-row-key="${key}"]`),ghost=row.locator('[data-testid="gantt-baseline-ghost"]'),bar=row.locator('[data-testid="gantt-bar"]');await expect(ghost).toHaveAttribute('title',`Baseline — ${key} was scheduled 2026-10-05 → 2026-10-09`);await expect(bar).toBeVisible();const old=await ghost.boundingBox(),live=await bar.boundingBox();expect(old).toBeTruthy();expect(live).toBeTruthy();expect(old!.x+old!.width-live!.x-live!.width,'two original working days must remain visibly exposed beyond the shorter live bar').toBeGreaterThan(10);await settledScreenshot(page,{subject:ghost,path:info.outputPath('baseline-ghost-exposed-after-reopen.png'),fullPage:true,animations:'disabled'});await info.attach('real-rendered-bounds',{body:JSON.stringify({key,baseline:{start:'2026-10-05',due:'2026-10-09',duration:5,bounds:old},working:{start:'2026-10-05',due:'2026-10-07',duration:3,bounds:live}}),contentType:'application/json'});expect(await f.read(key)).toEqual(original);
 });
});
