import assert from 'node:assert/strict';
import {expect} from '../../fixtures/forge';
import {getTarget} from '../../config/targets';
import {callEnvelope} from './campaign-ui';
import {replayHeaders} from './replay-headers.mjs';
import {serializeForgeResponse} from './forge-response-record.mjs';
import {createReportCaptureObserver} from './report-capture-observer.mjs';
import {createReportDocumentIdentity} from './report-document-identity.mjs';
import {departOwnedPlan,armPresenceLeave} from './owned-plan-departure.mjs';
import {admitPrivateSource,admitPrivateFork,admitPrivateForkIdentity,privateAccount} from './private-report-witness-contract.mjs';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const reportKeys=new Set(['captureSponsorReport','advanceSponsorReportCapture','getSponsorReportCapture','cancelSponsorReportCapture']);
const readKeys=new Set(['getPlan','getSimulationModel','getSnapshot','getPlanCalendar','getCapacitySettings','getDraft','getActiveDrafts','getSponsorReportCapture','getSponsorReport','getSponsorReportPage','listSponsorReports','getBaseline']);
/** New standalone witness. Shared report adapter and physical probe retain their original guards. */
export function privateWitnessSession(page:any,{record,timeoutMs=120000}:any){
 const target=getTarget('lz-ppm-dashboard'),appId=target.appId.split('/').at(-1)!,extensionId=`ari:cloud:ecosystem::extension/${appId}/${target.envId}/static/ppm-dashboard`;
 const documents=createReportDocumentIdentity({page,appId,envId:target.envId,record,timeoutMs});
 const pending=new Set<Promise<any>>(),requests=new Map<any,any>(),beats=new Map<string,any>(),leaves=new Set<any>(),waiters=new Set<any>();
 let candidate:any=null,protocolQueue=Promise.resolve();
 let owner:any=null,poison:any=null,wire:any=null,serial=0,protocol:any=null,protocolPlan:any=null,disposed=false,busy=false;
 const fail=(phase:string)=>{poison??=Object.assign(new Error('Private witness outcome is uncertain; exact owned resources retained'),{reportState:{owner,phase}});record('private-witness-refused',{phase,owner});return poison;};
 const checked=()=>{if(poison)throw poison;if(disposed)throw new Error('Private witness session disposed');};
 const safeBody=async(response:any,privacy:any,identity:any)=>{const raw=await response.text(),serialized=serializeForgeResponse(raw,privacy);const {data,...receipt}=serialized;record('private-response',{...identity,httpStatus:response.status(),...receipt});assert.equal(response.status(),200);const outer=data?.data?.invokeExtension;assert.equal(outer?.success,true);assert(outer.errors==null||Array.isArray(outer.errors)&&!outer.errors.length);assert(data.errors==null||Array.isArray(data.errors)&&!data.errors.length);assert(outer.response?.body&&typeof outer.response.body==='object');return outer.response.body;};
 const enqueue=(work:()=>any)=>{protocolQueue=protocolQueue.then(work).catch(()=>{protocol?.fail(new Error('Private capture protocol failed'));fail('capture-protocol');});};
 const request=(req:any)=>{try{const envelope=callEnvelope(req),input=envelope?.variables?.input;if(input?.extensionId!==extensionId)return;const call=input.payload?.call;assert.equal(typeof call?.functionKey,'string');const value={requestId:++serial,key:call.functionKey,planId:call.payload?.planId??null,requestedAtMs:Date.now(),document:call.functionKey==='presenceBeat'?documents.capture(serial):null,envelope};requests.set(req,value);if(protocol&&call.payload?.planId===protocolPlan&&reportKeys.has(call.functionKey))enqueue(()=>protocol.request(req,call));}catch{fail('request-admission');}};
 const terminal=(req:any,failed:boolean)=>{const item=requests.get(req);if(!item)return;requests.delete(req);const task=(async()=>{
  try{assert(!failed,'Actual owned app request failed');const response=await req.response();assert(response);const headers=await req.allHeaders(),body=await item.body;
   const value={requestId:item.requestId,key:item.key,planId:item.planId,requestedAtMs:item.requestedAtMs,dispatchedAtMs:item.requestedAtMs,completedAtMs:Date.now(),state:'finished',httpStatus:response.status(),outerSuccess:true,errors:null,body};
   if(body.success===false)throw new Error('Unexpected actual UI refusal');
   wire={url:req.url(),headers:replayHeaders(headers),data:item.envelope};
   if(item.key==='presenceBeat'){if(beats.has(item.planId))await documents.release(beats.get(item.planId).binding);beats.set(item.planId,{value,binding:item.document});}
   record('private-ui-terminal',value);for(const observe of leaves)observe(value);for(const observe of waiters)observe(value);
  }catch{if(protocol&&item.planId===protocolPlan)protocol.transportFailure(req,new Error('Actual private report transport or evidence failed'));throw fail('ui-response');}
 })();pending.add(task);task.catch(()=>{}).finally(()=>pending.delete(task));};
 const response=(res:any)=>{const req=res.request(),item=requests.get(req);if(!item)return;item.body=(async()=>{const failed=await res.finished();assert.equal(failed,null);return safeBody(res,{requestToken:item.envelope.variables.input.payload.contextToken,requestHeaders:await req.allHeaders()},{requestId:item.requestId,key:item.key,planId:item.planId});})();item.body.catch(()=>{});if(protocol&&item.planId===protocolPlan&&reportKeys.has(item.key))enqueue(async()=>protocol.response(req,await item.body));};
 const finished=(req:any)=>terminal(req,false),failed=(req:any)=>terminal(req,true);page.on('request',request);page.on('response',response);page.on('requestfinished',finished);page.on('requestfailed',failed);
 const drain=async()=>{const deadline=Date.now()+timeoutMs;while(requests.size||pending.size){if(Date.now()>=deadline)throw fail('drain-timeout');await Promise.race([sleep(25),...(pending.size?[Promise.allSettled([...pending])]:[])]);}await protocolQueue;checked();await documents.settle();};
 const frame=()=>{const frames=page.frames().filter(documents.matches);assert.equal(frames.length,1);return frames[0];};
 const mounted=async()=>{if(page.url()==='about:blank')return null;const f=frame(),back=f.locator('button[aria-label="Back to plans"][title="Back to plans"]');if(!await back.count()||!await back.first().isVisible())return null;assert(owner);await expect(back).toHaveCount(1);await expect(f.getByText(owner.name,{exact:true})).toBeVisible();const beat=beats.get(owner.planId);assert(beat);assert.equal(beat.binding.frame,f);assert(await documents.current(beat.binding));assert.equal(beat.value.planId,owner.planId);assert.equal(beat.value.body.selfAccountId,privateAccount);assert.equal(beat.value.body.success,true);return{frame:f,back};};
 const nonPlan=async()=>{if(page.url()==='about:blank')return;const f=frame(),capacity=f.locator('[data-testid="capacity-view"]');if(await capacity.count()&&await capacity.isVisible())await expect(capacity.getByRole('heading',{name:'Portfolio capacity',exact:true})).toBeVisible();else await expect(f.getByText('LZPT Scenarios',{exact:true}).first()).toBeVisible();};
 const stop=async()=>{checked();assert(!busy);busy=true;try{await departOwnedPlan({planId:owner?.planId,drain,findMounted:mounted,confirmNonPlan:nonPlan,armLeave:()=>armPresenceLeave(leaves,{timeoutMs}),clickBack:async(m:any)=>m.back.click(),confirmUnmounted:async(m:any)=>{await expect(m.back).toHaveCount(0);await expect(m.frame.getByText('LZPT Scenarios',{exact:true}).first()).toBeVisible();},blank:async()=>page.goto('about:blank'),record});}catch{throw fail('safe-back');}finally{busy=false;}};
 const wait=(key:string,planId?:string)=>{checked();let timer:any,observe:any;const promise=new Promise<any>((resolve,reject)=>{observe=(value:any)=>{if(value.key===key&&(!planId||value.planId===planId)){clearTimeout(timer);waiters.delete(observe);resolve(value.body);}};waiters.add(observe);timer=setTimeout(()=>{waiters.delete(observe);reject(fail('response-deadline'));},timeoutMs);});promise.catch(()=>{});return{promise,dispose(){clearTimeout(timer);waiters.delete(observe);}};};
 const invoke=async(key:string,payload:any={},mutation=false)=>{if(mutation)checked();if(disposed)throw new Error('Private witness disposed');assert(wire,'An actual completed browser request must establish the current-user wire');assert(readKeys.has(key)||mutation&&['deleteSponsorReport','cancelSponsorReportCapture'].includes(key));if(payload.planId)assert(!mutation&&['getDraft','getActiveDrafts'].includes(key)&&['plan-msq9dg8l-gz6mz1','plan-mta3aw3t-6dyijd','plan-mtbrlh8n-7ghw8u'].includes(payload.planId)||owner&&payload.planId===owner.planId||owner?.kind==='private'&&payload.planId===owner.plan.simulationProvenance.sourcePlanId||candidate&&['getPlan','getSimulationModel'].includes(key)&&payload.planId===candidate.id);
  const data=structuredClone(wire.data);data.variables.input.payload.call={functionKey:key,payload};const token=data.variables.input.payload.contextToken;let expires:any;try{expires=JSON.parse(Buffer.from(token.split('.')[1],'base64url').toString()).exp;}catch{throw fail('wire-expiry-unavailable');}if(!Number.isSafeInteger(expires)||expires*1000-Date.now()<120000)throw fail('wire-too-old-unsent');
  const requestId=++serial;record('private-direct-intent',{requestId,key,payload});try{const response=await page.request.post(wire.url,{headers:wire.headers,data:JSON.stringify(data)}),body=await safeBody(response,{requestToken:token,requestHeaders:wire.headers},{requestId,key,planId:payload.planId??null});record('private-direct-terminal',{requestId,key,payload,body});return body;}catch{throw fail('direct-response');}
 };
 return {drain,stop,wait,invoke,frame,owner:()=>owner,failure:()=>poison,
  source(value:any,name:string){checked();assert.equal(owner,null);owner=admitPrivateSource(value,name);record('private-source-owner',owner);},
  async fork(action:()=>Promise<any>,inputs:any,readFresh:(plan:any)=>Promise<any>){checked();assert.equal(owner?.kind,'source');assert(!busy);busy=true;let admitted:any;try{
   await departOwnedPlan({planId:owner.planId,drain,findMounted:async()=>{const m=await mounted();assert(m);return m;},confirmNonPlan:async()=>{throw new Error('Source must be mounted before Create');},armLeave:()=>armPresenceLeave(leaves,{timeoutMs}),clickBack:async()=>{const ack=await action();record('private-fork-ack',ack);candidate=admitPrivateForkIdentity({ack,...inputs});const fresh=await readFresh(ack.plan);admitted=admitPrivateFork({ack,...inputs,...fresh});},confirmUnmounted:async(m:any)=>{await drain();await expect(m.frame.getByText(owner.name,{exact:true})).toHaveCount(0);await expect(m.frame.getByText(admitted.name,{exact:true})).toBeVisible();await expect(m.frame.locator('[data-testid="simulation-plan-banner"]')).toBeVisible();const beat=beats.get(admitted.planId);assert(beat);assert.equal(beat.binding.frame,m.frame);assert(await documents.current(beat.binding));assert.equal(beat.value.body.selfAccountId,privateAccount);},blank:async()=>{},record});owner=admitted;candidate=null;record('private-owner-promoted',owner);return admitted;
  }catch{throw fail('fork-transition');}finally{busy=false;}},
  capture(planId:string,onState:(state:any)=>void){checked();assert.equal(owner?.kind,'private');assert.equal(planId,owner.planId);assert.equal(protocol,null);protocolPlan=planId;protocol=createReportCaptureObserver({planId,onState});return protocol;},
  async dispose(){const errors=[];try{await drain();}catch(e){errors.push(e);}disposed=true;page.off('request',request);page.off('response',response);page.off('requestfinished',finished);page.off('requestfailed',failed);try{await documents.dispose();}catch(e){errors.push(e);}protocol?.dispose();if(errors.length)throw new AggregateError(errors,'Private witness observation incomplete');},
 };
}
