import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {closePhase,createCloseJournal} from '../../forge/close-diagnostics.mjs';import {createPortableLauncher,MODE,VERSION} from '../../forge/portable-browser.mjs';
function fake(observe){const browser=new EventEmitter(),ctx=new EventEmitter(),calls=[];let release;ctx.pages=()=>[];ctx.newPage=async()=>{};ctx.request={dispose:async()=>{calls.push('dispose');}};ctx.tracing={stop:async()=>{},stopChunk:async()=>{}};ctx.close=async()=>{calls.push('context');await ctx.request.dispose();await new Promise(r=>release=r);ctx.emit('close');};browser.version=()=>VERSION;browser.newContext=async()=>ctx;browser.close=async()=>{calls.push('browser');browser.emit('disconnected');};const launch=createPortableLauncher({chromium:{launch:async()=>browser},readAdmission:()=>({cookies:[],origins:[]}),installHostFlagSuppressor:async()=>{},verifyIdentity:async()=>{}});return{calls,release:()=>release(),launch:()=>launch({mode:MODE,viewport:{width:100,height:100},expected:{accountId:'local',uiVersion:'1.2.3'},...(observe?{observeClose:observe}:{})})};}
test('absent observer preserves exact return/throw and work call once',()=>{const p=Promise.resolve(4);assert.equal(closePhase(undefined,'native-context-close',()=>p),p);const e=Error('held');assert.throws(()=>closePhase(undefined,'native-context-close',()=>{throw e;}),x=>x===e);});
test('actual wrapper exposes native wait before browser close, preserving default order and repeated close identity',async()=>{for(const observed of [false,true]){const events=[],f=fake(observed?(phase,event)=>events.push([phase,event]):undefined),ctx=await f.launch();const a=ctx.close(),b=ctx.close();assert.equal(a,b);await new Promise(setImmediate);assert.deepEqual(f.calls,['context','dispose']);if(observed){assert.ok(events.some(x=>x[0]==='native-context-close'&&x[1]==='start'));assert.ok(!events.some(x=>x[0]==='browser-close'));}f.release();await a;assert.deepEqual(f.calls,['context','dispose','browser']);}});
test('hostile observer outcomes cannot change original result or rejection',async()=>{for(const observe of [()=>{throw Error('secret');},()=>Promise.reject(Error('secret')),()=>new Promise(()=>{})]){assert.equal(await closePhase(observe,'native-context-close',()=>42),42);const e=Error('original');await assert.rejects(closePhase(observe,'browser-close',()=>Promise.reject(e)),x=>x===e);}});
test('journal is fixed bounded content-free and recording faults remain failing evidence',()=>{const writes=[];let n=0;const j=createCloseJournal('local',{write:(_p,s)=>writes.push(JSON.parse(s)),now:()=>n++});j.observe('native-context-close','start');assert.deepEqual(writes[0],{schema:'browser-close-phases-v1',events:[{phase:'native-context-close',event:'start',atMs:0}]});j.observe('secret-url','start');assert.throws(()=>j.check(),/recording failed/);assert.equal(writes.length,1);const b=createCloseJournal('local',{write:()=>{},now:()=>1});for(let i=0;i<65;i++)b.observe('browser-close','start');assert.throws(()=>b.check());const f=createCloseJournal('local',{write:()=>{throw Error('secret-token');}});f.observe('browser-close','start');assert.throws(()=>f.check(),e=>!e.message.includes('secret'));});
test('missing starts, duplicates and failed then completed evidence cannot pass',()=>{const core=['fixture-context-close','portable-context-close','viewport-close-queue','native-context-close','request-dispose','browser-close'];for(const mutation of ['none','missing','duplicate','failed']){const j=createCloseJournal('local',{write:()=>{},now:()=>1});for(const phase of core){if(!(mutation==='missing'&&phase==='native-context-close'))j.observe(phase,'start');if(mutation==='failed'&&phase==='native-context-close')j.observe(phase,'failed');j.observe(phase,'complete');if(mutation==='duplicate'&&phase==='native-context-close')j.observe(phase,'complete');}if(mutation==='none')j.check();else assert.throws(()=>j.check());}});
test('local actual worker fixture preserves every statement including the cache CDP session',()=>{const fs=process.getBuiltinModule('fs');const original=fs.readFileSync('fixtures/forge.ts','utf8').replaceAll('"../','"../../').replace('"../../forge/browser"','"./local-launch"');assert.equal(fs.readFileSync('tests/toolbar-comparison-visual/local-forge.ts','utf8'),original);});
test('optional tracing observations must form complete pairs too',()=>{for(const sequence of [['start'],['complete'],['start','start','complete','complete'],['start','complete','start','complete']]){const j=createCloseJournal('local',{write:()=>{},now:()=>1});for(const p of ['fixture-context-close','portable-context-close','viewport-close-queue','native-context-close','request-dispose','browser-close']){j.observe(p,'start');j.observe(p,'complete');}for(const e of sequence)j.observe('trace-stop-chunk',e);if(sequence.join(',')==='start,complete,start,complete')j.check();else assert.throws(()=>j.check());}});
