import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import vm from 'node:vm';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url),ts=require('typescript'),{expect}=require('@playwright/test');
const fixturePath='scenarios/lz-ppm/retained-uat-fixture.ts',specPath='scenarios/lz-ppm/journey-campaign-retained-uat.spec.ts';
const source=fs.readFileSync(fixturePath,'utf8'),scenario=fs.readFileSync(specPath,'utf8');
const oracle=fs.readFileSync('/Users/mihaiperdum/Projects/lz-ppm-forge/docs/campaign-2026-09/retained-uat-oracle.json','utf8');
const oldControls=fs.readFileSync('tests/retained-uat/admission.test.mjs','utf8'),factoryText=oldControls.slice(oldControls.indexOf('function fixture(mode){'),oldControls.indexOf("test('failed admission"));
const fixture=new Function('source','oracle','fs','os','path','vm','pathToFileURL','require','ts','expect',factoryText+'return fixture;')(source,oracle,fs,os,path,vm,pathToFileURL,require,ts,expect);
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
test('actual admission failure retains its positively owned issue under explicit preference',async()=>{const f=fixture('field-failure');try{await assert.rejects(f.api.createRetainedUat(f.info,{retainExperiments:true}),/isolated admission field failure/);assert.deepEqual(f.calls.filter(c=>c[0]==='DELETE'),[]);assert.equal(f.journal().issues.E.id,'1');assert.equal(f.journal().state,'retained-after-failure');assert.ok(f.journal().cleanup.some(c=>c.name==='standing schedule unchanged'&&c.ok));}finally{f.cleanup();}});
test('unknown create retains intent and original refusal, never retries or deletes',async()=>{const f=fixture('unknown');try{await assert.rejects(f.api.createRetainedUat(f.info,{retainExperiments:true}),error=>{assert(error instanceof AggregateError);assert.match(String(error.errors[0]),/ambiguous create reply/);return true;});assert.equal(f.calls.filter(c=>c[0]==='fetch-create').length,1);assert.deepEqual(f.calls.filter(c=>c[0]==='DELETE'),[]);assert.equal(f.journal().issues.E.state,'create-requested');assert.equal(f.journal().state,'recovery-required');}finally{f.cleanup();}});
const begin=source.indexOf('  const errors:any[]=[];',source.indexOf(' f.finish=async(retain:boolean)=>{')),end=source.indexOf('\n };',begin);
const finish=new Function('retain','retainExperiments','journal','f','persist','roles','expect','post','getTestState','put','get','request','scheduleFields','LZPT_PLAN','UAT_LABEL','seeds',`return(async()=>{${compile(source.slice(begin,end))}})()`);
test('actual failed finish preserves both plans, every issue and independent exact guards',async()=>{
 const roles=['E','A','B','L'],plans={main:{id:'main',name:'Main'},mirror:{id:'mirror',name:'Mirror'}},issues=Object.fromEntries(roles.map((r,n)=>[r,{id:String(n+1),key:'WFH-'+(n+1),summary:r}])),calls=[];const journal={plans,issues,registry:['original'],standingSchedule:[],cleanup:[]};
 const f={keys:Object.fromEntries(roles.map(r=>[r,issues[r].key])),own:async r=>{calls.push(['own',r]);},verifySource:async()=>{calls.push(['verifySource']);}};
 const hook=async(_,q)=>{calls.push(['hook',q.what,q.planId]);if(q.what==='plans')return{plans:['original','main','mirror'].map(id=>({id}))};if(q.what==='plan')return q.planId==='original'?{issues:[]}:{meta:{name:plans[q.planId].name}};if(q.what==='deleteFixture')return{deleted:q.planId,registryRemoved:true};return{};};
 await finish(false,true,journal,f,()=>{},roles,expect,async()=>({issues:[]}),hook,async()=>calls.push(['PUT']),async()=>({}),async m=>{calls.push([m]);return{status:404};},x=>x,'original','label',{});
 assert.equal(journal.state,'retained-after-failure');assert.deepEqual(calls.filter(c=>['PUT','DELETE'].includes(c[0])||c[0]==='hook'&&['deleteFixture','clearDrafts'].includes(c[1])),[]);assert.deepEqual(calls.filter(c=>c[0]==='own').map(c=>c[1]),['L','B','A','E']);assert.ok(journal.cleanup.every(c=>c.ok));assert.deepEqual(journal.plans,plans);assert.deepEqual(journal.issues,issues);
});
const a=scenario.lastIndexOf('  const errors:any[]=[];'),b=scenario.indexOf('\n }',a),run=new Function('page','f','info','cleanupOwnedReportCaptures','preferences','expect','rpc','crash','sourceGuard','stopReportUi','reportDepartureFailure','options',`return(async()=>{const graph='offline';let {passed=false,priorError,originalSettings={},routeHandler=null,documentPage=null}=options;let settingsRestored=false;${compile(scenario.slice(a,b))}})()`);
test('actual failed scenario finalizer never dispatches report cleanup and still restores/audits',async()=>{const calls=[],f={planId:'main',retainExperiments:true,journal:{plans:{main:{id:'main'},mirror:{id:'mirror'}},issues:{A:{id:'1'}}},persist(){},async finish(retain){calls.push(['finish',retain]);}},page={isClosed:()=>false,off(){},async goto(){calls.push('blank');}};await run(page,f,{},async()=>calls.push('report-cleanup'),{async restore(){calls.push('restore');return{restored:true};}},expect,{stop(){}},()=>{},async()=>calls.push('source'),async()=>calls.push('safe-stop'),()=>null,{});assert(!calls.includes('report-cleanup'));assert(calls.includes('restore'));assert(calls.includes('source'));assert.deepEqual(calls.filter(Array.isArray),[['finish',false]]);});
test('all original UAT business actions, assertions and deliberate duplicate deletion remain byte-exact',()=>{const old=execFileSync('git',['show','c2e75b3:'+specPath],{encoding:'utf8'}),body=s=>s.slice(s.indexOf("  stage('Assets context"),s.indexOf(' }catch(error){priorError='));assert.equal(body(scenario),body(old));for(const p of ['report-capture.ts','report-departure.ts','report-document-identity.mjs','capacity-preferences.mjs'])assert.equal(fs.readFileSync('scenarios/lz-ppm/'+p,'utf8'),execFileSync('git',['show','c2e75b3:scenarios/lz-ppm/'+p],{encoding:'utf8'}));});

for(const guardFailure of [false,true])test(`original body error survives retained finalizer with preference failure ${guardFailure}`,async()=>{
 const original=new Error('original local body failure'),preferencesError=new Error('local preference failure'),calls=[];
 const f={planId:'main',retainExperiments:true,journal:{plans:{main:{id:'main'},mirror:{id:'mirror'}},issues:{A:{id:'1'}}},persist(){},async finish(retain){calls.push(['finish',retain]);}},page={isClosed:()=>false,off(){},async goto(){}};
 let observed;try{try{throw original;}finally{await run(page,f,{},async()=>calls.push('report-cleanup'),{async restore(){calls.push('restore');if(guardFailure)throw preferencesError;return{restored:true};}},expect,{stop(){}},()=>{},async()=>calls.push('source'),async()=>calls.push('safe-stop'),()=>null,{priorError:original});}}catch(error){observed=error;}
 assert(!calls.includes('report-cleanup'));assert(calls.includes('source'));assert(calls.includes('safe-stop'));
 if(guardFailure){assert(observed instanceof AggregateError);assert.deepEqual(observed.errors,[original,preferencesError]);assert(!calls.some(Array.isArray));assert.equal(f.journal.state,'recovery-required');}else{assert.equal(observed,original);assert.deepEqual(calls.filter(Array.isArray),[['finish',false]]);}
});
