import test from 'node:test';import assert from 'node:assert/strict';
import {guardedCapacityRoute,verifiedAcquisition,capacityWireIdentity,expectedCapacityWire} from '../../scenarios/lz-ppm/seventeenth-wire-acquisition.mjs';
const now=1788700000000;
function wire(exp=now+900000){return {url:expectedCapacityWire.endpoint,headers:{authorization:'test-only'},data:{operationName:expectedCapacityWire.identity.operationName,variables:{input:{...expectedCapacityWire.identity,payload:{call:{functionKey:'getCapacitySettings',payload:{}},contextToken:`e30.${Buffer.from(JSON.stringify({iat:now/1000,exp:exp/1000})).toString('base64url')}.c2ln`}}}}};}
function observation(){const timing={requestedAtMs:now,dispatchedAtMs:now+1,completedAtMs:now+2};return {...timing,observed:{...timing,requestId:1,state:'finished',key:'getCapacitySettings',httpStatus:200,outerSuccess:true,errors:null,responseBytes:123,body:{success:true,version:65,settings:{selectedPlanIds:[],profiles:{},issueChoices:{}}}}};}
test('exact matched terminal Capacity observation produces candidate without changing wire',()=>{const w=wire(),timing=observation(),result=verifiedAcquisition({wire:w,accountId:expectedCapacityWire.accountId,timing});assert.equal(result.wire,w);assert.equal(result.body,timing.observed.body);assert.deepEqual(capacityWireIdentity(w),expectedCapacityWire.identity);});
test('unknown/failed transport and missing or changed request evidence cannot promote',()=>{for(const alter of [t=>t.observed.state='failed',t=>t.observed.outerSuccess=false,t=>t.observed.httpStatus=500,t=>t.observed.key='getSponsorReport',t=>t.observed.requestId=0,t=>t.observed.completedAtMs++,t=>t.completedAtMs=now-1,t=>t.observed.responseBytes=8388609]){const timing=observation();alter(timing);assert.throws(()=>verifiedAcquisition({wire:wire(),accountId:expectedCapacityWire.accountId,timing}));}});
test('wrong actual call payload rejected',()=>{const w=wire();w.data.variables.input.payload.call.payload={planId:'foreign'};assert.throws(()=>verifiedAcquisition({wire:w,timing:observation()}));});
test('route freshness checked when continuation occurs, after any queue',async()=>{let at=now,called=0;const timing={};const route=guardedCapacityRoute({request:()=>42,continue:()=>{called++;return Promise.resolve();}},timing,{wire:wire(),now:()=>at});at+=800000;await assert.rejects(async()=>route.continue(),/STALE_UNSENT/);assert.equal(called,0);assert.equal(timing.dispatchedAtMs,undefined);});
test('route retains exact actual wire and records gate immediately before dispatch',async()=>{const w=wire(),before=structuredClone(w),timing={};let called=0;const route=guardedCapacityRoute({request:()=>42,continue:()=>{called++;assert.equal(timing.dispatchedAtMs,now);return Promise.resolve();}},timing,{wire:w,now:()=>now});assert.equal(route.request(),42);await route.continue();assert.equal(called,1);assert.deepEqual(w,before);});
test('foreign app/module and endpoint never dispatch',async()=>{for(const change of [w=>w.url='https://elsewhere.test/',w=>w.data.variables.input.extensionId+='foreign']){const w=wire();change(w);let called=0;const route=guardedCapacityRoute({request:()=>42,continue:()=>{called++;}},{},{wire:w,now:()=>now});await assert.rejects(async()=>route.continue());assert.equal(called,0);}});
import {settledRequest} from '../../scenarios/lz-ppm/seventeenth-wire-acquisition.mjs';
test('dispatch journal failure waits for exact actual request before releasing ownership',async()=>{let finish,released=false,posts=0;const pending=new Promise(resolve=>finish=resolve);const result=settledRequest(()=>{posts++;return pending;},()=>{throw 0;}).finally(()=>released=true);result.catch(()=>{});await Promise.resolve();assert.equal(released,false);finish('actual response');await assert.rejects(result,error=>error===0);assert.equal(posts,1);assert.equal(released,true);});
test('simultaneous journal and actual transport failures both preserved without retry',async()=>{let posts=0;await assert.rejects(settledRequest(()=>{posts++;return Promise.reject('actual failure');},()=>{throw 'journal failure';}),error=>{assert.deepEqual(error.errors,['journal failure','actual failure']);return true;});assert.equal(posts,1);});
import {safeTransportFailure,browserPrincipal} from '../../scenarios/lz-ppm/seventeenth-wire-acquisition.mjs';
test('transport error retains digest but never header call log or original cause',()=>{const error=new Error('request failed Authorization: secret-credential Cookie: session=secret-cookie');const safe=safeTransportFailure(error,'report-rpc');assert.equal(safe.message,'SAFE_REPORT_RPC_FAILED');assert.equal(safe.cause,undefined);assert.match(safe.receipt.errorSha256,/^[a-f0-9]{64}$/);assert.equal(safe.receipt.errorBytes,Buffer.byteLength(String(error)));assert.doesNotMatch(JSON.stringify(safe)+safe.stack,/secret-/);});
test('browser principal uses same request context once with no retry and safe failure',async()=>{let calls=0;const page={request:{get:async(url,options)=>{calls++;assert.equal(url,'https://wolfaenpak.atlassian.net/rest/api/3/myself');assert.deepEqual(options,{maxRetries:0,maxRedirects:0,timeout:60000});throw new Error('Cookie: secret-cookie');}}};await assert.rejects(browserPrincipal(page,'https://wolfaenpak.atlassian.net'),error=>{assert.equal(error.message,'SAFE_BROWSER_PRINCIPAL_FAILED');assert.doesNotMatch(JSON.stringify(error)+error.stack,/secret-cookie/);return true;});assert.equal(calls,1);});
