import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {admitPacedResume,failedSha,recoveredSha} from '../../scenarios/lz-ppm/seventeenth-paced-resume-contract.mjs';
import {admitAggregateResume,pacedFailureSha} from '../../scenarios/lz-ppm/seventeenth-aggregate-resume-contract.mjs';
const load=(p,hash)=>{const bytes=fs.readFileSync(p);if(hash)assert.equal(createHash('sha256').update(bytes).digest('hex'),hash);return JSON.parse(bytes);};
const source=load('evidence/lz-campaign/seventeenth-source-return-readonly-20260906/artifacts/scenarios-lz-ppm-campaign--755d0-eserve-exact-retained-state-chromium/seventeenth-source.json','7226d8e907632eaf8c2d464b50c3a48ba701bd639f9a4ac0af92bf9078eecba5');
const failed=load('evidence/lz-campaign/seventeenth-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--f695f-rt-and-HTML-without-cleanup-chromium/seventeenth-forecast-resume.json',failedSha);
const recovery=load('evidence/lz-campaign/seventeenth-quota-readonly-admission-20260906/receipt.json',recoveredSha);
const paced=load('evidence/lz-campaign/seventeenth-paced-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--6c70d-rt-and-HTML-without-cleanup-chromium/seventeenth-paced-resume.json',pacedFailureSha);

import {admitRefreshedResume,continueRefreshedReport,aggregateFailureSha} from '../../scenarios/lz-ppm/seventeenth-refreshed-resume-contract.mjs';
const aggregate=load('evidence/lz-campaign/seventeenth-aggregate-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--7ca7a-rt-and-HTML-without-cleanup-chromium/seventeenth-aggregate-resume.json',aggregateFailureSha);
const previous=()=>admitAggregateResume(paced,pacedFailureSha,admitPacedResume(failed,failedSha,recovery,recoveredSha,{job:source.finalJob,probe:source.finalProbe}));
const admit=(value=aggregate,digest=aggregateFailureSha)=>admitRefreshedResume(value,digest,previous());
const stages=load('tests/seventeenth-paced-resume/advance-reservations.json').remainingAfter126.filter(r=>r.from>=155);

test('exact28 real acknowledgements and proofs plus expired29th admit laststrong155 only',()=>{const x=admit();assert.equal(x.job.checkpoint,155);assert.equal(x.probe.privateArtifacts.length,187);assert.equal(x.probe.publicArtifacts.length,114);assert.equal(x.probe.publicArtifacts.filter(a=>a.present).length,110);assert.deepEqual(x.job.forecastRuns,{completed:40,total:40});assert.equal(stages.length,28);});
test('wrong receipt, missing expiredrequest or falsely successful finalaudits refuse',()=>{assert.throws(()=>admit(aggregate,'0'.repeat(64)));for(const edit of [x=>x.events=x.events.filter(e=>!(e.stage==='advanceSponsorReportCapture'&&e.value.outerSuccess===false)),x=>x.completed=true,x=>x.sourceAndPreferencesPreserved=true,x=>x.advanceCalls=28]){const x=structuredClone(aggregate);edit(x);assert.throws(()=>admit(x));}});
test('expiry is not an acknowledgement and no other errorclass or checkpoint can replaceit',()=>{for(const edit of [x=>x.events.filter(e=>e.stage==='advanceSponsorReportCapture').at(-1).value.outerSuccess=true,x=>x.events.filter(e=>e.stage==='advanceSponsorReportCapture').at(-1).value.errors[0].extensions.errorType='OTHER',x=>x.events.filter(e=>e.stage==='actual-advance-dispatch').at(-1).value.payload.expectedCheckpoint=156,x=>x.finalJob.checkpoint=156]){const x=structuredClone(aggregate);edit(x);assert.throws(()=>admit(x));}});
test('missing priorrunheader, altered status or physicalproof and erased finalfailedaudit refuse',()=>{for(const edit of [x=>x.probes[1].privateArtifacts.pop(),x=>x.probes.at(-1).privateArtifacts[0].actualHash='0'.repeat(64),x=>x.events.filter(e=>e.stage==='getSponsorReportCapture')[20].value.body.job.checkpoint=900,x=>x.events=x.events.filter(e=>!(e.stage==='independent-audit-error'&&e.value.label==='preferences'))]){const x=structuredClone(aggregate);edit(x);assert.throws(()=>admit(x));}});
async function simulate(fault){const admitted=admit();let actual=admitted.job,calls=0,physical=0;let result,error;try{result=await continueRefreshedReport({initial:actual,progress:admitted.progress,advance:async payload=>{assert.equal(payload.expectedCheckpoint,actual.checkpoint);calls++;if(fault==='unknown')throw new Error('unknown');const row=stages[calls-1];actual={...actual,checkpoint:row.to,completedUnits:row.to,totalUnits:183,state:row.to===183?'complete':'active',stageLabel:stages[calls]?.priorStage??'Report ready'};if(fault==='premature')actual={...actual,state:'complete'};if(fault==='counter')actual.forecastRuns={completed:39,total:40};return {httpStatus:200,outerSuccess:fault!=='expired',body:fault==='expired'?null:{success:fault!=='refused',job:actual}};},status:async()=>fault==='status'?{...actual,checkpoint:999}:actual,probe:async()=>{physical++;if(fault==='physical')throw new Error('physical');}});}catch(e){error=e;}return {result,error,calls,physical};}
test('exact28 remaining transitions155→183 use all40 savedruns and every status/probe',async()=>{const x=await simulate();assert.ifError(x.error);assert.equal(x.result.checkpoint,183);assert.equal(x.calls,28);assert.equal(x.physical,28);assert.deepEqual(x.result.forecastRuns,{completed:40,total:40});});
test('actual expired/unknown/refused/status/proof/counter failure is terminal withno secondattempt',async()=>{for(const fault of ['expired','unknown','refused','status','physical','counter']){const x=await simulate(fault);assert.ok(x.error);assert.equal(x.calls,1);}});
test('premature publication cannot replace complete28-step protocol',async()=>{const x=await simulate('premature');assert.ok(x.error);assert.equal(x.calls,1);});
