import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {observeReportCapture} from '../../scenarios/lz-ppm/report-capture';
const job={id:'j',requestId:'nonce',name:'R',createdAt:'2026-09-06T00:00:00Z',expiresAt:'2026-09-07T00:00:00Z',checkpoint:0,state:'active',stageLabel:'Source',completedUnits:0,totalUnits:8,cleanupDone:false};
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lz-report-observer-')),page=new EventEmitter() as any;const session=observeReportCapture(page,'p',{outputPath:(x:string)=>path.join(dir,x)});return{page,session,dir,close:()=>{session.stop();fs.rmSync(dir,{recursive:true});}};}
function request(key:string,payload:any={}){return{postDataBuffer:()=>Buffer.from(JSON.stringify({variables:{input:{payload:{call:{functionKey:key,payload:{planId:'p',...payload}}}}}})),url:()=> 'https://example.invalid/owned',allHeaders:async()=>({}),failure:()=>({errorText:'Native request failed'})};}
function response(req:any,body:any){return{request:()=>req,status:()=>200,finished:async()=>{},json:async()=>({data:{invokeExtension:{success:true,response:{body}}}})};}
test('actual adapter serializes response parsing before following request validation',async()=>{const f=fixture();try{const b=request('captureSponsorReport',{name:'R',requestId:'nonce'});f.page.emit('request',b);f.page.emit('response',response(b,{success:true,job}));const a=request('advanceSponsorReportCapture',{jobId:'j',expectedCheckpoint:0});f.page.emit('request',a);f.page.emit('response',response(a,{success:true,job:{...job,checkpoint:1}}));await f.session.settle();assert.equal(f.session.recorder.snapshot().error,null);assert.equal(f.session.recorder.snapshot().job.checkpoint,1);assert.equal(JSON.parse(fs.readFileSync(path.join(f.dir,'report-capture-protocol.json'),'utf8')).events.length,4);}finally{f.close();}});
test('actual outer Forge timeout is retained rather than undefined-body success',async()=>{const f=fixture();try{const b=request('captureSponsorReport',{name:'R',requestId:'nonce'});f.page.emit('request',b);const res=response(b,null);res.json=async()=>({data:{invokeExtension:{success:false,response:null,errors:[{message:'Task timed out after 25.00 seconds'}]}}}) as any;f.page.emit('response',res);await f.session.settle();await assert.rejects(f.session.recorder.wait(()=>true),/Task timed out after 25/);}finally{f.close();}});
test('requestfailed is an error, not permission to repeat begin',async()=>{const f=fixture();try{const b=request('captureSponsorReport',{name:'R',requestId:'nonce'});f.page.emit('request',b);f.page.emit('requestfailed',b);await f.session.settle();await assert.rejects(f.session.recorder.wait(()=>true),/Native request failed/);}finally{f.close();}});
test('unrelated owner-discovery before click does not admit a foreign prior job',async()=>{const f=fixture();try{const q=request('getSponsorReportCapture');f.page.emit('request',q);f.page.emit('response',response(q,{success:true,job:{...job,id:'old'}}));await f.session.settle();assert.equal(f.session.recorder.snapshot().job,null);assert.equal(f.session.recorder.snapshot().begin,null);}finally{f.close();}});
