import {createHash} from 'node:crypto';
import test from 'node:test';import assert from 'node:assert/strict';
import {cleanReportCapture,verifyCaptureProbe} from '../../scenarios/lz-ppm/report-capture-cleanup.mjs';
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const digest='a'.repeat(64),job={id:'j',requestId:'n',state:'active',checkpoint:1,cleanupDone:false};
const proof=(j,extra={})=>({planId:'p',jobId:'j',registryMember:true,state:j.state,checkpoint:j.checkpoint,cleanupDone:j.cleanupDone,privateManifestHash:hash([digest]),publicManifestHash:hash([]),privateArtifacts:[{keyHash:digest,expectedHash:digest,present:!j.cleanupDone,actualHash:j.cleanupDone?null:digest}],publicArtifacts:[],...extra});
function ports(extra={}){let current={...job};const calls=[],states=[];return {calls,states,options:{planId:'p',requestId:'n',jobId:'j',onState:s=>states.push(s),invoke:async(name,payload)=>{calls.push([name,payload]);if(name==='cancelSponsorReportCapture')current={...current,state:'cancelled',checkpoint:current.checkpoint+1,cleanupDone:true};return{success:true,job:current};},probe:async()=>proof(current),...extra}};}
test('actual cleanup retains exact manifest before and verifies two strong absence reads',async()=>{const f=ports();const r=await cleanReportCapture(f.options);assert.equal(r.cleaned,true);assert.equal(r.probes.length,3);assert.deepEqual(f.calls.map(c=>c[0]),['getSponsorReportCapture','cancelSponsorReportCapture']);assert.equal(r.probes[0].privateArtifacts[0].present,true);assert.equal(r.probes[2].privateArtifacts[0].present,false);});
test('foreign owner request cannot be adopted for cleanup',async()=>{const f=ports({requestId:'other'});await assert.rejects(cleanReportCapture(f.options),e=>e.code==='LZ_REPORT_CAPTURE_RECOVERY_REQUIRED');assert.equal(f.calls.length,1);assert.equal(f.states.at(-1).cleaned,false);});
test('failed or ambiguous cancel is never retried and exact state survives',async()=>{const f=ports();const original=f.options.invoke;f.options.invoke=async(k,p)=>k==='cancelSponsorReportCapture'?{success:false,error:'Lease outcome unknown'}:original(k,p);await assert.rejects(cleanReportCapture(f.options),e=>e.code==='LZ_REPORT_CAPTURE_RECOVERY_REQUIRED'&&/Lease outcome unknown/.test(e.cause.message));assert.equal(f.states.at(-1).cleaned,false);});
test('false cleanupDone while keys still present cannot pass',async()=>{const f=ports({probe:async()=>proof({...job,state:'cancelled',checkpoint:2,cleanupDone:true},{privateArtifacts:[{keyHash:digest,expectedHash:digest,present:true,actualHash:digest}]})});await assert.rejects(cleanReportCapture(f.options),e=>e.code==='LZ_REPORT_CAPTURE_RECOVERY_REQUIRED');});
test('missing manifest entries after cancellation is not proof of removal',()=>{const before=proof(job),after=proof({...job,state:'cancelled',checkpoint:2,cleanupDone:true},{privateArtifacts:[]});assert.throws(()=>verifyCaptureProbe(after,{planId:'p',jobId:'j',...job,state:'cancelled',checkpoint:2,cleanupDone:true},before));});
test('cleanup after complete keeps all public report objects',async()=>{const done={...job,state:'complete',reportId:'r',cleanupDone:true};const publicArtifacts=[{keyHash:digest,present:true,actualHash:digest}];const f=ports({invoke:async()=>({success:true,job:done}),probe:async()=>proof(done,{publicArtifacts,publicManifestHash:hash([digest])})});const r=await cleanReportCapture(f.options);assert.equal(r.cleaned,true);assert.equal(r.steps.length,0);assert.equal(r.probes.length,3);});
test('zero-progress cleanup refused rather than infinite retry',async()=>{const f=ports({invoke:async()=>({success:true,job})});await assert.rejects(cleanReportCapture(f.options),e=>/no acknowledged progress/.test(e.cause.message));});
