import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pinned,sha} from '../../scenarios/lz-ppm/eighteenth-recovery-contract.mjs';
const cwd=new URL('../../',import.meta.url).pathname,cli=path.join(cwd,'node_modules/@playwright/test/cli.js'),spec='scenarios/lz-ppm/campaign-eighteenth-recovery.spec.ts';
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith('LZ_EIGHTEENTH_RECOVERY_'))delete e[k];return e;}
const run=(extra,args=['--list'])=>spawnSync(process.execPath,[cli,'test',spec,...args],{cwd,env:{...env(),...extra},encoding:'utf8',timeout:30000});
test('actual CLI discovery without phase registers exactly one inert test',()=>{const r=run({});assert.equal(r.status,0,r.stderr+r.stdout);assert.match(r.stdout,/Total: 1 test in 1 file/);});
test('actual absent-phase execution is skipped and does not launch browser',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'recovery-cli-'));try{const r=run({HARNESS_BROWSER_MODE:'intentionally-invalid-browser-must-not-launch'},['--reporter=line','--output='+tmp]);assert.equal(r.status,0,r.stderr+r.stdout);assert.match(r.stdout,/1 skipped/);}finally{fs.rmSync(tmp,{recursive:true});}});
test('actual explicit unsupported phase refuses collection',()=>{const r=run({LZ_EIGHTEENTH_RECOVERY_PHASE:'wrong'});assert.notEqual(r.status,0);assert.match(r.stdout+r.stderr,/approved-three-fixtures/);});
test('actual explicit phase without approval refuses before registration',()=>{const r=run({LZ_EIGHTEENTH_RECOVERY_PHASE:'approved-three-fixtures'});assert.notEqual(r.status,0);assert.match(r.stdout+r.stderr,/required before registration/);});
test('actual exact pinned files plus test-only approval permit list; wrong digest blocks it',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'recovery-list-'));try{const a={schema:'eighteenth-root-recovery-approval-v1',approveRecovery:true,terminalSha256:pinned.terminalSha256,pinSha256:sha(fs.readFileSync(new URL('./pinned.json',import.meta.url))),principal:pinned.principal,planIds:pinned.fixtures.map(f=>f.planId),issueKeys:pinned.fixtures.map(f=>f.issue),jobIds:pinned.fixtures.map(f=>f.job.id),rootDispatchCommit:'a'.repeat(40)},file=path.join(tmp,'test-only-approval.json'),bytes=JSON.stringify(a);fs.writeFileSync(file,bytes);const e={LZ_EIGHTEENTH_RECOVERY_PHASE:'approved-three-fixtures',LZ_EIGHTEENTH_RECOVERY_EVIDENCE:path.join(cwd,'evidence/lz-campaign/eighteenth-report-acceptance-20260906'),LZ_EIGHTEENTH_RECOVERY_APPROVAL:file,LZ_EIGHTEENTH_RECOVERY_APPROVAL_SHA256:sha(bytes)};const yes=run(e);assert.equal(yes.status,0,yes.stdout+yes.stderr);assert.match(yes.stdout,/Total: 1 test in 1 file/);assert.notEqual(run({...e,LZ_EIGHTEENTH_RECOVERY_APPROVAL_SHA256:'0'.repeat(64)}).status,0);}finally{fs.rmSync(tmp,{recursive:true});}});
