import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {pinned,sha,recoveryAdmission,verifyOwnedSource,verifyOwnedJira,recoveryUiClass,recoverThree} from '../../scenarios/lz-ppm/eighteenth-recovery-contract.mjs';
const copy=x=>structuredClone(x);
function source(f){return {meta:{id:f.planId,name:f.name,createdBy:'harness',calendarKey:'standard',sources:[{id:'src-0',type:'jql',label:'harness',query:`key in (${f.issue}) ORDER BY Rank ASC`,boardId:null,projectKey:null}]},issues:[{id:'123',key:f.issue,summary:`${f.name} ${f.seed.label}`,startDate:f.seed.start,dueDate:f.seed.due,duration:f.seed.duration,predecessors:[],successors:[]}]};}
function jira(f){return {httpStatus:200,body:{id:'123',key:f.issue,fields:{project:{key:'WFH'},issuetype:{id:'10004'},labels:[f.marker],summary:`${f.name} ${f.seed.label}`,customfield_10015:f.seed.start,duedate:f.seed.due,customfield_10180:f.seed.duration,issuelinks:[]}}};}
function fixture(){const calls=[],deleted=new Set(),jiraDeleted=new Set(),jobs=new Map(pinned.fixtures.map(f=>[f.planId,copy(f.job)])),probes=new Map(pinned.fixtures.map(f=>[f.planId,copy(f.probe)]));const io={principal:async()=>pinned.principal,preferences:async()=>copy(pinned.preferences),originalSource:async()=>({issues:['full-original-source']}),otherSources:async()=>[{issues:['54-original']},{issues:['5300-original']}],registry:async()=>[...pinned.originals,...pinned.fixtures.map(f=>f.planId)].filter(id=>!deleted.has(id)).map(id=>({id})),source:async id=>deleted.has(id)?{meta:null,issues:[]}:source(pinned.fixtures.find(f=>f.planId===id)),emptyDrafts:async()=>{},baseline:async()=>({baseline:null}),reports:async()=>({success:true,entries:[],nextCursor:null}),job:async f=>({success:true,job:copy(jobs.get(f.planId))}),probe:async f=>copy(probes.get(f.planId)),cancel:async f=>{calls.push(['cancel',f.planId]);const job={...jobs.get(f.planId),state:'cancelled',checkpoint:2,completedUnits:2,cleanupDone:true,stageLabel:'Cleaning up temporary data'};jobs.set(f.planId,job);const p=probes.get(f.planId);Object.assign(p,{state:'cancelled',checkpoint:2,cleanupDone:true});for(const a of p.privateArtifacts){a.present=false;a.actualHash=null;}return {success:true,job:copy(job)};},deletePlan:async f=>{calls.push(['planDelete',f.planId]);deleted.add(f.planId);return {success:true};},issue:async(method,key)=>{calls.push([method,key]);const f=pinned.fixtures.find(f=>f.issue===key);if(method==='DELETE'){jiraDeleted.add(key);return {httpStatus:204,body:null};}return jiraDeleted.has(key)?{httpStatus:404,body:{errorMessages:['not found']}}:jira(f);}};return {io,calls,probes,jobs,approval:{approval:{approveRecovery:true},terminalSha256:pinned.terminalSha256}};}
const writes=f=>f.calls.filter(([k])=>['cancel','planDelete','DELETE'].includes(k));
test('actual pinned protocols: two cancels, all three full payload checks, three plans/three issues, no cancelled-job retry',async()=>{const f=fixture(),events=[];assert.equal((await recoverThree({...f,record:async(stage,value)=>events.push({stage,value})})).completed,true);assert.deepEqual(writes(f),[['cancel',pinned.fixtures[0].planId],['cancel',pinned.fixtures[2].planId],...pinned.fixtures.flatMap(x=>[['planDelete',x.planId],['DELETE',x.issue]])]);assert.equal(events.filter(e=>e.stage==='payloads-absent-before-plan-delete').length,6);for(const x of pinned.fixtures){const idx=f.calls.findIndex(([k,id])=>k==='DELETE'&&id===x.issue);assert.deepEqual(f.calls[idx-1],['GET',x.issue]);assert.deepEqual(f.calls.slice(idx+1,idx+3),[['GET',x.issue],['GET',x.issue]]);}});
for(const [name,mutate]of[
 ['wrong principal',f=>f.io.principal=async()=> 'foreign'],['changed prefs',f=>f.io.preferences=async()=>({...pinned.preferences,version:66})],['foreign registry',f=>f.io.registry=async()=>[{id:'foreign'}]],['changed job checkpoint',f=>f.jobs.get(pinned.fixtures[2].planId).checkpoint++],['missing private artifact',f=>f.probes.get(pinned.fixtures[0].planId).privateArtifacts[0].present=false],['source duration drift',f=>f.io.source=async id=>{const s=source(pinned.fixtures.find(f=>f.planId===id));s.issues[0].duration=7;return s;}],['positive issue GET404',f=>f.io.issue=async()=>({httpStatus:404})],['foreign issue label',f=>f.io.issue=async(_,key)=>{const j=jira(pinned.fixtures.find(f=>f.issue===key));j.body.fields.labels=['foreign'];return j;}]
])test(`${name} refuses before ANY mutation`,async()=>{const f=fixture();mutate(f);await assert.rejects(recoverThree(f));assert.deepEqual(writes(f),[]);});
test('cancel generic refusal never retries or deletes plan/issue',async()=>{const f=fixture();f.io.cancel=async x=>{f.calls.push(['cancel',x.planId]);return {success:false,error:'unavailable'};};await assert.rejects(recoverThree(f));assert.deepEqual(writes(f),[['cancel',pinned.fixtures[0].planId]]);});
test('lost plan-delete acknowledgement stops exact flow, no Jira DELETE or replay',async()=>{const f=fixture();f.io.deletePlan=async x=>{f.calls.push(['planDelete',x.planId]);throw new Error('unknown outcome');};await assert.rejects(recoverThree(f));assert.equal(writes(f).filter(([k])=>k==='planDelete').length,1);assert.equal(writes(f).filter(([k])=>k==='DELETE').length,0);});
test('lost issue-delete acknowledgement stops, no retry and no next plan deletion',async()=>{const f=fixture(),original=f.io.issue;f.io.issue=async(m,k)=>{if(m==='DELETE'){f.calls.push([m,k]);throw 0;}return original(m,k);};await assert.rejects(recoverThree(f));assert.equal(writes(f).filter(([k])=>k==='planDelete').length,1);assert.equal(writes(f).filter(([k])=>k==='DELETE').length,1);});
test('reported cleanupDone with physically present artifact prevents all plan deletes',async()=>{const f=fixture(),original=f.io.cancel;f.io.cancel=async x=>{const r=await original(x);f.probes.get(x.planId).privateArtifacts[0].present=true;return r;};await assert.rejects(recoverThree(f));assert.ok(!writes(f).some(([k])=>k==='planDelete'));});
test('Jira additional dependency is refused, no deleteSubtasks capability',()=>{const j=jira(pinned.fixtures[0]);j.body.fields.issuelinks=[{id:'1'}];assert.throws(()=>verifyOwnedJira(j,pinned.fixtures[0]));});
test('UI allows exact armed plan delete only; all begin/advance/presence/save/foreign/delete-report blocked',()=>{const f=pinned.fixtures[0];assert.equal(recoveryUiClass({functionKey:'deletePlan',payload:{planId:f.planId}},f.planId),'approved-plan-delete');for(const key of ['captureSponsorReport','advanceSponsorReportCapture','presenceBeat','presenceLeave','savePlan','deleteSponsorReport'])assert.equal(recoveryUiClass({functionKey:key,payload:{planId:f.planId}},f.planId),'forbidden');assert.equal(recoveryUiClass({functionKey:'deletePlan',payload:{planId:'foreign'}},f.planId),'forbidden');assert.equal(recoveryUiClass({functionKey:'deletePlan',payload:{planId:f.planId}},null),'forbidden');assert.equal(recoveryUiClass({functionKey:'getCapacitySettings',payload:{}},null),'read');});
test('discovery inert absent phase; unsupported/missing explicit approval fails without site access',()=>{assert.equal(recoveryAdmission({}),null);assert.equal(recoveryAdmission({LZ_EIGHTEENTH_RECOVERY_PHASE:''}),null);assert.throws(()=>recoveryAdmission({LZ_EIGHTEENTH_RECOVERY_PHASE:'wrong'}));assert.throws(()=>recoveryAdmission({LZ_EIGHTEENTH_RECOVERY_PHASE:'approved-three-fixtures'}));});
test('actual nine evidence files + terminal/summary validate with explicit root receipt; changed approval refuses',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'lz-recovery-admit-'));try{const approval={schema:'eighteenth-root-recovery-approval-v1',approveRecovery:true,terminalSha256:pinned.terminalSha256,pinSha256:sha(fs.readFileSync(new URL('./pinned.json',import.meta.url))),principal:pinned.principal,planIds:pinned.fixtures.map(f=>f.planId),issueKeys:pinned.fixtures.map(f=>f.issue),jobIds:pinned.fixtures.map(f=>f.job.id),rootDispatchCommit:'a'.repeat(40)};const file=path.join(tmp,'approval.json'),bytes=JSON.stringify(approval);fs.writeFileSync(file,bytes);const env={LZ_EIGHTEENTH_RECOVERY_PHASE:'approved-three-fixtures',LZ_EIGHTEENTH_RECOVERY_EVIDENCE:new URL('../../evidence/lz-campaign/eighteenth-report-acceptance-20260906/',import.meta.url).pathname,LZ_EIGHTEENTH_RECOVERY_APPROVAL:file,LZ_EIGHTEENTH_RECOVERY_APPROVAL_SHA256:sha(bytes)};assert.equal(recoveryAdmission(env).approval.approveRecovery,true);assert.throws(()=>recoveryAdmission({...env,LZ_EIGHTEENTH_RECOVERY_APPROVAL_SHA256:'0'.repeat(64)}));for(const patch of [{approveRecovery:false},{issueKeys:['WFH-2820']},{jobIds:['foreign']},{terminalSha256:'0'.repeat(64)}]){const bad=JSON.stringify({...approval,...patch});fs.writeFileSync(file,bad);assert.throws(()=>recoveryAdmission({...env,LZ_EIGHTEENTH_RECOVERY_APPROVAL_SHA256:sha(bad)}));}}finally{fs.rmSync(tmp,{recursive:true});}});
