import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {admitOwnerCleanup,loadOwnerCleanupAdmission,cleanExactOwner,ownerCleanupBound,cleanupReadCost,cleanupUiRequestClass} from '../../scenarios/lz-ppm/seventeenth-owner-cleanup-contract.mjs';
import {retained} from '../../scenarios/lz-ppm/seventeenth-report-recovery-contract.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex'),canonical=x=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x,hash=x=>sha(JSON.stringify(canonical(x)));
function fixture(){
 const job={id:retained.jobId,requestId:retained.requestId,reportId:retained.reportId,state:'complete',checkpoint:183,cleanupDone:false,forecastRuns:{completed:40,total:40},completedUnits:183,totalUnits:183};
 const privateArtifacts=Array.from({length:188},(_,n)=>({keyHash:sha('private'+n),expectedHash:sha('value'+n),present:true,actualHash:sha('value'+n)}));
 const publicArtifacts=[...Array.from({length:112},(_,n)=>({keyHash:sha('public'+n),role:n===0?'descriptor':'page',collection:'current',expectedPresent:true,present:true,actualHash:sha('publicvalue'+n)})),...['sponsor-reports','sponsor-report-baselines'].map((ns,n)=>({keyHash:hash(`p:${retained.planId}:${ns}:deleted:${retained.reportId}`),role:'deletion-marker',collection:n?'baseline':'current',expectedPresent:false,present:false,actualHash:null}))];
 const probe={planId:retained.planId,jobId:retained.jobId,state:'complete',checkpoint:183,cleanupDone:false,registryMember:true,privateArtifacts,publicArtifacts,privateManifestHash:hash(privateArtifacts.map(x=>x.keyHash)),publicManifestHash:hash(publicArtifacts.map(x=>x.keyHash))};
 const files=new Map([['html',Buffer.from('test HTML root must inspect')],...Array.from({length:4},(_,n)=>['png'+n,Buffer.from('89504e470d0a1a0a','hex')])]);
 const j={phase:'paced-resume155',retained,completed:true,publicationObserved:true,sourceAndPreferencesPreserved:true,traceDiscarded:true,all5300ReportFieldsVerified:true,all5300HtmlFieldsVerified:true,reopenedAllPagesImmutable:true,reviewRequired:true,aggregateFailureReceipt:{sha256:'7be7311c7d5369ccdf70bd9f9144c4ae44111814a7100a9df3a5d72b80afdf67'},advanceCalls:28,events:[{stage:'download-saved',value:{sha256:sha(files.get('html')),bytes:files.get('html').length}}],finalJob:job,finalProbe:probe,report:{id:retained.reportId,counts:{timeline:5300},forecast:{runs:40,inputHash:'74e3f14bb519b5733ec1a65d729605f63ccebf4e6594b1f1ddf0682b90404e4a'}},pages:Array.from({length:106},()=>({rows:Array.from({length:50},()=>({}))}))};
 const i={schema:'retained-report-root-cleanup-approval-v1',approveCleanup:true,inspectionComplete:true,retained,domainVerificationPassed:true,ledgerVerificationPassed:true,rootInspectionCommit:'a'.repeat(40),reportSummaryHash:hash(j.report),pagesHash:hash(j.pages),finalProbeHash:hash(j.finalProbe),artifacts:[...files].map(([path,b])=>({path,role:path==='html'?'html':'png',sha256:sha(b),bytes:b.length}))};
 const seal=()=>{const journalBytes=Buffer.from(JSON.stringify(j));i.completedJournalSha256=sha(journalBytes);const inspectionBytes=Buffer.from(JSON.stringify(i));return {journalBytes,journalSha256:sha(journalBytes),inspectionBytes,inspectionSha256:sha(inspectionBytes),readFile:p=>files.get(p)};};return{j,i,files,seal};
}
test('external exact completed journal and inspection admit; no invented terminal in executable',()=>{const f=fixture();assert.equal(admitOwnerCleanup(f.seal()).journal.finalJob.checkpoint,183);assert.throws(()=>loadOwnerCleanupAdmission({}),/required before test registration/);});
test('missing or unapproved root receipt and either mismatched byte digest refuse',()=>{for(const edit of [f=>f.i.approveCleanup=false,f=>f.i.inspectionComplete=false,f=>f.i.ledgerVerificationPassed=false,f=>f.i.domainVerificationPassed=false]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}const f=fixture(),v=f.seal();assert.throws(()=>admitOwnerCleanup({...v,journalSha256:'b'.repeat(64)}));assert.throws(()=>admitOwnerCleanup({...v,inspectionSha256:undefined}));});
test('active/stale/cleaned/failed terminal and changed owner identity refuse',()=>{for(const edit of [f=>f.j.finalJob.state='active',f=>f.j.finalJob.checkpoint=182,f=>f.j.finalJob.cleanupDone=true,f=>f.j.finalJob.requestId='foreign',f=>f.j.completed=false,f=>f.j.events.push({stage:'independent-audit-error'}),f=>f.j.traceDiscarded=false]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}});
test('lost private payload, wrong marker, missing page and uninspected/tampered artifact refuse',()=>{for(const edit of [f=>f.j.finalProbe.privateArtifacts[0].present=false,f=>f.j.finalProbe.publicArtifacts.at(-1).present=true,f=>f.j.pages.pop(),f=>f.i.artifacts.pop(),f=>f.files.set('html',Buffer.from('changed'))]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}});
test('complete owner flow exactly38 acknowledgements then stops; no extra calls',async()=>{const {j}=fixture();let calls=0;const out=await cleanExactOwner({initial:j.finalJob,phase:'private',cancel:async payload=>{assert.deepEqual(payload,{planId:retained.planId,jobId:retained.jobId});calls++;return{success:true,job:{...j.finalJob,checkpoint:183+calls,completedUnits:183+calls,totalUnits:183+calls,cleanupDone:calls===38}};}});assert.equal(calls,38);assert.equal(out.state,'complete');assert.equal(out.cleanupDone,true);});
test('false/throw/zero-progress/cross-job/false-final never retries',async()=>{for(const behavior of ['false','throw','same','other','notclean']){const {j}=fixture();let calls=0;await assert.rejects(cleanExactOwner({initial:{...j.finalJob,state:'cancelled'},phase:'public',cancel:async()=>{calls++;if(behavior==='throw')throw Error('unknown');if(behavior==='false')return{success:false,error:'unknown'};return{success:true,job:{...j.finalJob,state:'cancelled',id:behavior==='other'?'other':j.finalJob.id,checkpoint:behavior==='same'?183:184,completedUnits:184,totalUnits:184,cleanupDone:behavior!=='notclean'}};}}));assert.equal(calls,1);}});
test('monotonic and explicit bounded duration fail closed',async()=>{assert.equal(ownerCleanupBound(38),5798000);assert.throws(()=>ownerCleanupBound(39));const{j}=fixture();let n=0;await assert.rejects(cleanExactOwner({initial:j.finalJob,phase:'private',now:()=>n++?0:1,cancel:()=>{throw Error('must not dispatch');}}));});
test('only measured cleanup mutations priced and unknown operations still refuse',()=>{assert.equal(cleanupReadCost('cancelSponsorReportCapture','private'),192);assert.equal(cleanupReadCost('cancelSponsorReportCapture','public'),352);assert.equal(cleanupReadCost('deleteSponsorReport'),224);assert.equal(cleanupReadCost('deletePlan'),768);assert.throws(()=>cleanupReadCost('cancelSponsorReportCapture'));assert.throws(()=>cleanupReadCost('deleteFixture'));});

test('only exactly armed normal UI owned-plan deletion allowed; all sibling mutations refused',()=>{const call={functionKey:'deletePlan',payload:{planId:retained.planId}};assert.equal(cleanupUiRequestClass(call,{armedPlanDelete:true}),'approved-plan-delete');for(const c of [call,{...call,payload:{planId:'foreign'}},{...call,payload:{planId:retained.planId,extra:true}},{functionKey:'cancelSponsorReportCapture',payload:{planId:retained.planId}},{functionKey:'deleteFixture',payload:{planId:retained.planId}}])assert.equal(cleanupUiRequestClass(c,{armedPlanDelete:c!==call}),'forbidden');});
test('public cleanup one acknowledgement and exact receipt; completed report is never cancelled by private helper',async()=>{const{j}=fixture();let calls=0;const next=await cleanExactOwner({initial:{...j.finalJob,state:'cancelled',checkpoint:222,completedUnits:222,totalUnits:222},phase:'public',cancel:async()=>{calls++;return{success:true,job:{...j.finalJob,state:'cancelled',checkpoint:223,completedUnits:223,totalUnits:223,cleanupDone:true}};}});assert.equal(calls,1);assert.equal(next.checkpoint,223);});
