import fs from 'node:fs';import path from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {admitOwnerCleanup,loadOwnerCleanupAdmission,cleanExactOwner,ownerCleanupBound,cleanupReadCost,cleanupUiRequestClass,REFRESHED_FAILURE_SHA} from '../../scenarios/lz-ppm/seventeenth-owner-cleanup-contract.mjs';
import {retained} from '../../scenarios/lz-ppm/seventeenth-report-recovery-contract.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex'),canonical=x=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x,hash=x=>sha(JSON.stringify(canonical(x)));
const failedPath='/Users/mihaiperdum/Projects/forge-live-harness/evidence/lz-campaign/seventeenth-refreshed-forecast-resume-20260906/artifacts/scenarios-lz-ppm-campaign--e3c4b-rt-and-HTML-without-cleanup-chromium/seventeenth-refreshed-resume.json';
const failedBytes=fs.readFileSync(failedPath),failed=JSON.parse(failedBytes);assert.equal(sha(failedBytes),REFRESHED_FAILURE_SHA);
function response(body){const raw=JSON.stringify({data:{invokeExtension:{success:true,response:{body},errors:null}}});return{raw,rawEncoding:'forge-response-context-token-redacted-v1',responseSha256:sha(raw),responseBytes:Buffer.byteLength(raw),retainedResponseSha256:sha(raw),retainedResponseBytes:Buffer.byteLength(raw),httpStatus:200,outerSuccess:true,errors:null,body};}
// Synthetic accepted183 envelope is only a local negative/positive contract fixture.
// It never rewrites or promotes the real failed155 bytes and is never saved as approval.
function fixture(){
 const files=new Map([['html',fs.readFileSync(path.join(path.dirname(failedPath),'retained5300-actual-report.html'))],...Array.from({length:4},(_,n)=>['png'+n,Buffer.from('89504e470d0a1a0a','hex')])]);
 const j={phase:'readonly-reopen183',retained,completed:true,publicationObserved:true,sourceAndPreferencesPreserved:true,traceDiscarded:true,all5300ReportFieldsVerified:true,all5300HtmlFieldsVerified:true,reopenedAllPagesImmutable:true,reviewRequired:true,refreshedFailureReceipt:{path:failedPath,sha256:REFRESHED_FAILURE_SHA},aggregateFailureReceipt:failed.aggregateFailureReceipt,advanceCalls:0,events:[],uiRequests:[],finalJob:structuredClone(failed.finalJob),finalProbe:structuredClone(failed.finalProbe),report:structuredClone(failed.report),pages:structuredClone(failed.pages)};
 j.probes=[structuredClone(j.finalProbe),structuredClone(j.finalProbe)];
 for(let n=0;n<212;n++)j.events.push({stage:'getSponsorReportPage',value:response({success:true,page:j.pages[n%106]})});
 for(let n=1;n<=2;n++){const r={requestId:n,key:'presenceLeave',planId:retained.planId,state:'finished',requestedAtMs:n*10,dispatchedAtMs:n*10+1,completedAtMs:n*10+2,...response({success:true})};j.uiRequests.push(r);j.events.push({stage:'owned-departure-leave-observed',value:{planId:retained.planId,requestId:n,armedAtMs:n*10,requestedAtMs:r.requestedAtMs,dispatchedAtMs:r.dispatchedAtMs,completedAtMs:r.completedAtMs}},{stage:'owned-departure-unmounted',value:{planId:retained.planId,requestId:n}},{stage:'owned-departure-postblank-leaves',value:[n]});}
 j.events.push({stage:'download-saved',value:{sha256:sha(files.get('html')),bytes:files.get('html').length}});
 const i={schema:'retained-report-root-cleanup-approval-v2',approveCleanup:true,inspectionComplete:true,retained,refreshedFailureSha256:REFRESHED_FAILURE_SHA,domainVerificationPassed:true,ledgerVerificationPassed:true,rootInspectionCommit:'a'.repeat(40),reportSummaryHash:hash(j.report),pagesHash:hash(j.pages),finalProbeHash:hash(j.finalProbe),artifacts:[...files].map(([path,b])=>({path,role:path==='html'?'html':'png',sha256:sha(b),bytes:b.length}))};
 const seal=()=>{const journalBytes=Buffer.from(JSON.stringify(j));i.completedJournalSha256=sha(journalBytes);const inspectionBytes=Buffer.from(JSON.stringify(i));return {journalBytes,journalSha256:sha(journalBytes),inspectionBytes,inspectionSha256:sha(inspectionBytes),refreshedFailureBytes:failedBytes,refreshedFailureSha256:REFRESHED_FAILURE_SHA,readFile:p=>files.get(p)};};return{j,i,files,seal};
}
test('external exact completed journal and inspection admit; no invented terminal in executable',()=>{const f=fixture();assert.equal(admitOwnerCleanup(f.seal()).journal.finalJob.checkpoint,183);assert.throws(()=>loadOwnerCleanupAdmission({}),/required before test registration/);});
test('missing or unapproved root receipt and either mismatched byte digest refuse',()=>{for(const edit of [f=>f.i.approveCleanup=false,f=>f.i.inspectionComplete=false,f=>f.i.ledgerVerificationPassed=false,f=>f.i.domainVerificationPassed=false]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}const f=fixture(),v=f.seal();assert.throws(()=>admitOwnerCleanup({...v,journalSha256:'b'.repeat(64)}));assert.throws(()=>admitOwnerCleanup({...v,inspectionSha256:undefined}));});
test('active/stale/cleaned/failed terminal and changed owner identity refuse',()=>{for(const edit of [f=>f.j.finalJob.state='active',f=>f.j.finalJob.checkpoint=182,f=>f.j.finalJob.cleanupDone=true,f=>f.j.finalJob.requestId='foreign',f=>f.j.completed=false,f=>f.j.events.push({stage:'independent-audit-error'}),f=>f.j.traceDiscarded=false]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}});
test('lost private payload, wrong marker, missing page and uninspected/tampered artifact refuse',()=>{for(const edit of [f=>f.j.finalProbe.privateArtifacts[0].present=false,f=>f.j.finalProbe.publicArtifacts.at(-1).present=true,f=>f.j.pages.pop(),f=>f.i.artifacts.pop(),f=>f.files.set('html',Buffer.from('changed'))]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}});
test('complete owner flow exactly38 acknowledgements then stops; no extra calls',async()=>{const {j}=fixture();let calls=0;const out=await cleanExactOwner({initial:j.finalJob,phase:'private',cancel:async payload=>{assert.deepEqual(payload,{planId:retained.planId,jobId:retained.jobId});calls++;return{success:true,job:{...j.finalJob,checkpoint:183+calls,completedUnits:183+calls,totalUnits:183+calls,cleanupDone:calls===38}};}});assert.equal(calls,38);assert.equal(out.state,'complete');assert.equal(out.cleanupDone,true);});
test('false/throw/zero-progress/cross-job/false-final never retries',async()=>{for(const behavior of ['false','throw','same','other','notclean']){const {j}=fixture();let calls=0;await assert.rejects(cleanExactOwner({initial:{...j.finalJob,state:'cancelled'},phase:'public',cancel:async()=>{calls++;if(behavior==='throw')throw Error('unknown');if(behavior==='false')return{success:false,error:'unknown'};return{success:true,job:{...j.finalJob,state:'cancelled',id:behavior==='other'?'other':j.finalJob.id,checkpoint:behavior==='same'?183:184,completedUnits:184,totalUnits:184,cleanupDone:behavior!=='notclean'}};}}));assert.equal(calls,1);}});
test('monotonic and explicit bounded duration fail closed',async()=>{assert.equal(ownerCleanupBound(38),5798000);assert.throws(()=>ownerCleanupBound(39));const{j}=fixture();let n=0;await assert.rejects(cleanExactOwner({initial:j.finalJob,phase:'private',now:()=>n++?0:1,cancel:()=>{throw Error('must not dispatch');}}));});
test('only measured cleanup mutations priced and unknown operations still refuse',()=>{assert.equal(cleanupReadCost('cancelSponsorReportCapture','private'),192);assert.equal(cleanupReadCost('cancelSponsorReportCapture','public'),352);assert.equal(cleanupReadCost('deleteSponsorReport'),224);assert.equal(cleanupReadCost('deletePlan'),768);assert.throws(()=>cleanupReadCost('cancelSponsorReportCapture'));assert.throws(()=>cleanupReadCost('deleteFixture'));});

test('only exactly armed normal UI owned-plan deletion allowed; all sibling mutations refused',()=>{const call={functionKey:'deletePlan',payload:{planId:retained.planId}};assert.equal(cleanupUiRequestClass(call,{armedPlanDelete:true}),'approved-plan-delete');for(const c of [call,{...call,payload:{planId:'foreign'}},{...call,payload:{planId:retained.planId,extra:true}},{functionKey:'cancelSponsorReportCapture',payload:{planId:retained.planId}},{functionKey:'deleteFixture',payload:{planId:retained.planId}}])assert.equal(cleanupUiRequestClass(c,{armedPlanDelete:c!==call}),'forbidden');});
test('public cleanup one acknowledgement and exact receipt; completed report is never cancelled by private helper',async()=>{const{j}=fixture();let calls=0;const next=await cleanExactOwner({initial:{...j.finalJob,state:'cancelled',checkpoint:222,completedUnits:222,totalUnits:222},phase:'public',cancel:async()=>{calls++;return{success:true,job:{...j.finalJob,state:'cancelled',checkpoint:223,completedUnits:223,totalUnits:223,cleanupDone:true}};}});assert.equal(calls,1);assert.equal(next.checkpoint,223);});

test('actual failed155 can never authorize alone or be rewritten as passing155',()=>{const f=fixture(),v=f.seal();assert.throws(()=>admitOwnerCleanup({...v,journalBytes:failedBytes,journalSha256:REFRESHED_FAILURE_SHA}));assert.throws(()=>admitOwnerCleanup({...v,refreshedFailureBytes:undefined}));const changed=Buffer.from(JSON.stringify({...failed,completed:true}));assert.throws(()=>admitOwnerCleanup({...v,refreshedFailureBytes:changed}));});
test('both externally bound predecessor identities must agree exactly',()=>{for(const edit of [f=>f.i.refreshedFailureSha256='b'.repeat(64),f=>f.j.refreshedFailureReceipt.sha256='b'.repeat(64),f=>f.i.retained={...retained,jobId:'foreign'},f=>f.j.retained={...retained,planId:'foreign'}]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}});
test('212 fresh response bodies and two completed owned departures cannot be replaced by flags',()=>{for(const edit of [f=>f.j.events.shift(),f=>f.j.events[0].value.body.page={},f=>f.j.uiRequests[0].state='failed',f=>f.j.uiRequests[0].errors={},f=>f.j.uiRequests[0].planId='foreign',f=>f.j.events.find(e=>e.stage==='owned-departure-postblank-leaves').value.push(999),f=>f.j.advanceCalls=1,f=>f.j.events.push({stage:'actual-advance-dispatch'}),f=>f.j.probes.pop()]){const f=fixture();edit(f);assert.throws(()=>admitOwnerCleanup(f.seal()));}});
