import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {departOwnedPlan,armPresenceLeave} from '../../scenarios/lz-ppm/owned-plan-departure.mjs';
const source=fs.readFileSync(new URL('../../scenarios/lz-ppm/campaign-seventeenth-refreshed-resume.spec.ts',import.meta.url),'utf8');const old=source.match(/const stopUi=(async\(\)=>\{await drainUi\(\);await page.goto\('about:blank'\);await drainUi\(\);\});/);assert(old,'Frozen actual155 departure source required');
const depart=process.env.LZ_DEPARTURE_LEGACY==='1'?async p=>new Function('drainUi','page',`return (${old[1]})()`)(p.drain,{goto:p.blank}):departOwnedPlan;
const good={key:'presenceLeave',planId:'owned',state:'finished',httpStatus:200,outerSuccess:true,errors:null,body:{success:true},requestedAtMs:101,dispatchedAtMs:102,completedAtMs:103,requestId:9};
function fixture(alter,duplicate=false){let mounted=true,disposed=0;const log=[],observations=[],recorded=[];let resolve;const promise=new Promise(r=>resolve=r);const ports={planId:'owned',now:()=>100,drain:async()=>{log.push('drain');},findMounted:async()=>mounted?{}:null,confirmNonPlan:async()=>{log.push('non-plan-positive');},armLeave:()=>{log.push('armed');return {promise,observations,dispose(){disposed++;}};},clickBack:async()=>{log.push('back');mounted=false;const value=structuredClone(good);alter?.(value);observations.push(value);resolve(value);},confirmUnmounted:async()=>{log.push('confirmed-unmounted');if(duplicate)observations.push({...good,requestId:10});},blank:async()=>{log.push('blank');if(mounted)throw new Error('presenceLeave net::ERR_ABORTED by old beforeunload boundary');},record:(stage,value)=>recorded.push({stage,value})};return {ports,log,recorded,get disposed(){return disposed;}};}
test('real in-app Back precedes observed leave, unmount/drain and final blank',async()=>{const f=fixture();await depart(f.ports);assert.deepEqual(f.log,['drain','armed','back','confirmed-unmounted','drain','blank','drain']);assert.equal(f.disposed,1);assert.equal(f.recorded.find(x=>x.stage==='owned-departure-leave-observed').value.requestId,9);});
test('abort HTTP403/503 unknown/bodyfalse/wrongplan/wrongkey/oldreceipt all refuse before blank',async()=>{for(const edit of [v=>{v.state='failed';v.error='net::ERR_ABORTED';},v=>v.httpStatus=403,v=>v.httpStatus=503,v=>v.outerSuccess=false,v=>v.body={success:false},v=>v.planId='foreign',v=>v.key='getPresence',v=>v.requestedAtMs=99]){const f=fixture(edit);await assert.rejects(departOwnedPlan(f.ports));assert(!f.log.includes('blank'));assert.equal(f.disposed,1);assert(f.recorded.some(x=>x.stage==='owned-departure-leave-observed'));}});
test('duplicate terminal leaves cannot pass even when both succeeded',async()=>{const f=fixture(null,true);await assert.rejects(departOwnedPlan(f.ports),/Exactly one/);assert(!f.log.includes('blank'));assert.equal(f.recorded.find(x=>x.stage==='owned-departure-all-leaves').value.length,2);});
test('missing leave and disposed observation reject without accepting old receipts',async()=>{const observers=new Set();const w=armPresenceLeave(observers,{timeoutMs:5});await assert.rejects(w.promise,/not observed/);assert.equal(observers.size,0);w.dispose();const second=armPresenceLeave(observers);second.dispose();await assert.rejects(second.promise,/closed before/);assert.equal(observers.size,0);});
test('observer ignores unrelated reads but retains every future leave through drain',async()=>{const set=new Set(),w=armPresenceLeave(set);for(const fn of set)fn({key:'getPresence'});assert.equal(w.observations.length,0);for(const fn of set)fn(good);assert.equal(await w.promise,good);for(const fn of set)fn({...good,requestId:10});assert.equal(w.observations.length,2);w.dispose();assert.equal(set.size,0);});
test('non-Plan surface requires positive identification before blank',async()=>{const f=fixture();f.ports.findMounted=async()=>null;f.ports.confirmNonPlan=async()=>{throw new Error('unknown mounted surface');};await assert.rejects(departOwnedPlan(f.ports),/unknown/);assert(!f.log.includes('blank'));});

test('late duplicate triggered by blank is retained and fails postblank audit',async()=>{const f=fixture();const blank=f.ports.blank;let watched;const arm=f.ports.armLeave;f.ports.armLeave=()=>{watched=arm();return watched;};f.ports.blank=async()=>{await blank();watched.observations.push({...good,requestId:10});};await assert.rejects(departOwnedPlan(f.ports),/No additional leave/);assert.deepEqual(f.recorded.find(x=>x.stage==='owned-departure-postblank-leaves').value,[9,10]);assert.equal(f.disposed,1);});
