import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {ownerCleanupAdmissionForPhase} from '../../scenarios/lz-ppm/seventeenth-owner-cleanup-contract.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const inputs=['LZ_CLEANUP_COMPLETED_JOURNAL','LZ_CLEANUP_COMPLETED_SHA256','LZ_CLEANUP_ROOT_INSPECTION','LZ_CLEANUP_ROOT_INSPECTION_SHA256','LZ_CLEANUP_REFRESHED_FAILURE_JOURNAL','LZ_CLEANUP_REFRESHED_FAILURE_SHA256'];
function discover(extra={},broad=false){const env={...process.env,JIRA_BASE_URL:'https://wolfaenpak.atlassian.net',JIRA_ADMIN_EMAIL:'local-discovery@example.invalid',JIRA_API_TOKEN:'local-discovery-no-network'};for(const k of [...inputs,'LZ_SEVENTEENTH_CLEANUP_PHASE'])delete env[k];Object.assign(env,extra);return spawnSync(process.execPath,[path.join(root,'node_modules/@playwright/test/cli.js'),'test',...(broad?[]:['scenarios/lz-ppm/campaign-seventeenth-owner-cleanup.spec.ts']),'--project=chromium','--list','--reporter=json'],{cwd:root,env,encoding:'utf8',timeout:60000,maxBuffer:8*1024*1024});}
function report(result){assert.equal(result.signal,null);return JSON.parse(result.stdout);}
test('actual default and empty-phase discovery registers only a skipped cleanup, without reading dangling approval paths',()=>{for(const extra of [{},{LZ_SEVENTEENTH_CLEANUP_PHASE:'',LZ_CLEANUP_COMPLETED_JOURNAL:'/absent/never-read'}]){const result=discover(extra),j=report(result);assert.equal(result.status,0);assert.deepEqual(j.errors,[]);const item=j.suites[0].specs[0].tests[0];assert.equal(item.expectedStatus,'skipped');assert.equal(item.status,'skipped');assert.deepEqual(item.results,[]);}});
test('actual explicit approved-cleanup discovery refuses each of the six missing inputs before registration',()=>{for(const missing of inputs){const env=Object.fromEntries(inputs.map(k=>[k,k.endsWith('SHA256')?'a'.repeat(64):'/absent/never-read']));delete env[missing];const result=discover({...env,LZ_SEVENTEENTH_CLEANUP_PHASE:'approved-cleanup'}),j=report(result);assert.equal(result.status,1);assert.equal(j.suites.length,0);assert(j.errors.some(e=>e.message.includes(missing+' required before test registration')));}});
test('actual explicit approved-cleanup still rejects invalid complete inputs and wrong nonempty phases',()=>{const env=Object.fromEntries(inputs.map(k=>[k,k.endsWith('SHA256')?'a'.repeat(64):'/absent/never-read']));const invalid=report(discover({...env,LZ_SEVENTEENTH_CLEANUP_PHASE:'approved-cleanup'}));assert.equal(invalid.suites.length,0);assert(invalid.errors.some(e=>e.message.includes('ENOENT')));for(const phase of ['cleanup','false',' ']){const result=discover({LZ_SEVENTEENTH_CLEANUP_PHASE:phase}),j=report(result);assert.equal(result.status,1);assert.equal(j.suites.length,0);assert(j.errors.some(e=>e.message.includes('Unsupported explicit owner cleanup phase')));}});
test('actual broad discovery no longer contains owner-cleanup approval failure; inherited cross-test imports remain explicit',()=>{const result=discover({},true),j=report(result);assert.equal(result.status,1);assert(j.errors.length>0);assert(j.errors.every(e=>!e.message.includes('LZ_CLEANUP_')&&!e.message.includes('owner-cleanup')));assert(j.errors.some(e=>e.message.includes('should not import test file')));});
test('phase adapter is inert only when absent/empty; explicit phase cannot bypass mandatory approval',()=>{assert.equal(ownerCleanupAdmissionForPhase({}),null);assert.equal(ownerCleanupAdmissionForPhase({LZ_SEVENTEENTH_CLEANUP_PHASE:''}),null);assert.throws(()=>ownerCleanupAdmissionForPhase({LZ_SEVENTEENTH_CLEANUP_PHASE:'approved-cleanup'}),/required before test registration/);for(const phase of ['false',' ',false,0])assert.throws(()=>ownerCleanupAdmissionForPhase({LZ_SEVENTEENTH_CLEANUP_PHASE:phase}),/Unsupported explicit/);});
